### ISSUE TITLE
Doc on hover

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#10]
When the user hovers the mouse over a standard library function, we should pop up a tool tip with basic type and documentation for that symbol.

**Comment by nixorn** [comment]
Hi from BountySource. I see this issue listed here https://www.bountysource.com/teams/codeworld/bounties, can I try to solve this?

**Comment by nixorn** [comment]
Is this issue still actual? Or any issues on bountysource?

**Comment by cdsmith** [comment]
Hi.  Yes, this is still an actual issue, and you are welcome to work on it.  I'm not aware of anyone else doing any work on this.  Let me know if you have any trouble getting started.

You probably want this feature to use the same information as autocomplete, which is loaded here: https://github.com/google/codeworld/blob/master/web/js/codeworld_shared.js#L148 and the file being parsed is https://code.world/codeworld-base.txt .  Right now, the doc comments are ignored when reading that file, and only names and type signatures are pulled out.  I'd suggest starting with just that; a good first step would be to just display names and type signatures.  To get the docs as well, you'd want to extend the parsing at https://github.com/google/codeworld/blob/master/web/js/codeworld_shared.js#L247 to read and build up a string that's applied to the next symbol.

**Comment by nixorn** [comment]
Thanks for explanation, I started.

**Comment by nixorn** [comment]
Looks CodeMirror tracks only editor cursor, not mouse coordinates, and have no event like "token.mouseover()" from jquery. I have not figure out with CodeMirror completely yet, and in search of best way.

Now I see 2 options:
1. use CodeMirror cursor events to determine when some text become highlighted variable, and create hidden tooltip element for this token like [here](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_tooltip). Css solution without extending CodeMirror defaults. 
2. write CodeMirror custom addon, which will handle hover events. I'm not sure about this, need to deeper understanding of CodeMirror internals for that. 

I did not start parsing yet, left it for dessert.

**Comment by cdsmith** [comment]
Oh, it looks like that addon may already exist in https://www.npmjs.com/package/codemirror-extension  I don't know much about npm, so I'm not sure how to best incorporate that into the project.

**Comment by cdsmith** [comment]
It looks like this is working.  Great!  I'll file a few minor bugs, but I think we can close this issue.  Thanks so much for the contribution.
