### ISSUE TITLE
CW.Driver: Drawers are separated from their type signatures

### ISSUE THREAD

**Issue by sjakobi** [google/codeworld#1005]
https://github.com/google/codeworld/blob/dc175283929abd546a03af627965fc545208b157/codeworld-api/src/CodeWorld/Driver.hs#L395-L402

Do you mind if I join these type signatures with their respective function bodies, @cdsmith? I find this separation makes the function bodies harder to understand.

**Comment by cdsmith** [comment]
Yes, that's fine.  I believe there used to be separate implementations for GHC vs blank-canvas, but I merged the implementations, so they can now be moved together.
