### ISSUE TITLE
The inspect dialog should replace the run section of the screen

### ISSUE THREAD

**Issue by sjakobi** [google/codeworld#1008]
Motivation:

* The current popup for the inspect dialog is somewhat inelegant
* The run section isn't of much use when in inspect mode.
* In #712 we want to control the inspect dialog from the editor. This would look funny when we have a popup in front of the editor.

**Comment by sjakobi** [comment]
@cdsmith I'd like to work on this but I'm not sure where to start. Could you give me some pointers?

**Comment by cdsmith** [comment]
To clarify, what I understand Simon is working on is:

- The tree control for navigating the scene graph will move to a new panel that replaces the message area when it's active.
- The display area on the current dialog (that displays the selected node from the tree) will go away, and instead the selected node will replace the program output.  So there won't be two pictures at all any more.

**Comment by cdsmith** [comment]
The second of these is already done.

**Comment by Powell-v2** [comment]
@cdsmith what exactly needs to be accomplished here?

**Comment by cdsmith** [comment]
Sure, let me explain in more detail.  When you run any CodeWorld graphic program (for example: https://code.world/#PuGvYUnxim9aAE4l4HF672Q), you see an Inspect button on the bottom right of the screen.  Clicking that button opens up a UI where you can browse through the "scene graph" of the picture -- how it's composed out of simpler pieces, and such.  This opens in a popup window.  What I'd like to happen instead is that instead, it replaces the output area, that occurs below the canvas and show error messages and console output.  When you click Inspect again, it should switch back.

![image](https://user-images.githubusercontent.com/544744/89739565-97aa1880-da4f-11ea-9bf1-f473cbdc29b5.png)
