### ISSUE TITLE
Group Extras javadoc together in Guide

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1022]
The documentation for various Extras modules is taking up a bit too much space in the Guide.  We want it there, but in a single item until expanded.

**Comment by Powell-v2** [comment]
Is this how you imagined it?

![image](https://user-images.githubusercontent.com/25308326/88289543-b1302e00-ccf5-11ea-9e1f-510dd5dd77e8.png)

**Comment by cdsmith** [comment]
Yes, that looks great.  I would probably want to change the structure to put the non-extras reference at the top level, but I assume you are reading the structure from the codeworld.shelf file?

Can it be nested more than two levels?  That doesn't need to be possible; I'm just curious.

**Comment by Powell-v2** [comment]
> I assume you are reading the structure from the codeworld.shelf file?

Yes, I believe that's where the structure is coming from.

> Can it be nested more than two levels?

Sure thing, it can be nested as many times as needed.

**Comment by cdsmith** [comment]
That's great!  That should scale to much more documentation in the future.  For example, we could add a teacher's guide with tips on presentation, on building customized activities, on configuring the requirements checker, etc.  I've been unable to add some of these things because they would overwhelm students, but if advanced documentation is hidden under one section, a lot more becomes possible.

**Comment by Powell-v2** [comment]
Do you want start reviewing changes already or I should wait with the PR until you adjust the structure?

**Comment by cdsmith** [comment]
I'm not sure what you mean.  I don't think I can change the structure until this change is in.  Right now, there is no way to nest documentation at all.

**Comment by cdsmith** [comment]
To clarify what I meant, the current `codeworld.shelf` file is at https://github.com/google/codeworld/blob/master/web/help/codeworld.shelf.  It is a JSON file that describes the help window organization.  Right now, inside the "named" object, the key/value pairs are the collapsible sections.

```
{
  ...
  "named": {
    "Section 1": "help/Section1.md",
    "Section 2": "help/Section2.md",
    "Section 3": "help/Section3.md",
    ...
  }
}
```

I think you should modify the code to accept entries in that object whose values are nested objects.  Something like this:

{
  ...
  "named": {
    "Section 1": "help/Section1.md",
    "Section 2": "help/Section2.md",
    "Section 3": {
      "overview": "help/Section3.md",
      "named": {
        "Part 1": "help/Section3Part1.md",
        "Part 2": "help/Section3Part2.md",
        ...
      }
    },
    ...
  }
}
```

I'm not attached to this specific format, but hopefully you get the idea.  In your initial pull request, it's fine to modify `codeworld.shelf` to just group all of the appendices the way you have them now.  I just wanted to be sure that it will be easy to change that.

**Comment by cdsmith** [comment]
Thinking about this in detail does bring up a question.  When you open a section with nested subsections, what happens?

My example format above assumes that there is an overview document that is loaded.  Since there's no place to put the table of contents for that overview document, I assume you'd just skip that part, and the overview should be short enough not to require it.

Another alternative would be to automatically load the first child document, so expanding a section of the accordion would also expand its first child.  But that could be a weird experience, and make it harder to navigate to later child sections.  So I'm not in favor of this.  I prefer the overview approach.

**Comment by cdsmith** [comment]
Also: I haven't seen your code yet, but one thing to keep in mind is that a viewer's current location in the help is saved in local storage, and restored when help is reopened.  That is something else that will have to be updated.

**Comment by Powell-v2** [comment]
> When you open a section with nested subsections, what happens?

Right now the section just gets expanded, section on the right stays intact. I'm hesitant about the possibility to load an overview doc as accordion's markup has to be structured in a [very specific way](https://api.jqueryui.com/accordion/#option-active). Is it really important? If so, I'll try to find a workaround.

> one thing to keep in mind is that a viewer's current location in the help is saved in local storage, and restored when help is reopened

At first glance, this might prove tricky to achieve with nested accordions as we'd have to manually determine indices (locations) in all parents to reveal article's title in the navbar. I'll look into it next week.

**Comment by cdsmith** [comment]
> I'm hesitant about the possibility to load an overview doc as accordion's markup has to be structured in a very specific way. Is it really important? If so, I'll try to find a workaround.

I guess my question is: when I select a section that has nested subsections, what loads?  If it is the first subsection, that's fine and the overview isn't needed.  But if it's a blank page, that would be unfortunate.

**Comment by cdsmith** [comment]
We definitely need the saved location restore to keep working.  That makes the guide a lot more usable.  (Without it, you become scared to click on a code sample, because reopening the guide loses your place.)

**Comment by Powell-v2** [comment]
> when I select a section that has nested subsections, what loads?

Accordion's children, content on the right hand side stays intact (we load intro by default after initializing the guide). I can arrange for loading the first item in the list, but you pointed out earlier that it's undesirable and I tend to agree with you.

**Comment by cdsmith** [comment]
Oh, I see.  Well that's probably okay.
