### ISSUE TITLE
Cabal issue when running unit tests

### ISSUE THREAD

**Issue by starsandspirals** [google/codeworld#1023]
When attempting to run the automated tests via test.sh, I get a set of errors related to module imports from Cabal, specifically relating to the module Util.EmbedAsUrl. 

It tells me that various modules need to be added to the cabal file, such as bytestring, base64-bytestring and ghc-lib-parser, but this module doesn't appear to have its own cabal file and these modules are already present in the codeworld-api cabal file. 

This could be an issue with my local environment (I didn't have this issue last week), but I thought it was worth flagging up.

**Comment by sjakobi** [comment]
This is due to https://github.com/google/codeworld/commit/402e2888d2c27dea9878037d2f9bd350898b7df6 which should also have updated the test dependencies.
