### ISSUE TITLE
Clean up debug simulation state handling

### ISSUE THREAD

**Issue by sjakobi** [google/codeworld#1025]
I find code like this very hard to understand:

https://github.com/google/codeworld/blob/d0349b1cf977f263af93bfa31d3d20ea3f9e426e/codeworld-api/src/CodeWorld/Driver.hs#L2111-L2122

The use of `head` and `tail` makes it difficult to see whether it's even total.

It might help to use a dedicated data structure for the timeline. E.g.

```
data X a =
  { past :: [a]
  , present :: a
  , future :: [a]
  }
```

**Comment by cdsmith** [comment]
I'll take care of this, just to close it.

**Comment by sjakobi** [comment]
> I'll take care of this, just to close it.

Cool! I was hoping that this could also help make `debugSimulationOf.draw`, `debugInteractionOf.draw` and `prependIfChanged` total. But maybe that's not so important.
