### ISSUE TITLE
f(^=^) claims to be a function application without parentheses

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1031]
**Program:** https://code.world/#PgN_HiI1hYdvzLlJEODI__Q

**Comment:**

This is confusing because there are parentheses around the operator.  A different error would be better.

**Message:**

    program.hs:3:8-12: error:
        • Missing punctuation before this expression.
          Perhaps you forgot a comma, an operator, or a bracket.
        • To multiply, please use the * operator.
          For example: f * (^=^)
        • To apply a function, add parentheses around the argument.
          For example: f((^=^))

**Comment by cdsmith** [comment]
This in, indeed, confusing, but I'm not sure what the message should say.
