### ISSUE TITLE
Cryptic EOF message when reading from stdin

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1036]
**Program:** https://code.world/haskell#Pnv3MyvNwVaEJ9Duzbn4PGg

**Message:**

    <stdin>: hGetLine: end of file

**Comment by cdsmith** [comment]
The user was attempting to read from stdin.  Since it's not connected to anything, they got an EOF right away.

I am not sure it's worth the time to improve the error message, when users really want standard input to work, instead.
