### ISSUE TITLE
thickPolyline is sometimes filled instead

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1052]
**Shared Program**: https://code.world/haskell#Px4A93a9xi_uHTP9Q8wtksQ

**Description**

If you play around with this, there's a drawing quirk that surfaces in specific situations.  It only happens when the blue line is short enough, and when the canvas is large enough.  Reducing the number of levels seems to help, too, in reproducing.  But when these conditions are true, the thickPolyline becomes solid and filled in.

![image](https://user-images.githubusercontent.com/544744/60817859-7b5fec00-a16a-11e9-9e2f-b1645b9e0a78.png)

(Note that the solid area is actually rendered as a thin line in the inspect window, which is smaller.  The same thing happens if the canvas is resized smaller.  I suspect this has to do with drawing being faster?) 

The blue line is the first thing in the scene graph, which makes it the last thing drawn.  I suspected there was some interference with a fill from an adjacent drawing.  But there's really no adjacent drawing that does a fill.

FYI @polux

**Comment by cdsmith** [comment]
Simpler reproduction: https://code.world/#PuhS6rQjtFvzBDJY3zVIKPA

You do have to drag the canvas so it's larger than the default 500x500 before the effect is visible.

**Comment by cdsmith** [comment]
So that eliminates weird interactions with adjacent shapes.  It looks like there's just something wrong with `thickPolyline` itself.

**Comment by cdsmith** [comment]
This seems to be a browser bug?  https://jsfiddle.net/8hs5jrdu/

**Comment by polux** [comment]
Indeed, the jsfiddle link works as intended on firefox, but I can reproduce the bug in chrome 75. Interestingly, it disappears if one disables canvas hardware acceleration. I have an Intel HD Graphics 520, maybe you've got the same?

**Comment by cdsmith** [comment]
I've filed a bug with Chrome about this issue.  I'll follow up there, but it doesn't make sense to try to work around this in CodeWorld.  So I'll close this one.
