### ISSUE TITLE
Reflex programs are very slow

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1057]
**Shared Program**: https://code.world/haskell#P6gA0a82KeXSlz2_HBxOGxA

**Description**

This is a trivially simple program.  It just spins a single picture on the screen.  But it runs roughly, going through cycles of poor frame rate about once per second.  The slowness seems to be independent of being in debug mode, or of the screen size, so it looks like it's Reflex or my integration that's producing garbage rapidly.

**Comment by chessai** [comment]
Have you tried increasing GHCJS' gc interval? I know this affected our code at work, and we saw performance increases from it.

**Comment by cdsmith** [comment]
I don't know how to do that.  Do you?

**Comment by chessai** [comment]
You can pass -DGHCJS_GC_INTERVAL=<MILLISECONDS> to GHCJS

**Comment by chessai** [comment]
See https://github.com/ghcjs/ghcjs/issues/550

**Comment by cdsmith** [comment]
Thanks!  I am not sure that increasing the interval would be better, though, if it means longer pauses when they happen.  I'll first try to look into reducing the cause of slowness in the first place.

**Comment by cdsmith** [comment]
It's notable that https://code.world/haskell#PpSDbZUNs443eEWzoHZSezQ is essentially the same program using the older `reflexOf` API, and it doesn't suffer from the same slowness.  This suggests to me that there's something wrong with the ReaderT / DynamicWriterT monad stack that I implemented this weekend.  I wouldn't expect runtime performance to be any different, since the two should be executing essentially the same network.

**Comment by cdsmith** [comment]
https://code.world/haskell#Pi4c2B1tdHXcYbuR0L4v8WQ is an experiment with increasing the GC interval.  Unfortunately, it makes things a lot worse.  It seems that having a short gc interval is the only thing that saves us from an even more unresponsive program!  In fact, setting the GC interval to 200 ms makes things a lot better.

That's not a serious suggestion.  But something about `reactiveOf` is spewing allocations so fast that the garbage collector cannot keep up.

**Comment by cdsmith** [comment]
(And although many of the examples I'm posting use `debugReactiveOf`, it remains the case that the same performance problems are seen with `reactiveOf`.  I'm only using `debugReactiveOf` because that's what I've been developing on today, so I'm testing it.)

**Comment by cdsmith** [comment]
This seems to have something to do with the monad stack.  I should test with https://github.com/qfpl/reflex-basic-host and see if they are doing something different that fixes the problem.

**Comment by cdsmith** [comment]
@cartazio helped investigate this last weekend at NY CoHack.  Here's what we found:

The stuttering is entirely due to an interaction between the JavaScript garbage collector and the GHCJS RTS garbage collector.  The program fills the JavaScript heap, causing JavaScript to aggressively garbage collect.  GC performance impact spikes under the high memory load.  But these JavaScript garbage collectors don't solve the problem, because the GHCJS RTS still maintains JavaScript pointers to the memory until GHCJS's own RTS garbage collector runs.
The GHCJS RTS garbage collector only runs about once per second.  When it runs, it does fix the problem, leading to periods of smooth animation.

If the program maintains a small live heap, it's easy to solve this problem by setting the GHCJS gc interval to a very small value, like 50 ms.  See https://code.world/haskell#Plu2OtSus-lRhp25aedl0Ig  However, this is cost too much performance if the application is more complex.

GHCJS keeps a list of weak pointers, and:
* Reflex programs in CodeWorld across the board seem to slowly leak weak pointers over time, so this list grows into the tens of thousands after the program has been running for a while.  This doesn't seem to have a huge performance effect.  These pointers survive across GHCJS RTS garbage collections.
* Using the new `reactiveOf`, though, causes weak pointers to be created at a far, far greater rate.  These new weak pointers do not survive GHCJS RTS garbage collection, and so the weak pointer list drops to a smaller size again when the garbage collector runs.  (But, it continues to grow slowly over time for the reasons in the previous point.)

This suggests that the extra garbage is a lot of weak pointers.  That further explains why they might tend to live longer until the GHCJS RTS garbage collector runs.  (JavaScript's memory model doesn't have weak pointers, so GHCJS must simulate them.)

I still don't understand why `reactiveOf` creates so many extra weak pointers.

**Comment by cdsmith** [comment]
We also found that lots of simultaneous events causes even simple reflex programs to halt.  This seems to be true regardless of GC pauses, but is far more true for `reactiveOf` programs that `reflexOf`.  But it also depends on the device the program runs on.

**Comment by xplat** [comment]
Not sure if it fixes the problem in https://github.com/google/codeworld/issues/1057#issuecomment-518923951 though ... if you have a repro case for that one we could look at it.

The reason so many weak pointers were created by reactiveOf is because doing a monadic bind on a Dynamic causes the Kleisli arrow to rerun, and new dataflow nodes and subscriptions to be created, every time the bound Dynamic updates.  We're looking at ways to avoid this, but it's not an easy problem.  The most reliable way is to use Applicative whenever possible, especially for busy events like timers and mouseMove.

**Comment by cdsmith** [comment]
@xplat After this change, I can no longer reproduce the latter problem, either.  I suspect it was just that the larger rate of memory usage caused the GC thrashing to become many times worse.

I suspect that I should really limit the frequency of mouse movement events in CodeWorld programs, anyway, but the fix to use Applicative for Dynamics mitigated the symptom.
