### ISSUE TITLE
Attempting to import an unknown module gives a confusing error message.

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1068]
**Program:** https://code.world/haskell#

**Comment:**

GTK

**Message:**

    program.hs:1:1-22: error:
        Could not find module ‘Graphics.UI.Gtk’
        Use -v to see a list of the files searched for.

**Comment by cdsmith** [comment]
This user was apparently looking for GTK.  It's not available.  However, the `Use -v to see a list of files searched for.` is not useful. I can add a sanitizer message that replaces it.

**Comment by cdsmith** [comment]
One interesting aspect of this problem is that the error message is equally wrong for Haskell mode.  This suggests that maybe the error sanitizer should also run in Haskell, but just with a smaller set of replacements.

**Comment by cdsmith** [comment]
This was already fixed for CodeWorld mode.  I'm going to close this, since there are lots of reasons not to start mucking with GHC messages for Haskell mode.
