### ISSUE TITLE
Forbidden language features (even in a comment) => red program window but nothelpful message.

### ISSUE THREAD

**Issue by misterbeebee** [google/codeworld#1072]
**Shared Program**: https://code.world/haskell#PvmcFl0m1uGPxR-OH8_lVeQ

**Description**

Attempting to run a program with forbidden language features, results in a red program window but no helpful message.

Web browser's developer console shows the relevant error message:

```
codeworld_shared.js:669 POST https://code.world/compile 400 (Bad Request)

codeworld.js:1130 Can not parse error header: : error: Sorry, but your program uses forbidden language features.
```

It would be user-friendly to display this error message in the main web page UI.

It might also be useful to link to documentation, to help the user find their use of forbidden features.

The trigger is here:

https://github.com/google/codeworld/blob/master/codeworld-compiler/src/CodeWorld/Compile/Stages.hs
```
checkDangerousSource = do
    src <- decodeUtf8 <$> getSourceCode
        (src =~ (".*TemplateHaskell.*" :: Text) ||
          src =~ (".*QuasiQuotes.*" :: Text) ||
          src =~ (".*glasgow-exts.*" :: Text)) 
```

Particularly, it's possible, albeit unlikely, to get a program obliquely banned by using offending text in a harmless way (such as in a string or comment.)

One frustrating failure mode is:

1. Use a forbidden feature, compile breaks.
2. Comment out the forbidden code, but compile is still broken, because comments aren't ignored by `checkDangerousSource`
3. Be confused.

For now, this GitHub issue can serve as documentation for CodeWorld "forbidden language features", as soon as Google indexes it :)

**Comment by cdsmith** [comment]
This was introduced when we added error highlights in the editor.  Error messages are now parsed to identify their location in the source code.

A simple fix would be to add "program.hs:1:1: error:" to the beginning of the message.  But even better would be to find the location of the disallowed language feature and include it in the error message.

**Comment by cdsmith** [comment]
The problem about finding the bad language feature in a comment is lower priority for me.  But we do now have the tools to solve that problem, too.  `codeworld-compiler` now links `ghc-lib-parser`, and `parseDynamicFilePragma` can be used to parse language and options pragmas from the source code into dflags, and then we can check for use of the language flags in the resulting `DynFlags` value.  There's existing code for this in `CodeWorld.Compile.Framework` `ghcParseCode`.

**Comment by cdsmith** [comment]
https://github.com/google/codeworld/blob/master/codeworld-compiler/src/CodeWorld/Compile/Framework.hs#L210 is relevant to the last comment.  That `dflagsWithPragmas` is where we really want to check to see whether template haskell is enabled.

**Comment by cdsmith** [comment]
This commit fixed the error message.  I'll open a new issue for more precise parsing.
