### ISSUE TITLE
Layout-aware auto-indent

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1081]
**Program:** https://code.world/#PUuoQnOFSIJrBVVdXYn3Jwg

**Comment:**

: (

**Message:**

    program.hs:3:1: error: parse error on input &

**Comment by cdsmith** [comment]
The problem here is starting a new line with no indent.  It's a very common problem, and I wonder if some kind of layout-aware pre-parsing is called for.  That seems excessive, though.

**Comment by cdsmith** [comment]
I should be able to automatically increase the indent if you start a new line and there are brackets still open in the previous line.  Right now, auto-indent goes to the same indent as the previous line.  A new auto-indent scheme would look like this.  In each token *context*, store the indent level of the previous line (if any) that began inside this context.  Upon auto-indent, scan up the context stack to find the innermost context that has a most recent line indent.  Set the indent to that, except that if one must pass a bracket context first, then add an additional indent level (e.g., 4 spaces) .

That would not have helped this student directly, unfortunately.  There was no way, in this case, to predict that the indent was needed.  But it may have helped indirectly, in that it may have gotten the student accustomed to indents before they wrote this.

**Comment by cdsmith** [comment]
If I did want to solve this problem for the reporting student, I would probably add a rule that changes the indent just after they type an & at the beginning of a line.  This is possible with CodeMirror's "electric" indent feature.

**Comment by cdsmith** [comment]
In fact, one could make up a list of characters that can never occur at the top level of a layout context, and then set the electric indent pattern to recognize typing any of them at the beginning of a line.  This would include any symbol character (crucially, including `&`), any close-bracket, a comma, a colon, an equal sign, a vertical-bar (`|`) which might be an attempt to write a guard.  When one of these is typed and electric indent is triggered, one would check whether the symbol is a new statement in a layout context, and if so, attempt to indent it to avoid this being the case.  (There is a weird case here where indenting would put it in a new containing layout context, and in this case, I suppose one must just give up...)

**Comment by cdsmith** [comment]
The final piece of this is that I want to make a list of tokens or characters that cannot end an expression, and also add an indent level if a line ends with one of those.  That way, if you write `program =` and press enter, you should be indented.  The best way to do this is probably to keep a new attribute in the token state that remembers if this is a non-indent-ending token: an infix operator, comma, equal sign, etc.
