### ISSUE TITLE
CodeWorld website should start cleanly after server reboot

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#110]

**Comment by cdsmith** [comment]
Fixed on the server.

Unfortunately, the number of steps outside the install scripts to set up a new running server is getting longer: (1) grab CodeWorld source, (2) set client ID, (3) install SSL certificates, (4) install and configure nginx, and (5) set up init.d scripts.  I could use some automation for this, and the right answer is probably related to Docker.

Anyway, that's a future step.  Closing this issue.

**Comment by bbarker** [comment]
Should I open a new issue to create a docker container? Might be a good way for me to get started with the project. Any objections to me using a nix-based docker container, if so?

**Comment by cdsmith** [comment]
I don't know much about docker or nix, honestly.  I don't object to having a docker container, but I'd have to figure out how that works with my workflow.  I'm happy to do that.  Since you mentioned nix, I know @Gabriel439 had done some work on nix-izing the build system, if that is helpful.

Just as a heads-up, the build process does patch and build a modified copy of GHC, so that might be an impediment in setting up the build process to use existing nix packages.

**Comment by bbarker** [comment]
It sounds like @Gabriel439's work would definitely be helpful for me; I'm not a nix expert myself but do use it frequently. As to workflows, I prefer to not use individual docker containers while developing myself, but rather use nix; then I package this up in a container for production/distribution.

**Comment by Gabriel439** [comment]
@bbarker: I can push what I have later this week, but there were some issues with the generated JavaScript so it's still a work in progress

**Comment by Gabriel439** [comment]
@bbarker: Sorry for the delay.  I pushed my work-in-progress branch to Nix-enable CodeWorld here: https://github.com/Gabriel439/codeworld/tree/gabriel/nix

Here's the diff: https://github.com/google/codeworld/compare/master...Gabriel439:gabriel/nix

You should be able to run `nix-build` from the top-level directory to build the server.  However, if you run it you will find issues which (if I remember correctly) appeared to be related to not building the `codemirror` JavaScript assets correctly.  That's as far as I got.

**Comment by bbarker** [comment]
@Gabriel439 Sorry for the long delay in replying! Starting to circle back to this after a major life event and some other distractions. I made a few updates and rebased on master at https://github.com/bbarker/codeworld/tree/bbarker_nix, and I think i'm now likely getting the same issue you had:

```
http 200 http://registry.npmjs.org/concat-map
info attempt registry request try #1 at 01:15:39
http request GET http://registry.npmjs.org/require-relative
http 200 http://registry.npmjs.org/require-relative
error: getting attributes of path '/home/brandon/workspace/codeworld/third_party/CodeMirror/function-highlight-addon.js': No such file or directory
```

**Comment by cdsmith** [comment]
@bbarker You're probably running into problems caused by https://github.com/google/codeworld/commit/9692579dee97d8437e21917a4629211d744efc73

Basically, that file doesn't exist any more.

**Comment by bbarker** [comment]
Ah, thanks, I should have dug deeper. Got a bit farther and now I'm back to the usual problem of version mismatches in cabal/nix, which I'll try to figure out:

```
Configuring base-compat-batteries-0.10.1...
Setup: Encountered missing dependencies:
bifunctors >=5.5.2 && <5.6
builder for '/nix/store/538zpm1k1adpkh5zqcq2slqikw7ppnmp-base-compat-batteries-0.10.1.drv' failed with exit code 1
building '/nix/store/bhpc0xfm3ixd94mk79jj588k28vqz6mz-base-orphans-0.7.drv'...
cannot build derivation '/nix/store/bbd9yfd15af870pix3czfn9hkc89pzgr-text-show-3.7.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fm1qm3yw8xhkx9x18snp5zam82akxk5n-blank-canvas-0.6.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vpx2dmjm4khkr55lzjlj8dqsnmm3fk0m-codeworld-api-0.3.1.drv': 1
dependencies couldn't be built
cannot build derivation '/nix/store/wbcabpsb18n2piqkykxlsn9jghbxjanx-codeworld-game-server-0.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/4aby92mhihxpmmaj202bhff8sqcv7z0n-codeworld-server-0.1.drv', '/nix/store/lryq02y8w3ylmk9m8ns45yh49hbw5whv-web.drv', '/nix/store/wbcabpsb18n2piqkykxlsn9jghbxjanx-codeworld-game-server-0.1.drv' failed
```
