### ISSUE TITLE
The CodeWorld standard library module should follow Haskell conventions

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#111]
The two modules `HaskellPrelude` and `CodeWorld` exist to allow people to write standard Haskell in CodeWorld.  `HaskellPrelude` contains a copy of the standard Haskell prelude, intended to replace the customized library in CodeWorld.  At the same time, the CodeWorld module makes the major CodeWorld functionality (which would normally be included in the prelude) accessible to programs using HaskellPrelude.

This is great... except that the `CodeWorld` module follows CodeWorld conventions, such as using the `Number` type and uncurrying its functions, even though it's intended to be used by standard Haskell programmers.

This is just a matter of laziness.  I should rewrite CodeWorld to follow Haskell conventions instead.

**Comment by bergey** [comment]
I'm teaching a second-year high school CS class using CodeWorld, and this would make the class go much more smoothly.  I may have some time this weekend at HacPhi to put together a PR.

Thanks for making CodeWorld, and making the standard Prelude accessible.

**Comment by cdsmith** [comment]
If I make this change, will it be a problem that it breaks all of the existing code written in your class?

**Comment by cdsmith** [comment]
As of now, the editor modes are different depending on the use of HaskellPrelude.  I'm intending to work on the major change this week.

In the end, we'll have two packages:

1. codeworld-api, which exports an idiomatic Haskell API for CodeWorld drawing abstractions.
2. codeworld-base, which re-exports all base modules except for Prelude, re-exports the Haskell prelude under the name HaskellPrelude, and exports a new Prelude with the simplified standard library.  It will delegate to codeworld-api for drawing code.

I'll then export the editor by two separate URLs:

* http://code.world -- builds with codeworld-base and hides base, and uses the standard set of CodeWorld language extensions.
* http://code.world/haskell - builds with base and codeworld-api, and no language extensions by default.

Saved projects will be separate between the two URLs, since projects saved in one are unlikely to run in the other.

For compatibility, I'll continue exporting the CodeWorld module in its current form from codeworld-base.  Then anyone who wants can swap to the pure Haskell implementation at any time.

**Comment by bergey** [comment]
Sounds great.  Thank you for all of this.

**Comment by cdsmith** [comment]
There's now a preview of this available at http://code.world/haskell.  For example, see https://code.world/haskell#Qi9VXFWE-oTA7-w25ZcXwKA

I need to work on some of the details; in particular, I'm pretty sure there's some inconsistency in whether certain APIs use degrees or radians.  The codeworld-api package shouldn't be considered stable.

**Comment by cdsmith** [comment]
I believe this is basically done.  There's a lot of documentation left to write, and you should feel free to request changes and additions that would make this more useful to you.

**Comment by timbod7** [comment]
This is great - thanks so much for making these changes.
