### ISSUE TITLE
Deprecation message suggests wrong replacement

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1146]
**Program:** https://code.world/#P3gQwjrer2MNAX_MyA1T2-Q

**Comment:**

inhw

**Message:**

    program.hs:2:59-63: warning:
        In the use of azure
        (defined in the standard library):
        "Please use RGB(210, 0.75, 0.5) instead of azure.
         The variable azure may be removed July 2020."

**Comment by cdsmith** [comment]
There's nothing more that can be said here.  The student may not like the deprecation, but it was done for good reasons.

**Comment by cdsmith** [comment]
Actually, this is a bug!  The suggestion should be HSL, not RGB!
