### ISSUE TITLE
<<loop>> runtime error should be replaced by something nicer.

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1156]
**Program:** https://code.world/#P6qNtcgDyYzzfGcrmuZ7O2g

**Message:**

    <<loop>>

**Comment by cdsmith** [comment]
I thought this should be easy, but catching `NonTermination` doesn't seem to be working as expected.  I'm still getting the "<<loop>>" message rather than the modified message.

**Comment by cdsmith** [comment]
Never mind.  It worked when I tried again.  I must have forgotten to restart the server or something.
