### ISSUE TITLE
Students looking for LSU-specific modules on main CodeWorld site

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1158]
**Program:** https://code.world/#PMMCEenljwhO2B3bqshFwUg

**Comment:**

this is bugged

**Message:**

    program.hs:4:1-22: error:
        Could not find module Lessons.Penguin

**Comment by cdsmith** [comment]
Unfortunately, I'm getting increasingly hostile reports about this.  I don't know how to fix it.

**Comment by alphalambda** [comment]
Chris,

I'm sorry about it. I will contact his teacher, so that he can guide the student to the proper place.

I'm sorry I missed the initial report. Having LSU in the subject line of this message brought it to my attention.

Thank you,
Fernando

**Comment by cdsmith** [comment]
I could add a specific error message for this case, if you give me a list of module imports to look for, and the right website name and URL for where to send them.

**Comment by cdsmith** [comment]
i.e., something like:

    Line 1, Column 1: error:
        Lessons.Penguin looks like a module from the LSU Computational Thinking curriculum.
        Try using http://blackeyepeas.phys.lsu.edu instead.

**Comment by alphalambda** [comment]
So far, there are only a few internal modules: Standard, Standard.Debug, Lessons.Penguin and Lessons.Logic

The rest are in Extras, which is also in the public server.

The current LSU server is at: https://blackeyepeas.phys.lsu.edu/cwn/

However, that may change, so probably something generic would make more sense,
such as "Try using the link provided by your teacher"

**Comment by cdsmith** [comment]
Great.  Is "the LSU Computational Thinking curriculum" the right wording, or could you provide a more generally appropriate description?

**Comment by alphalambda** [comment]
I think that is a good description.
