### ISSUE TITLE
Circles don't appear well on Android

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#116]
On Android phones, drawing a circle seems to just draw a few arcs instead of the whole picture.  I suspect a scaling issue.

**Comment by cdsmith** [comment]
This is using Chrome on a Nexus 5X.  I have not verified on other phones or browsers.

**Comment by ChavXO** [comment]
Seems fine using Firefox, Chrome and Default Browser on Galaxy S7.

**Comment by cdsmith** [comment]
Seems to have gone away.
