### ISSUE TITLE
Confusing error when compiling codeworld-api project with codeworld-base

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1172]
**Program:** https://code.world/#Pahu_P2GR1yjvC1o9LxLthw

**Message:**

    program.hs:7:11-21: error:
        Ambiguous occurrence solidCircle
        It could refer to either solidCircle,
                                 defined in the standard library
                              or CodeWorld.solidCircle,
                                 defined in the standard library

**Comment by cdsmith** [comment]
Interesting.  This is someone using http://code.world who meant to use http://code.world/haskell

We should really hide the `codeworld-api` package for the former, which would fix this error message and have it refuse to import CodeWorld anyway.  But there are also other tell-tale signs, and it would also be great to direct the user specifically to http://code.world/haskell when we're confident that's what they wanted.
