### ISSUE TITLE
Error message when adding `&` outside of `drawingOf`

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1174]
**Program:** https://code.world/#PqmQBSeCRTU7X_EvBwjleyg

**Message:**

    program.hs:1:1: error: 
        • Couldn't match expected type Program with actual type Picture

**Comment by cdsmith** [comment]
This is not a horrible error message, but it's common enough that it is worth thinking about how to do better.  Students often write this:

    program = drawingOf(pic) & coordinaPlane

or

    program = drawingOf(pic) & drawingOf(coordinatePlane)

One possibility is to write the error message in the preprocessor by looking for uses of `&` on applications of `drawingOf` or `animationOf`, and giving a specialized message.
