### ISSUE TITLE
install.sh uses unrecognized v2-install option --symlink-bindir

### ISSUE THREAD

**Issue by blackgnezdo** [google/codeworld#1176]
**Description**

It appears install.sh is a bit too trusting to the environment and ends up using some wrong tools from the system despite having just installed the right tool.
```
./install.sh
...
===== RUNNING: ghcup install-cabal
Installing cabal-install-3.0.0.0 into "/home/gnezdo/codeworld/build/.ghcup/bin"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4071k  100 4071k    0     0  19.5M      0 --:--:-- --:--:-- --:--:-- 19.5M
Successfully installed cabal-install into
  /home/gnezdo/codeworld/build/.ghcup/bin

===== RUNNING: cabal update
Config file path source is default config file.
Config file /home/gnezdo/.cabal/config not found.
Writing default configuration to /home/gnezdo/.cabal/config
Downloading the latest package list from hackage.haskell.org
===== RUNNING: cabal v2-install happy-1.19.9 alex --symlink-bindir=/home/gnezdo/codeworld/build/bin
cabal: unrecognized 'v2-install' option
`--symlink-bindir=/home/gnezdo/codeworld/build/bin'
gnezdo@os-ws:~/codeworld$ which cabal
/usr/bin/cabal
gnezdo@os-ws:~/codeworld$ cabal --version
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library
gnezdo@os-ws:~/codeworld$ /home/gnezdo/codeworld/build/.ghcup/bin/cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library

gnezdo@os-ws:~/codeworld$ uname -a
Linux os-ws 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux
gnezdo@os-ws:~/codeworld$ cat /etc/issue
Debian GNU/Linux 9 \n \l

```

**Comment by blackgnezdo** [comment]
I'm mistaken, it is picking up the correct cabal binary. It's just the flag which is invalid.

**Comment by blackgnezdo** [comment]
If I understand the intent correctly, cabal-3 can do the same thing with
`--installdir=$BUILD/bin --install-method=symlink`

I can send a PR.

**Comment by cdsmith** [comment]
Okay, that sounds great!  I'll confess to knowing almost nothing about cabal v2 commands.  The option there was the result of my random fiddling to make GHCJS 8.6 work.  It may or may not even matter that it's a symlink in the first place.

**Comment by blackgnezdo** [comment]
One little concern that I have is we don't pin cabal repository state which is presumably responsible for suddenly starting to download a newer cabal than before. It might be something to consider to have a more reproducible setup going forward.

**Comment by cdsmith** [comment]
Yes, I understand.  CodeWorld has a lot of non-reproducible build going on.  For instance, I believe it's currently cloning GHCJS from github at head.  I'm definitely supportive of improving matters, but I haven't really sorted through everything.

**Comment by cdsmith** [comment]
Subsumed into #1181
