### ISSUE TITLE
Empty folders might prevent the files from loading

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1197]
@alphalambda  reports that there are issues loading student projects if they have an empty folder.  To resolve this, he has had to delete their empty folder by hand on the server.

I don't know if this is still an issue on the production server.

**Comment by cdsmith** [comment]
@alphalambda Any hints you can give me?  I'm tempted to assume this is fixed, since I know I fixed a bunch of weird cases around folder handling earlier this summer.

**Comment by alphalambda** [comment]
Sorry, I don't have a test case right now, as it did not happen to me, but to some students. Next time this happens, I will try to
reproduce the setting and can reopen the issue if necessary.
