### ISSUE TITLE
Confusing error location for missing close-parentheses

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1216]
**Program:** https://code.world/#Ps9xfBmQCLCP0bxpeOmBNsg

**Message:**

    program.hs:4:1: error:
        parse error (You may be missing an indent, or a parenthesis on the previous line)

**Comment by cdsmith** [comment]
Student is missing a parenthesis on the previous line.  The error says so.  However, I think we can do better at communicating this.

**Comment by cdsmith** [comment]
Note that in this case, the error was at the end of the file.  This needs a special case, since it shouldn't refer to the previous line.
