### ISSUE TITLE
Autoformat

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#122]
CodeWorld should offer something like hindent to reformat student code.

**Comment by cdsmith** [comment]
An update here: 0d8d554be065b2111999a7f7862013cc7070b193 added hindent to code.world/haskell  Currently, it uses hindent, but that's only because it was the first and easiest option I found.  I'm quite willing to consider other options.  @nomeata has suggested https://github.com/lspitzner/brittany -- but it requires GHC 8.0, and upgrading GHC to 8.0 is still a sizeable project.  It will require verifying all of the error message post-processing to prevent regressions due to wording of error messages.

Adding this for http://code.world is trickier, because we typically use non-standard formats.  In particular, all existing options will rewrite `f(x)` to `f (x)` with a space.  Postprocessing to remove the space isn't always an option when the formatting involves alignment.  I'd also want to add parentheses when missing around function arguments.  The amount of configurability necessary for this is probably beyond what anyone is going to write externally.

**Comment by nomeata** [comment]
I agree that upgrading to 8.0 is not something that should be done during the school year :-)

**Comment by cdsmith** [comment]
Now that CodeWorld has been updated to GHC 8.0, it would be possible to swap indenters.

**Comment by cdsmith** [comment]
Unfortunately, that's a no on brittany due to licensing (discussed at https://github.com/lspitzner/brittany/issues/164).  But hindent will do for now in the Haskell dialect.

The more interesting point is formatting for the CodeWorld dialect.  Still unresolved.

**Comment by cdsmith** [comment]
Now that I've added auto-indent for the CodeWorld dialect, it seems reasonable to request that any autoformat feature should be consistent with the autoindent implementation.  Then it remains only to decide where to insert line breaks.  This means I most likely want a client-side JavaScript implementation, so that I can reuse code from autoindent.

**Comment by cdsmith** [comment]
I've now implemented an autoformat for the CodeWorld dialect that just calls auto-indent on each line (with some subtleties to be sure everything remains at the same layout level).  It actually works really well.  It doesn't add line breaks or change spacing within lines, as that would need something like a full parse tree.  But that's okay with me.  I'll mark this as closed.
