### ISSUE TITLE
Reformatting loses source location and scrolling

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1221]
This issue applies only to https://code.world/haskell

Ideally, Ctrl-I (format, in Haskell mode) should leave you at the same place in the code, and just reformat around you.  Of course, "the same place" is non-trivial to interpret when the source changed.  But the current behavior is undeniably bad.

Better:
1. At least go back to the same line and column, so if there's only minor changes, you will be close.
2. Run some kind of diff algorithm such as https://github.com/kpdecker/jsdiff, and compute a new location by looking at changes that occur before the cursor.
3. Add support to Ormolu to do precise tracking using the SrcLoc values in the parsed input.  https://github.com/tweag/ormolu/issues/433 is an issue asking for this feature.

**Comment by cdsmith** [comment]
There's another question here of what to do with selections.  I think it would be okay if reformatting means you lose your selection, and only preserves the current primary cursor.

**Comment by cdsmith** [comment]
It doesn't look like Ormolu will get this feature, so we should do client-side diffing.

**Comment by Powell-v2** [comment]
I believe I need some guidance on this one. How exactly did you imagine computing a new location with `jsdiff` after reformatting?

**Comment by cdsmith** [comment]
I would start with Diff.diffLines.  Given the list of changes, you can match corresponding lines in the old and new code, as follows:

    let oldLine = 0, newLine = 0;
    console.log(oldLine + " -> " + newLine);
    Diff.diffLines(oldCode, newCode).forEach((change) => {
      const numLines = change.value.split(/\r\n|\r|\n/).length;
      if (change.added) {
        newLine += numLines;
      } else if (change.removed) {
        oldLine += numLines;
      } else {
        newLine += numLines;
        oldLine += numLines;
      }
      console.log(oldLine + " -> " + newLine);
    });

Using this correspondence, you should be able to convert scroll and cursor locations in the old code to similar locations in the new code, and restore them.
