### ISSUE TITLE
codeworld-api: blank-canvas bound on hackage is too tight

### ISSUE THREAD

**Issue by endgame** [google/codeworld#1222]
The most recent codeworld-api release on hackage (0.3.1) requires `blank-canvas == 0.6.*` but builds and seems to run fine with `blank-canvas-0.7`. The cabal file on master seems to be fixed already, but perhaps someone can ship a metadata revision to hackage?

**Comment by cdsmith** [comment]
Yeah, sorry about this!  I can do it tonight.

**Comment by cdsmith** [comment]
Done!  https://hackage.haskell.org/package/codeworld-api-0.4.0
