### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1229]
The new travis build succeeded a few times, but now it's failing with some kind of message about package corruption (files missing from the `text` package).

**Comment by cdsmith** [comment]
@peterbecich  Any ideas?

**Comment by cdsmith** [comment]
```
/home/travis/build/google/codeworld/codeworld-api/src/CodeWorld/CanvasM.hs:25:1: error:
    Could not find module ‘Data.Text’
    There are files missing in the ‘text-1.2.4.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
25 | import Data.Text (Text)
   | ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by cdsmith** [comment]
That problem went away, but now we've got a timeout running `travis_apt_get_update`.  This seems to be very flaky, and I don't know what to do about it.

**Comment by cdsmith** [comment]
Seems to be okay for now.

**Comment by peterbecich** [comment]
@cdsmith please delete all the Travis caches, I'm guessing here https://travis-ci.org/google/codeworld/caches

**Comment by cdsmith** [comment]
@peterbecich Done
