### ISSUE TITLE
Files "migrate" out of folders while editing them.

### ISSUE THREAD

**Issue by peterb12** [google/codeworld#1239]
**Shared Program**: Program was unshared.

**Description**
I saw this in code.world/haskell, but I'm positive I've seen the same phenomenon on 'plain' code.world.

-I created a subdirectory "Directory".
-I created a new empty file, saved it to a name "My Program", and began editing it.
-I save fairly regularly as a matter of habit.

At _some point_, and I don't know when, I logged in on another machine and noticed that it _seemed like_ my changes were gone.  Upon inspection, what I saw was that a new copy of "My Program" (with the 'missing' changes) was now living at the root level of code.world, and the file in the subfolder was an older revision.

In the past I've always assumed that I somehow created the file in the wrong place, but today I literally logged in to a single machine, created a file, and saw this phenomenon happen *while I was editing*.

**Comment by cdsmith** [comment]
I think this and #1219 are the final straw.  This world that was created by the folder migration isn't sustainable.  There are separate states for the selected file and the currently open file, and they are kept in sync with a bunch of ad hoc rules.

This weekend, I'll take a crack at rewriting this to keep one unified state for the open project, and a single adapter to keep the UI updated with respect to that state.
