### ISSUE TITLE
Nested data structures documentation

### ISSUE THREAD

**Issue by peterb12** [google/codeworld#1252]
While often nested product types are stylistically bad, it would be great if the documentation contained at least one example of how the syntax for this works (I've spent a morning trying to puzzle this out and still don't quite understand the parsing rules.)

**Comment by cdsmith** [comment]
I'm not sure that I quite understand what you mean.  Can you give an example?

**Comment by peterb12** [comment]
The answer seems to be "I was making a dumb mistake" because when I sat down to write an example of what I meant it worked fine.

I still think filling in some of the missing documentation would be good.  Is there a project for completing it / would you consider pull requests for it if I gave it a go?

Please consider this one to be ok to close.

**Comment by cdsmith** [comment]
Sure, documentation is at https://github.com/google/codeworld/tree/master/web/help, and pull requests are always welcome.

**Comment by cdsmith** [comment]
The starting point for the docs is `codeworld.shelf` for the educational mode and `haskell.shelf` for the haskell mode.  Those files allow you to add a section to the outline on the left.  To edit an existing section, you can just find the markdown file in there, and edit by hand.

The markdown is processed by markdeep (https://casual-effects.com/markdeep/), but with some local custom-built extensions.  Most notabily, a tip of type "collapsible" is collapsed but can be expanded, and a code sample with the style "clickable" can be clicked to load the code into the CodeWorld editor.

**Comment by cdsmith** [comment]
If you want to make significant structural changes, I'd encourage you to open an issue to discuss the plans first.

**Comment by cdsmith** [comment]
I'll leave this open, and let you close this when it's no longer helpful to you.

**Comment by cdsmith** [comment]
This seems to be obsolete.
