### ISSUE TITLE
Poor formatting in long error message

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1258]
**Program:** https://code.world/#PmwSAJwDIIAkufkejuKi8uA

**Message:**

    program.hs:115:28-53: error: 
        • Couldn't match expected type (Number, Number, Number, Number,
                                         Number, Number)
                      with actual type (Number, Number, Number, Number, Number, Number,
                                         Shiptype)

**Comment by cdsmith** [comment]
I'm not sure what the student meant, but the formatting is ugly here, so I'll call that the bug.

**Comment by cdsmith** [comment]
This actually isn't too bad.  I'm not going to spend time on this.
