### ISSUE TITLE
Styling should indicate an error for incorrect brackets

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1267]
**Program:** https://code.world/#P77JLTANARio8iMhJ3R1B5w

**Message:**

    program.hs:2:63: error: parse error on input )

**Comment by cdsmith** [comment]
Brackets out of order.

Rather than do anything with the error message, I should improve the styling for brackets that don't match.  That should be easy to do in the lexer.

**Comment by Powell-v2** [comment]
Should I make non-matching brackets more pronounced via CSS, or you had something else in mind? For example:

![image](https://user-images.githubusercontent.com/25308326/86249087-12f5f000-bbaf-11ea-8a9d-d878d63e056e.png)

**Comment by cdsmith** [comment]
Yes, that's the idea.  The harder part is detecting the mismatched brackets.  The lexer in codeworld-mode.js can be modified to flag closing brackets that don't match, but it can only propagate information forward, so it cannot flag open brackets.  That's probably better than nothing

**Comment by Powell-v2** [comment]
Is it really necessary to adjust the lexer? CodeMirror seems to be automatically marking matching and non-matching brackets. They get corresponding CSS classes: https://github.com/google/codeworld/blob/master/web/css/codeworld-cm.css#L151

**Comment by cdsmith** [comment]
Oh!  That makes it easier, then!

**Comment by cdsmith** [comment]
Oh wait.  I think that style only gets applied when the cursor is adjacent to the bracket.  So this issue is really about applying the style even when the cursor isn't located there.

Feel free to double-check, though.  I'm commenting from memory.

**Comment by Powell-v2** [comment]
> I think that style only gets applied when the cursor is adjacent to the bracket.

Yes, it's indeed so. I understand what's needed now, thanks for clarifying!
