### ISSUE TITLE
codeworld-api: update bound on test suite

### ISSUE THREAD

**Issue by endgame** [google/codeworld#1300]
**Description**

In `codeworld-api.cabal`, the library depends on `blank-canvas >= 0.6 && < 0.8`, but the test-suite depends on `blank-canvas >= 0.6 && < 0.7`. If the tests don't need a strictly older blank-canvas, can this be relaxed?

See:
https://github.com/google/codeworld/blob/8f1fbe6e83c69ca063f71a94008232aeafab49c7/codeworld-api/codeworld-api.cabal#L136

**Comment by cdsmith** [comment]
Yes, this was an oversight.  Will fix it today.

**Comment by endgame** [comment]
Did this get fixed?

**Comment by cdsmith** [comment]
Fixed a while ago in commit 1085433d681712c62a7d79cce85878a216e4fc55
