### ISSUE TITLE
Non-latin character corruption in program/folder names

### ISSUE THREAD

**Issue by blackgnezdo** [google/codeworld#1325]
**Description**

We saved a few programs Cyrillic characters in their names. A week later we observed that the names became corrupted and the programs can no longer be opened. I'll share the account name with you directly. I cannot build a reproducer now because I suspect there's another issue preventing me from logging in on chrome 81 (to be filed)

**Comment by blackgnezdo** [comment]
I tried to share the folder (its link is shown as https://code.world/#F1B2M2Y8AsgTpgAmY7PhCfg)

The "Share folder" dialog displays "Copy this link to share code in clones of ÑÐ´Ð°Ð²ÑÐ¸Ðº( and their adventures through the world of coding) with others!" 

The corrupted characters correspond to the Russian word "удавчик".

**Comment by blackgnezdo** [comment]
Looks like the problem is even more involved. I can save and read back the programs within short-term. The failed programs I reported originally were created a week ago. Is there some kind of maintenance job which can make changes that aren't visible on short-term scale?

**Comment by cdsmith** [comment]
There is definitely no maintenance job involved here.

**Comment by cdsmith** [comment]
The directory that share link points to is empty.

**Comment by blackgnezdo** [comment]
Cool! Thanks!

Do you anticipate a rollout some time soon?

**Comment by blackgnezdo** [comment]
It's gone worse now. Her account now displays "Loading" with a rolling wheel that never finishes. I see a failure in the JS console for this request https://code.world/listFolder:
```
A web handler threw an exception. Details:
data/codeworld/projects/112943662040574254927/D0zqc8JPcbvXvo-0wQpiLOQ/dir.info: openFile: does not exist (No such file or directory)
```

```
(index):1 A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
(index):1 A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
(index):1 A cookie associated with a cross-site resource at https://accounts.google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
codeworld.js:1156 POST https://code.world/listFolder 500 (Internal Server Error)
sendHttpAuth @ codeworld_shared.js:803
sendHttp @ codeworld_shared.js:32
discoverProjects @ codeworld_shared.js:911
signinCallback @ codeworld.js:1156
(anonymous) @ cb=gapi.loaded_0:311
b.port1.onmessage @ cb=gapi.loaded_0:183
```

**Comment by cdsmith** [comment]
This new problem should be fixed now.
