### ISSUE TITLE
Thoughts on exposing an Int or Integer type (or both)

### ISSUE THREAD

**Issue by bbarker** [google/codeworld#1327]
I can largely imagine why `Number` is used. But for indexing, it seems like it may be worth considering an integer type. The main motivation would be for indexing, but as a side effect, might be a more advanced topic for students to see that sometimes the same idea (that of a mathematical integer) can be represented in multiple ways by a computer language.

I'm not proposing to change existing API functionality, though perhaps some functions could be gradually added that use integers as well, where appropriate.

**Comment by cdsmith** [comment]
The big problem here: what's the type of `+`?  You can either add a whole new set of math operators for integers (which would be confusing and annoying), or you can start exporting type classes from CodeWorld's prelude.  The latter is a huge step back from all the error message work.

That's not to dismiss it out of hand.  If you could convince me that you can catch all "No instance" errors and rewrite them with meaningful messages that are specific to the types and operation in question (something like "Text values cannot be added.  If you meant to concatenate them, try <>" would be perfect, for example), then I could see supporting one or two built-in classes.  I actually planned to try that with Eq and Ord anyway -- along with some extra magic to auto-derive those classes for user-defined types, which you don't need here.  But it is not obvious how to achieve it.

**Comment by cdsmith** [comment]
Actually, my plan with `Eq` and `Ord` was to ensure that ALL types had those instances, and then use runtime errors if you try to (for example) compare two functions.  That obviously doesn't work for numeric operations, since they shouldn't be accepted for all input types.

**Comment by bbarker** [comment]
As a fun exercise, it is easy enough to construct Peano natural numbers in CodeWorld (I went over it with my 8 year old, and while I doubt he could reproduce it, he seemed to get the idea). Though in practice, I think they are obviously a bit unwieldy and still have the typeclass issue mentioned.

**Comment by cdsmith** [comment]
It seems unlikely this should happen, at least in the prelude.  Any objection to closing the issue?

**Comment by bbarker** [comment]
No, it sounds like the issue is more involved than I originally appreciated, so agreed it should be closed for now.
