### ISSUE TITLE
Add TriggerEvent to ReflexCodeWorld

### ISSUE THREAD

**Issue by endgame** [google/codeworld#1328]
I am working on a framework for simple two player games, as part of a general-purpose assignment skeleton. I want to provide hooks for a CodeWorld interface to the games. I had about 80% of a solution coded up, where values are passed to and from the game engine by `MVar`s, but I hit a wall when the lack of `TriggerEvent` prevented me from writing `watchMVar :: (TriggerEvent t m, PerformEvent t m) => MVar a -> m (Event t a)`.

(This is the same as my remark in #1053, but after sleeping on it, I decided that it deserved an open issue, and I don't have privs to reopen issues in this repo.)

**Comment by cdsmith** [comment]
I fully support this.  I don't know what I'll get to it on my own, but if you care to send a pull request, that would be great.

**Comment by cdsmith** [comment]
One promising approach, which offloads maintenance work versus a private implementation, is to use http://hackage.haskell.org/package/reflex-basic-host to implement the host.  This includes support for TriggerEvent

**Comment by endgame** [comment]
That would move the work from me to... me! I'll look into seeing whether it makes sense for codeworld-api to lean on reflex-basic-host.

Is there a document anywhere that describes how to build and test just codeworld-api for GHC and GHCjs?

**Comment by cdsmith** [comment]
You should be able to build just codeworld-api for GHC by just running `cabal v1-install ./codeworld-api`, assuming you have a GHC and cabal installed and in the path.  Same for GHCJS, but run `cabal v1-install --ghcjs ./codeworld-api`

The core reflex adapter is at https://github.com/google/codeworld/blob/master/codeworld-api/src/CodeWorld/Driver.hs#L1715, and does have separate event handling code for each environment.
