### ISSUE TITLE
Better sync code editor with the running program

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#133]
One source of occasional student confusion is that they have edited their code, but are still running an old version of the program in the sidebar.  There are a few possibilities for fixing this:
- Remember the CodeMirror revision that's running, and grey out the run window, or otherwise mark it as obsolete, when the current revision is different from the running one.
- Automatically rebuild and restart the program on a timer of some sort when there's a change.
- Something more ambitious?  Like hot-plugging changes into a running program without losing the state?

The latter two options are worth being cautious about.  I've built a prototype that continually rebuilds and reruns user code in the past, and it's vulnerable to the weakness that partially typed student code can sometimes compile and go into an infinite loop, which can make browsers suddenly lock up or become intolerably slow.  (e.g., imagine a user is typing `[1..10]`, but the rebuild timer hits when they've written `[1..]`)

At least the first option should be easy enough, though.  Just need a good UI for it...

**Comment by cdsmith** [comment]
@stefan-j 

This is particularly important with the new blocks UI, because we're updating the generated code, but not the running program, and it's all happening within the sidebar.  That leads to some extremely confusing situations where the code clearly doesn't match the output, and it's unclear that the running program is obsolete.

We should work out how to make this a bit more clear, at least in the blocks UI.

**Comment by stefan-j** [comment]
Yeah I also thought about this. We can use some color and a warning icon or
something similiar.

Another unfortunate example is that edit goes to the hash of the running
code, and also does not match the current code.

**Comment by cdsmith** [comment]
This seems pretty straightfoward.  We just want to place a new `div` on top of the runner window, set `pointer-events: none` as a CSS property, and make it transparent when the edit buffer is the same code as when Run was last pressed, or semi-opaque when it's not.
