### ISSUE TITLE
Thoughts on Vector/Matrix API

### ISSUE THREAD

**Issue by bbarker** [google/codeworld#1335]
I see that currently Vector is an alias for a tuple. I assume this is a hold over but haven't looked into it much.

Matrix algebra of course isn't for the target audience but I wonder if having a matrix type of some sort might be useful for drawing a "matrix of things" onto the Cartesian grid.

I'd be happy to explore some possibilities.

**Comment by cdsmith** [comment]
I'm not sure what you mean by a "holdover".  It's intentional that `Vector` is a type synonym for `(Number, Number)`.  Since CodeWorld is a two-dimensional graphics library, that's what a vector is.  It's a useful thing to keep in state types for physics simulations.

I'd have to see the use cases for a `Matrix` type.   In most cases where you want to represent two-dimensional arrangements, I think lists (or maybe lists of lists) work just fine.

**Comment by endgame** [comment]
In an assignment skeleton I recently built, I draw grids of differing size to the screen, and used the 3x3 matrices from the `linear` library to compute the inverse transformation of all the `scaled`/`translated` calls so I could resolve a pointer click into a grid coordinate.

**Comment by cdsmith** [comment]
@endgame To clarify, you're using Haskell mode, right?  That is, your students are using http://code.world/haskell?

**Comment by endgame** [comment]
@cdsmith negative. We are using only `codeworld-api`, and our labs provide a local Haskell development environment.

**Comment by cdsmith** [comment]
@endgame Okay, got it.  So you're not at all concerned with a matrix API being exported from `codeworld-base`, right?  I suspect when we're not talking about the educational dialect, the right thing to do is let people import their own linear algebra libraries just like you did.

**Comment by endgame** [comment]
Maybe. I can imagine people wanting to do what I did as an easy way to handle clicks, but I don't have a dog in this race.

**Comment by bbarker** [comment]
I was thinking about lists of list but I can imagine that getting a bit error-prone (maybe I'm wrong), due to needing each of the inner-lists needing to agree on length, but this is a difficult issue to tackle even in Haskell.

**Comment by bbarker** [comment]
And I had in mind vanilla codeworld (codeworld-base?) not code.world/haskell, in this case.

But it might well be that lists of lists is the way to go to keep things simple.

**Comment by cdsmith** [comment]
@bbarker That's my intuition.  Try to get away with one-dimensional lists, and just translate the pictures into a grid or something like that using list comprehensions.  If you do you need lists of lists, enforce the constraints on list lengths at runtime.

I know that's not "the Haskell way", but `codeworld-base` is not idiomatic Haskell anyway.  One guiding principle that has worked really wall is: keep the number of distinct types at an absolute minimum, and reuse types whenever it's at all sensible to do so.

**Comment by cdsmith** [comment]
It seems unlikely that more linear algebra primitives is the right choice for a library aimed at middle school students.  Any objection to closing this?

**Comment by bbarker** [comment]
No objections - again, I didn't really have linear algebra in mind broadly speaking (more like a multi-dimensional array type used for storing data, and in particular, 2d arrays, which are probably in common use even for people who have never heard of linear algebra).

**Comment by YellowOnion** [comment]
Maybe there's something I'm missing but I noticed in some of the Haskell examples that you're using some LA, and you can't actually add tuples so have to use "vectorSum"

If this project is actually targeted at high school students, wouldn't providing a proper LA library (like Kmett's linear package), that implements Num type class and other things make more sense to hide some of the details for them?
