### ISSUE TITLE
Continuous highlighting of syntax errors

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#134]
Today, students have to click Run to realize they have made an obvious syntax error.  Would be great to find them and place obvious annotations on the editor, so that they can be fixed immediately without a context switch and having to go back and re-understand the syntax.

**Comment by cdsmith** [comment]
There are basically two implementation options here:

1. Occasional round-trips to the server.
2. Build haskell-src-exts on the client with GHCJS.

The second is more appealing to me, but has the problem that error messages will differ from the compiled code.

**Comment by cdsmith** [comment]
I've neglected this, but it's still interesting.  Especially if we could invoke GHCJS with arguments that cause it to check the syntax and types but stop before generating code, then I think it could be efficient enough to be feasible.  Particularly if we do it with an adaptive frequency based on the current server load.

**Comment by cdsmith** [comment]
Note to self: the argument I wished for above should be `-fno-code`.  I haven't verified that it works for GHCJS, but I don't see why it wouldn't.

**Comment by cdsmith** [comment]
Some initial work: https://github.com/google/codeworld/commit/c57ebc85450fc418e99af23e822c7dc1ff394b45 and https://github.com/google/codeworld/commit/c9ae860c6c890e1b47ef8585517861a0d2956a06

There is now a `/errorCheck` endpoint on the server that tries to compile submitted code without generating code or linking.  This is suitable for a prototype of continuous error highlighting.  However, I probably want to look into some kind of a priority system before deploying publicly.  That is, instead of blocking indefinitely on the semaphore, `/errorCheck` should probably try to grab a low-priority semaphore, which will be aborted if a true build request comes in.  I could imagine a scheme where client polling frequency is adjusted, too, based on measured server load; so if the server is very busy, then clients attempt builds less often.

There are outstanding UI challenges, as well.  The error display window is currently synced to the running program, which is different from the current contents of the editor buffer.  This could get confusing if error highlighting refers to a newer version of the code than the errors that are clearly displayed on the screen!  On the other hand, I wouldn't want to clear the old errors too eagerly, since a student may be working down the list and fixing them.  Definitely requires some thought.

**Comment by nixorn** [comment]
Going to use [CodeMirror linter](https://codemirror.net/demo/lint.html) for this.
