### ISSUE TITLE
Expose the generic-lens package to codeworld Haskell projects

### ISSUE THREAD

**Issue by enobayram** [google/codeworld#1347]
First of all, thank you **very much** for code.world!

I've noticed that in codeworld Haskell, `LANGUAGE TemplateHaskell` is, understandably, not allowed since that would help malicious users do nasty stuff. However, as noted in #69, one very important use of `TemplateHaskell` is deriving lenses for records. And that's **especially** true for codeworld, given how important pure state transformations are in codeworld's model and how well lens plays with `MonadState`.

So, I'd like to suggest exposing the `generic-lens` package as an alternative means to scratch the same itch without requiring  `TemplateHaskell`. (In fact, that's the way I prefer even when `TemplateHaskell` is available). So the users can resort to:

```
{-# LANGUAGE DeriveGeneric, OverloadedLabels #-}

import Control.Lens
import Data.Generics.Labels
import GHC.Generics

data MyRecord = MR { myField :: Int } deriving Generic

main = print $ MR 42 ^. #myField
```

**Comment by cdsmith** [comment]
Sounds like a great idea.  I can definitely do this.

**Comment by cdsmith** [comment]
https://code.world/haskell#P653zkG8w1eybgAG_tGomfw

**Comment by enobayram** [comment]
Awesome, thanks a lot!
