### ISSUE TITLE
Auto-complete should include documentation

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#135]
The autocomplete window include type annotations, but it should include documentation as well.  Possibly the one-line summary for all entries, and possibly a more complete doc window for the currently selected auto-complete entry.

**Comment by nixorn** [comment]
Looks this is closely to #10 . Can I do this as well?

**Comment by cdsmith** [comment]
Yeah, that sounds great.  I will finish reviewing your last pull request tomorrow; I just need to merge it when I can test the server and check that everything is working; and I have a flight now.

**Comment by cdsmith** [comment]
@nixorn I don't find it easy to comment on things like this without seeing more realistic UI mocks.  My concern with the hover version is that it might make it harder to browse the list if the docs obscure other elements.  On the other hand, the focus version suffers from the fault that it's impossible to merely focus an item from the list using the mouse.  If list elements became focused on mouseover, then I think I'd favor the inline doc that expands under the focused row (or alternatively, in a second popup to the right of the list).  But in the end, I think it comes down to just trying it out to see what feels right.
