### ISSUE TITLE
Random numbers parameter to activityOf lacking documentation

### ISSUE THREAD

**Issue by blackgnezdo** [google/codeworld#1352]
**Description**

The source of random numbers is documented pretty sparsely. One important point is the range of numbers (empirically [0..1]) should be documented.

**Comment by cdsmith** [comment]
I've added a brief comment in the API documentation, and updated unit 9 of the guide to use the current API (`activityOf` instead of `simulationOf`).  More complete documentation would always be better, but I think that's enough that it's not worth keeping a specific issue open.
