### ISSUE TITLE
It's not clear how to select the root folder

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1371]
If one selects a subfolder in the project browser UI, it seems to remain pretty stubbornly selected from then on.  Even refreshing the page doesn't change the selection (!!!).  There's no obvious way to select the root folder again, so that new projects will be placed into the root.

One way to do it (if you have projects in your root folder) is click a project, not a folder, inside of root, and then click New.  But if you don't have any projects in your root folder, I think it may actually be impossible to select the root folder without dragging a project there first.

**Comment by cdsmith** [comment]
Actually, if you select a project in a subfolder and refresh the page, it also clears the selection.  It's only when a folder itself is selected and the page is refreshed that the selection sticks.  That makes this behavior even more confusing.

**Comment by cdsmith** [comment]
Something even weirder is going on.  If I select a project inside the folder, and then refresh the page, it loads with the folder not selected, but the icon showing an open folder (as if it's expanded).  So it's in some sort of half-selected state?

**Comment by cdsmith** [comment]
@Powell-v2 This might be related to your recent changes.  What do you think?

**Comment by Powell-v2** [comment]
This is probably related to the tree state stored in browser's local storage by the jqTree plugin. Selection sticks around between page reloads, but for some reason the selected file isn't revealed in the directory. I'll make sure the selection is properly exposed.

The root path could be implicitly selected every time a folder is closed. Will that be a suitable behavior?

**Comment by cdsmith** [comment]
My biggest concern right now is the last comment.  It seems to get the tree into some kind of half-selected state, where there's an open-folder icon even though the folder is neither selected nor expanded.  That makes me worried.

Once that's resolved, I think I can live with any reasonable behavior.

**Comment by cdsmith** [comment]
It looks like this is just unintuitive behavior around lazy-loading of folder contents.  So are #977 and #990.  Lazy loading is supposed to be a built-in feature of jqtree, so it seems like it would work well out of the box.

If not, then perhaps this lazy loading was a bad idea to begin with.  It's not as if there's likely to be a huge amount of data.  I could add a `listFolders` endpoint on the server that just delivers the entire project tree.

**Comment by cdsmith** [comment]
https://mbraak.github.io/jqTree/examples/05_load_on_demand/ is a jqtree demo for lazy loading, and it works in ways CodeWorld doesn't.  It's not a great experience on reload, sure, but at least it doesn't get into this weird state with empty-looking folders.

I suspect this was just done wrong.

**Comment by Powell-v2** [comment]
> jqtree demo for lazy loading

I attempted to recreate this behavior, but ran into an ID mismatch problem. In a nutshell, we cannot reliably recreate tree state carried over from the previous session as folders should be loaded in exactly the same order they were opened initially.

The simplest fix for the problem would be to initialize directory tree from a clean slate every time, ignoring any previous state. I have a commit ready in a branch, along with a quick fix for the root path selection - should I send it over?

**Comment by cdsmith** [comment]
Yeah, I guess that sounds good.  I didn't even know the state was persistent, and it's definitely not working now, so not doing it is an improvement.

**Comment by Powell-v2** [comment]
Okay, here it is => #1388

**Comment by Powell-v2** [comment]
Since this issue is closed, I assume that you are happy with proposed quick fixes for the time being and I should focus on refactoring?

**Comment by cdsmith** [comment]
Yes, I agree with that.  This isn't a top priority any longer.
