### ISSUE TITLE
Improve formatting and linting

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1375]
@Powell-v2 is working on this.  The plan:

1. Use Prettier to replace js-beautify.
2. Change the ESLint configuration to 2-space indents rather than 4.
3. Modify `format.sh` to use `npx` rather than installing new packages each time.
4. Set up a git precommit hook to run `format.sh` on every commit, on just the modified files.

**Comment by Powell-v2** [comment]
Link to the PR => #1378
