### ISSUE TITLE
Can't run programs from the guide

### ISSUE THREAD

**Issue by eleni-xar** [google/codeworld#1381]
**Shared Program**: https://code.world/#Pxxxxxxxxxxx (if applicable)

**Description**

(If you don't know what's causing the problem, please include the
browser and operating system you're using in the description.)

I am using chrome on Ubuntu. I want to run programs that are available in the guide. I open the guide on a different tab, I copy paste the following program on the coding area

```
program = drawingOf(design)
design  = rotated(rectangle(4, 0.2), 1 * 180 / 5)
        & rotated(rectangle(4, 0.2), 2 * 180 / 5)
        & rotated(rectangle(4, 0.2), 3 * 180 / 5)
        & rotated(rectangle(4, 0.2), 4 * 180 / 5)
        & rotated(rectangle(4, 0.2), 5 * 180 / 5)
```

 I click the run button. I get the message "Compiling. Your code is compiling. Please wait", the area where the result would appear opens, but it is completely blank, there are no rectangles there, or nothing else for that matter.

**Comment by cdsmith** [comment]
Here are two things to try:

1. Clear your browser cache.  See https://support.google.com/accounts/answer/32050 for instructions.
2. If that doesn't work, try again and press Ctrl-Shift-J, then see if there are errors in the "Console" tab?  If so, please copy and paste them here.

**Comment by cdsmith** [comment]
@eleni-xar Any update on this?  I'm still unable to reproduce the problem so far.

**Comment by eleni-xar** [comment]
Hi. I didn't really have much time to play with codeWorld since I posted this. There seems to be no problem now. I am not doing anything differently. It could be that the cache was cleared when my battery died and I had to start all over again. Anyway, thanks for your help.

**Comment by cdsmith** [comment]
Okay, great.  Feel free to reopen if you see this again.
