### ISSUE TITLE
Can't create a new session in groupActivityOf

### ISSUE THREAD

**Issue by enobayram** [google/codeworld#1382]
**Shared Program**: https://code.world/haskell#PIkgCPK_drjWxTrRK_KFh5g

**Description**

Clicking the "New" button in the "Main Menu" of a `groupActivityOf` application freezes the application view.

Operating System: Linux Mint 18 Cinnamon 64 Bit
Browser: Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by cdsmith** [comment]
I see the same.  Exception is:

```
runBaseJS?version=5558f1b27f6e7ebb0b6d9c776b0c7f2fb94326360631e85b0b3498020085c591:21314 WebSocket connection to 'wss://code.world/gameserver' failed: WebSocket is closed before the connection is established.
h$closeWebSocket @ runBaseJS?version=5558f1b27f6e7ebb0b6d9c776b0c7f2fb94326360631e85b0b3498020085c591:21314
h$$a3X @ runBaseJS?version=5558f1b27f6e7ebb0b6d9c776b0c7f2fb94326360631e85b0b3498020085c591:98015
h$runThreadSlice @ runBaseJS?version=5558f1b27f6e7ebb0b6d9c776b0c7f2fb94326360631e85b0b3498020085c591:6553
h$runSyncAction @ runBaseJS?version=5558f1b27f6e7ebb0b6d9c776b0c7f2fb94326360631e85b0b3498020085c591:6679
h$runSync @ runBaseJS?version=5558f1b27f6e7ebb0b6d9c776b0c7f2fb94326360631e85b0b3498020085c591:6650
c @ runBaseJS?version=5558f1b27f6e7ebb0b6d9c776b0c7f2fb94326360631e85b0b3498020085c591:4064
```

**Comment by cdsmith** [comment]
I don't see errors on the server side, though.

**Comment by cdsmith** [comment]
Definitely happening for all games.  (I expected this, since the reproduction is trivial.)

**Comment by cdsmith** [comment]
This is not transient, as a server reboot still doesn't fix it.  There have also not been any recent changes in related code.  The only thing I can guess is that the problem was introduced either when updating the cabal version, or adding dependencies, by forced cabal to choose a different version of some underlying library.

I can think of nothing to do except clone the server and try various old versions until I find out that works, and bisect to isolate the problem.  That's a lot of work.

**Comment by cdsmith** [comment]
I still had a system snapshot around from June 10, but it was already failing then.

**Comment by enobayram** [comment]
Thanks for the quick response @cdsmith! Sorry for just dumping the reproduction case without much elbow grease. I was hoping it'd be trivial to fix. I've been meaning to familiarize myself with the Code World infrastructure for a while now, so I'll try to take a stab at the bug on Saturday, but I wouldn't hold my breath, because don't have much hands on experience with ghcjs.

**Comment by cdsmith** [comment]
No, don't apologize.  Thanks for the report.  I wish it had been trivial, as well, but I've been stymied so far.

**Comment by cdsmith** [comment]
There are three places this problem might happen:

1. On the client
2. In nginx
3. On the server.

I can rule out (3).  I modified codeworld-game-bot to be able to start new games, and it still works:

```
cdsmith@codeworld-copy:~/codeworld$ build/bin/codeworld-game-bot --debug --hostname code.world --port 9160 -c 2
ThreadId 8 → NewGame 2 "BOT"
ThreadId 8 ← JoinedAs 0 "UDQV"
ThreadId 8 ← PlayersWaiting 1 2
ThreadId 10 → JoinGame "UDQV" "BOT"
ThreadId 8 ← Started
ThreadId 10 ← JoinedAs 1 "UDQV"
ThreadId 10 ← Started
^C
```

However, it doesn't work on port 443:

```
cdsmith@codeworld-copy:~/codeworld$ build/bin/codeworld-game-bot --debug --hostname code.world --port 443 -c 2
codeworld-game-bot: MalformedResponse (ResponseHead {responseCode = 400, responseMessage = "Bad Request", responseHeaders = [("Server","nginx/1.10.3"),("Date","Fri, 19 Jun 2020 13:49:36 GMT"),("Content-Type","text/html"),("Content-Length","173"),("Connection","close")]}) "Wrong response status or message."
```

That suggests that this might be an nginx config problem.  Weird, though.  I haven't changed nginx for a long time.

**Comment by cdsmith** [comment]
I have confirmed that the server is working as expected through nginx.  The earlier problem was that the gameserver bot didn't know how to speak SSL.

```
cdsmith@codeworld-copy:~/codeworld$ build/bin/codeworld-game-bot --secure --debug --hostname code.world --port 443 -c 2
ThreadId 8 → NewGame 2 "BOT"
ThreadId 8 ← JoinedAs 0 "JLUV"
ThreadId 8 ← PlayersWaiting 1 2
ThreadId 10 → JoinGame "JLUV" "BOT"
ThreadId 8 ← Started
ThreadId 10 ← JoinedAs 1 "JLUV"
ThreadId 10 ← Started
```

**Comment by cdsmith** [comment]
So the remaining possibility is (3): there is a problem in the client code.  Unfortunately, the game API doesn't work with blank-canvas, so this necessarily requires building everything with GHCJS to bisect the faulty change.

**Comment by cdsmith** [comment]
One more quick note: I can reproduce the problem with http://code.world:8080/haskell#PIkgCPK_drjWxTrRK_KFh5g (which connects to websockets on port 9160).  So it should be possible to do the bisection without SSL, at least.  That's good news.

**Comment by cdsmith** [comment]
Bisection reveals that f5799b343aa217b31d5fb68b99182ee874714927 the bad commit.

**Comment by cdsmith** [comment]
The actual code change here is very safe.  The problem, then, almost certainly arises from an incompatibility between ghcjs-dom versions 0.8 and 0.9.

**Comment by cdsmith** [comment]
Very interesting... this works just fine at the same commit when building codeworld-api against ghcjs-dom 0.9.2.0, but fails when building codeworld-api against ghcjs-0.9.4.0, which is the next version.  So something changed between those versions that broke websockets (at least as codeworld-api uses them for multiplayer games)

**Comment by enobayram** [comment]
Wow, this turned into quite a detective story. Just wanted to say thanks for all the effort.

**Comment by cdsmith** [comment]
Hey, no problem.  I definitely want this to continue working.  The good news is that it was only broken for about 10 days.  Not great, but I don't often use this API, and I was afraid it may have been much worse.
