### ISSUE TITLE
Apply patches from https://github.com/ghcjs/ghcjs/pull/788 locally

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1387]
There's a known bug in GHCJS dedup, fixed at https://github.com/ghcjs/ghcjs/pull/788/files.  Unfortunately, the fix is taking a long time to merge into GHCJS, so I believe I'll need to patch it locally.

Thanks @3noch for the heads-up.

**Comment by 3noch** [comment]
It took us weeks do find and fix that bug so I want everyone to benefit 😄
