### ISSUE TITLE
Line breaks not respected by output window

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1395]
**Shared Program**: https://code.world/haskell#PtI3nHp_9CxppdJJwQXtwcw

**Description**

This shows how appending to the console output window doesn't respect line breaks.  Only line breaks inside of an output chunk are respected (as in the first example, where the full output is concatenated in stdout's buffer and then sent at once).  If the buffer is flushed so that output is sent in multiple chunks, then the line breaks are lost.

@Powell-v2 Almost certainly caused by your change to the output code.

**Comment by Powell-v2** [comment]
Yes, my bad. A formatted message should be appended instead of an array containing lines without line breaks.
