### ISSUE TITLE
Verbs used as titles in funblocks

### ISSUE THREAD

**Issue by alphalambda** [google/codeworld#140]
I noticed that the new blocks interface does not follow the same conventions as the text-based interface, because it uses verbs for Pictures/Translate, Pictures/Combine and Pictures/Change-Color instead of
Translated, Combined or Colored. It also has an If/Do block instead of an If/Value function.
I know the block interface is very preliminary, but I wanted to open an issue just for the record.

**Comment by cdsmith** [comment]
@stefan-j

**Comment by stefan-j** [comment]
Hi,

Thanks for reporting.

As you may know, I'm doing the project as part of the Haskell Summer of Code program.

The interface is very preliminary and thought was not yet given to consistency. 

I'll clean up the interface a bit, add a few blocks and then change the current block names to be more consistent, soon, for a cleaner preliminary version that can be played with.

**Comment by cdsmith** [comment]
This appears to be fixed as of Stefan's latest pull request.
