### ISSUE TITLE
Local authentication fails

### ISSUE THREAD

**Issue by jbash** [google/codeworld#1406]
**Description**

On a local instance installed from the master branch at commit a720446c7df0a52315669f2cbb0f4fa2103edaab , local authentication does not work.

1. Clicking the "Sign In" button produces no user-visible response. In the debugger, you get an exception at auth.js line 278, with the error "ReferenceError: Alert is not defined".

This first error appears to be fixed by adding the following line at the top of web/js/utils/auth.js:

    import * as Alert from './alert.js';

2. After the Alert problem is fixed, it's possible to get the login dialog, but actually submitting a username and password results in a never-ending "spinner". The server logs a POST on "/signIn", and the browser logs:
```
    Possible Unhandled Promise Rejection: ReferenceError: Html is not defined
        onPreConfirmSignIn http://vps2.kdjf.net:8080/js/utils/auth.js:223
        polyfill 7.1.0/dist/promise.min.js:1
    promise.min.js:1:2831
```

I didn't try to debug it beyond that point.

**Comment by cdsmith** [comment]
@Powell-v2 Is it possible your modules change broke this?  Can you take a look?

**Comment by cdsmith** [comment]
Oh, actually this looks like it may be an easy fix.  You probably need:

    import * as Html from './html.js';

in addition to the `Alert` line.

**Comment by Powell-v2** [comment]
Yes, that's right - imports for `Alert` and `Html` modules are missing in `auth.js`. I've pushed a fix.

**Comment by cdsmith** [comment]
Thanks.  This is merged.  @jbash, please let me know if you have more problems.

**Comment by jbash** [comment]
I merged the fix and can confirm it works for me.

As for other problems, don't worry; I'm very good at complaining. :-)

Thanks very much.
