### ISSUE TITLE
Chrome warning about misbehaving codeExplorer.js script

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1426]
I'm seeing this in the JavaScript console:

```
Throttling navigation to prevent the browser from hanging. See https://crbug.com/882238. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection
go @ codeExplorer.js:62
go @ codeExplorer.js:79
go @ codeExplorer.js:79
go @ codeExplorer.js:79
buildNestedList @ codeExplorer.js:89
selectNode @ codeExplorer.js:212
(anonymous) @ codeExplorer.js:241
postMessage (async)
(anonymous) @ VM122 debugmode.js:93
```

I'm not sure what it means, but it's certainly not a good thing,  @Powell-v2

**Comment by cdsmith** [comment]
I can no longer reproduce this after other fixes.  Since there was definitely wonky stuff going on, I'll close this and assume it was a symptom of other bugs.

**Comment by Powell-v2** [comment]
Looks like an infinite loop. I didn't touch the logic in this part of the file, only renamed few things. Probably happens with extra long lists. Haven't seen it before, though.
