### ISSUE TITLE
CodeExplorer.toggle is the wrong abstraction

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1430]
#1428 was caused in part by a poor choice of abstraction in `codeExplorer.js`.  In general, we always know whether we intend to be enabling or disabling debug mode, so there should be separate API calls to enable or disable, rather than one call to toggle.  These should be idempotent: that is, if debug mode is already disabled, then disabling it should do nothing, rather than turn it back on.

**Comment by cdsmith** [comment]
@Powell-v2

**Comment by Powell-v2** [comment]
One thing that I would expect as a student is that the debugger maintains selection of nodes when toggled on and off. Right now the state is always reset.
