### ISSUE TITLE
Infinite compilation for any program

### ISSUE THREAD

**Issue by Starlawn** [google/codeworld#1433]
Hello, I have a problem, which is an infinite compilation for any program, even for those that were written before and were working just fine. Maybe it is somehow connected to my account, because when I am logged out the same code compiles and works just fine.

System:
Linux mint 19. Mozilla Firefox(latest)

**Comment by cdsmith** [comment]
I cannot reproduce this, nor find anything in logs.  When it happens, can you check the JavaScript console in Firefox and see if there's anything there?

**Comment by Starlawn** [comment]
For some reason it just started working now, so I will close it and reopen if I will be able to reproduce this issue.
