### ISSUE TITLE
Chapter 1 & Homework 1 Exercise 2 all prompts Variable not in scope error

### ISSUE THREAD

**Issue by AmagiDDmxh** [google/codeworld#1435]
**Shared Program**: https://code.world/haskell#PdcNncD_4FsdW5wJ_6UD10Q (if applicable)

**Description**
**Variable not in scope: path :: [(Integer, Integer)] -> Picture**
Im using chrome Version 85.0.4183.83 (Official Build) (64-bit), macOS 10.15.5

(If you don't know what's causing the problem, please include the
browser and operating system you're using in the description.)

**Comment by AmagiDDmxh** [comment]
I fix this by change the name of `path` to `curve`, perhaps this are documentation and template issues

**Comment by cdsmith** [comment]
I think what you're looking for is `polyline`, actually.  A long time ago, it used to be called `path`.  It was renamed for pedagogical reasons, the old name was deprecated for several years, and finally removed.

Just to be clear, the exercises you're working from aren't part of CodeWorld, right?  I don't think there are any CodeWorld exercises that refer to it by its old name, but I can't do anything about bitrot in external resources.  I know a lot of @nomeata's CIS194 class, for example, no longer works.  That's unfortunate, but the alternative would be to get forever stuck in the mistakes of the past.

**Comment by AmagiDDmxh** [comment]
So glad for helping, seeing this mistake is a quite good reason for nostalgia LOL:>. I wasn't think about CodeWorld and CIS194 were not integrated part together, and searching guide

**Comment by nomeata** [comment]
Yes, unfortunately I can’t update the CIS194 pages anymore.

Maybe I should host them privately in maintenance mode…

**Comment by nomeata** [comment]
Allright, updated the CodeWorld part of the course and am hosting it now on https://github.com/nomeata/haskell-via-sokoban
