### ISSUE TITLE
Poor error message due to accidental currying in types

### ISSUE THREAD

**Issue by bbarker** [google/codeworld#1446]
**Shared Program**: https://code.world/#PQF2o7pi7IxvOXFC_1TRvPA (if applicable)

**Description**

We receive this error message:

```

Line 31, Column 9-21: error: Not helpful?
    • Couldn't match expected type Text
                  with actual type (Text, Number)
Line 31, Column 25-35: error: Not helpful?
    • Couldn't match type Picture with Number -> Picture
      Expected type: Number -> Number -> Picture
        Actual type: Number -> Picture
```

For the following code snippet:

```haskell
spinText :: Text -> Number -> (Number -> Picture)
spinText(theText, aS) = spunTextPic
 where
    theTextPic = lettering(theText)
    textPicMoved = translated(theTextPic,3,5)
    spunTextPic :: Number -> Picture
    spunTextPic(t) = rotated(textPicMoved, aS * t)
```

Here's a little Haskell program that I think demonstrates the same principles, but with different types, and it compiles:

```haskell
import Data.Char (chr)

main = putStrLn $ show $ [foo 1, foo 3]
  where
    foo = spinText 'a' 5

spinText :: Char -> Int -> (Int -> String)
spinText theChar aS = newChar
  where
    newChar :: Int ->  String
    newChar i = [chr (i+aS), theChar]
```

**Comment by cdsmith** [comment]
The type signature for `spinText` was using currying.  Corrected code here (see line 30).  https://code.world/#PwQN1Tq4f8LR2jEoMcRAIwg

**Comment by cdsmith** [comment]
One thing we could do is require explicit parentheses for function-typed results in type signatures in CodeWorld mode.  This parallels how we require explicit parentheses for arguments; it ensures that if you return a function from a function, you really mark it as such.  Would create room for a more helpful error message.

**Comment by bbarker** [comment]
Wow, I can't believe I missed that. It seems very difficult for me to stop thinking in Haskell's curried function-call syntax when using CodeWorld. Thank you! 

And as the target audience aren't Haskell programmers, I can totally understand how this isn't a typical issue.

**Comment by cdsmith** [comment]
Looks like there's a better error message for this now

```

Line 30, Column 21-49: error: The range of this function is another function type.
	If this is what you intended, add parentheses around the range.
```
