### ISSUE TITLE
Inspect appears to do nothing

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#1452]
The Inspect button seems to have stopped doing anything.

@Powell-v2 Do you know what's going on here?

**Comment by cdsmith** [comment]
This was definitely working when I filed #1425 on September 4, right after I merged the change to move the inspect area.  So it's something since then, meaning that I probably broke it.

**Comment by Powell-v2** [comment]
That was my bad. By not importing anything from the `codeExplorer` module I cut off the reception of incoming messages.
