### ISSUE TITLE
Restyle block title text

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#146]
The title text on a block looks identical to the parameter labels, and this is a usability issue.  We could:

- Make the parameter labels smaller
- Make the title bold
- Use different colors
- something else in this spirit?

**Comment by cdsmith** [comment]
@stefan-j says: "The text on the blocks can be changed with CSS. When creating blocks, text added to a block is done through a Text field, and it is not possible to distinguish between block titles and input titles, as block titles are just a dummy input with a text field. This can be seen on the BlockFactory. It might be possible to having a hackish solution to bold the first encountered blocklyText class on each block. I'll look into a better way as well."

**Comment by stefan-j** [comment]
I'm adding support for an additional field with a different CSS class. Currently I'm bolding the title. This looks rather plain, but at least the CSS can now be changed easily for the block titles. This will be included soon with the new pull request.
