### ISSUE TITLE
Fail to install codeworld-compiler-0.1.0.0

### ISSUE THREAD

**Issue by Carina-Cai** [google/codeworld#1474]
I am getting the following error when running `./install.sh`

<img width="623" alt="Screen Shot 2020-12-17 at 2 52 38 am" src="https://user-images.githubusercontent.com/76047281/102375555-c431fa80-4016-11eb-8eea-8532fe182cb3.png">

Could anybody help me with the possible causes?

Thank you!

**Comment by cdsmith** [comment]
Can you provide the full output.  The reason for the failure should be in the output above the screen shot you posted.

**Comment by Carina-Cai** [comment]
Here is the full output:

[ 5 of 10] Compiling CodeWorld.Compile.Requirements.LegacyLanguage ( src/CodeWorld/Compile/Requirements/LegacyLanguage.hs, dist/build/CodeWorld/Compile/Requirements/LegacyLanguage.o )

src/CodeWorld/Compile/Requirements/LegacyLanguage.hs:147:50: error:
    • Couldn't match expected type ‘State String Void’
                  with actual type ‘[ParseError String e0] -> State String e0’
    • Probable cause: ‘initialState’ is applied to too few arguments
      In the second argument of ‘runParser'’, namely ‘initialState’
      In the second argument of ‘($)’, namely
        ‘runParser' legacyRequirementParser initialState’
      In the second argument of ‘($)’, namely
        ‘snd $ runParser' legacyRequirementParser initialState’
    |
147 |         snd $ runParser' legacyRequirementParser initialState
    |                                                  ^^^^^^^^^^^^
Failed to install codeworld-compiler-0.1.0.0
Warning: could not create a symlink in /home/tong/codeworld-rosy/build/bin for
hindent because the file exists there already but is not managed by cabal. You
can create a symlink for this executable manually if you wish. The executable
file has been installed at /home/tong/codeworld-rosy/build/bin/hindent
cabal: Error: some packages failed to install:
codeworld-compiler-0.1.0.0-3vlChHs5ETVE6YQm3CcQa8 failed during the building
phase. The exception was:
ExitFailure 1
codeworld-server-0.1-4WGqjq9QWokLZR6xDJz8LO depends on codeworld-server-0.1
which failed to install.


========== Aborting: Command failed. ==========
DIRECTORY: .
COMMAND  : cabal_install ./codeworld-server ./codeworld-error-sanitizer ./codeworld-compiler ./codeworld-game-api ./codeworld-prediction ./codeworld-api ./codeworld-game-server ./codeworld-account ./codeworld-auth
EXIT CODE: 1
===============================================

**Comment by cdsmith** [comment]
Thanks for the report!  This is a result of a breaking change in megaparsec, which added a new field to its State constructor in version  8.0.

**Comment by cdsmith** [comment]
There are three possible fixes:

1. Update the code to a new version of megaparsec
2. Add a version bound constraint to force old megaparsec
3. Just delete the legacy requirements syntax support.

I'm leaning toward option 3.  There's no one using this feature that I'm aware of.  But I can do some grepping through logs to see if it's been used first.

**Comment by cdsmith** [comment]
@Carina-Cai  When I went to add the version bound, I realized it was already added in December of 2019.  Any chance you removed this version bound... or else are building with code from more than a year ago?

**Comment by Carina-Cai** [comment]
@cdsmith I edited the files as suggested by #1180, and I am still a bit confused by the way to delete the legacy requirements syntax support.
Thank you so much for helping!

**Comment by Carina-Cai** [comment]
@cdsmith I tried the third suggestion by deleting the command `import CodeWorld.Compile.Requirements.LegacyLanguage` from codeworld-compile/src/CodeWorld/Compile/Requirements.hs. However, it is used in Language.hs as shown in the screenshots.

<img width="797" alt="Screen Shot 2020-12-22 at 5 13 48 pm" src="https://user-images.githubusercontent.com/76047281/102856044-eba32000-4479-11eb-8d27-af77f8b29dfc.png">

<img width="821" alt="Screen Shot 2020-12-22 at 5 13 31 pm" src="https://user-images.githubusercontent.com/76047281/102855926-b0a0ec80-4479-11eb-989a-112f6ccc7772.png">

Does this mean I can only go for the first two options?

**Comment by cdsmith** [comment]
I don't think you answered the question earlier: are you building with the most recent code?  It looks like there's already a version bound on megaparsec (added a year ago) that should fix this.

To remove legacy language support, you would want to change the code above to:

```
parseRequirement :: Int -> Int -> Text -> Either String Requirement
parseRequirement ln col txt =
    either (Left . prettyPrintYamlParseException ln col) Right $
        Yaml.decodeEither' (T.encodeUtf8 txt)
```

In other words, just delete the case for `isLegacyFormat` and turn the `otherwise` case into the entire definition.

**Comment by Carina-Cai** [comment]
Yes I am building with the most recent code.
After removing the legacy language support the installation is successful. However I ran into this error

===== RUNNING: codeworld-server -p 80 --no-access-log --verbose
Authentication method: Google
Listening on http://0.0.0.0:9160
codeworld-server: Network.Socket.bind: permission denied (Permission denied)

========== Aborting: Command failed. ==========
DIRECTORY: .
COMMAND  : codeworld-server -p 80 --no-access-log --verbose
EXIT CODE: 1
===============================================
when I tried to run the code. What could be the possible cause? I've copied the OAuth client Id into `web/clientId.txt`

**Comment by cdsmith** [comment]
This is a standard UNIX thing.  To bind to port 80, you would need to be root.  To run as non-root, you need to bind to a port number greater than 1024.  (You must have modified this, because the checked in code binds to 8080.)

Rather than running codeworld-server as root, I strongly recommend that you set up a proxy like nginx to forward requests from port 80 to a different port number.  This is the way CodeWorld works on the main servers: it listens on port 8080, and nginx forwards from port 80 to port 8080 for incoming requests from the outside.

**Comment by Carina-Cai** [comment]
I tried setting up a nginx proxy to forward requests from port 80 to port 8080 following [https://eladnava.com/binding-nodejs-port-80-using-nginx/](url) but somehow it didn't work. There was no port listening on port 80.
I tried to modify the last command so that it binds to 8080 (not sure whether it is feasible) and another issue came up.
<img width="734" alt="Screen Shot 2020-12-29 at 8 44 04 pm" src="https://user-images.githubusercontent.com/76047281/103275295-faf51100-4a17-11eb-856c-df685956dbef.png">
The directory `codeworld-base/dist/doc/html` was created manually when running `cabal haddock --html` and there was no file inside even after successfully running this command.

**Comment by cdsmith** [comment]
That file is created by `build.sh`, here: https://github.com/google/codeworld/blob/master/build.sh#L49  The command that generates it is `cabal haddock --hoogle`.  I'm puzzled again why you're saying it was created manually.  The `build.sh` script already does all of that, as linked above.

**Comment by Carina-Cai** [comment]
There was issues when I ran `cabal haddock --hoogle` and I changed it into `cabal haddock all --haddock-hoogle`. Does it still work?

**Comment by cdsmith** [comment]
I honestly don't know if that command will work, or what it does.

I'd like to help you here, but almost everything you've reported so far seems to be working in the current code, but not working for you because of something else that you changed.  The only way this is going to work is if you can tell me what problem you ran into before you made any changes on your own.  For example, what do you mean by "There was issues when I ran `cabal haddock --hoogle`?  You mean the build script failed?  What was the error message?

**Comment by Carina-Cai** [comment]
I deleted the screenshot for the error I encountered back then but as I recall, the error should be something like "command does not exist '--hoogle'''.
I know there were quite a lot of weird issues happening because the changes I've made. Do you suggest me to rebuild the whole thing again? Thank you so much for helping me there.

**Comment by cdsmith** [comment]
Sure, starting from a fresh install would be good.

I did a little bit of poking around, and found that `--hoogle` is not accepted by newer Cabal versions.  At https://github.com/google/codeworld/blob/master/install.sh#L196, the install script explicitly installs version 2.4, where this command will work.  Is that something that you changed?

**Comment by Carina-Cai** [comment]
No, I didn't change the version to be installed.
<img width="777" alt="Screen Shot 2020-12-31 at 7 04 47 am" src="https://user-images.githubusercontent.com/76047281/103378500-a5635600-4b36-11eb-8e85-2ef37234d935.png">

**Comment by Carina-Cai** [comment]
I started the installation from scratch but the same thing occurred. The file is still missing and the very last command of build.sh ended without completion. What is it supposed to be like?
<img width="719" alt="Screen Shot 2021-01-02 at 6 15 32 pm" src="https://user-images.githubusercontent.com/76047281/103454810-a0232880-4d3b-11eb-85ac-b3ab4d08bd41.png">

**Comment by Carina-Cai** [comment]
The version bound actually solves this issue. Thank you so much for helping out!
