### ISSUE TITLE
No fold/reduce functions available in codeworld?

### ISSUE THREAD

**Issue by maspotts** [google/codeworld#1480]
**Shared Program**: https://code.world/#Pss8gW_0yQqOj_L9wLm0QDQ

**Description**

I'm trying to show my kid how to replace this pattern:

```
picture1 & picture2 & picture2
```

with (the codeworld equivalent of) this pattern:

```
foldl1 (&) listOfPictures
```

but I can't find foldl (or foldl1, foldl', foldr, etc.) in codeworld:

```
Variable not in scope:
      foldl :: ((Number, Number) -> Number, Number, [Number]) -> t
```
and I also can't import Data.List:

```
Could not find module Data.List
```

Is this possible, or am I trying to do something that's forbidden within codeworld?

**Comment by cdsmith** [comment]
There is no general fold in CodeWorld.  There are specific folds, including `pictures`, which does what you want.

If you want the Haskell base, you should use http://code.world/haskell, and import the CodeWorld module.  That will get you a standard Haskell environment.

**Comment by bbarker** [comment]
Just to elaborate slightly, I think the lack of `fold`s is due to type classes not being exposed in the CodeWorld language.

**Comment by maspotts** [comment]
Thanks so much for that explanation (and the detail).  I definitely want to stay within codeworld because of the Picture type; I did try to step out (code.world/haskell) but I couldn't import Extras.Cw (due to it being hidden).  I guess my ideal scenario would be a way to use pure haskell but have the whole of codeworld base + extras available; is that possible?

But for now the pictures funciton (which I had totally missed - doh!) is a great solution.

Thanks again,

Mike

**Comment by cdsmith** [comment]
@maspotts Yes, http://code.world links with the `codeworld-base` package, while http://code.world/haskell links with `codeworld-api` and hides `codeworld-base`.  The ideal situation would be that everything in `codeworld-base` is also available in either `base` or `codeworld-api`... but you are right that the `Extras.*` modules do not yet exist in `codeworld-api`.  If anyone wants to complete that port, I would be happy to review the pull request.   I agree with the change in principle, but it's not on my list of changes I'll be making soon.

**Comment by cdsmith** [comment]
You can also see https://github.com/google/codeworld/issues/1477 for some discussion of using `base` from the CodeWorld educational dialect.  It is possible, but it's complex enough that I definitely wouldn't recommend it for students.  But if you want to use it to implement some kind of framework to provide to your students to import by hash, that would be quite reasonable.

**Comment by maspotts** [comment]
Thanks: funnily enough [#1477](https://github.com/google/codeworld/issues/1477) was also from me, before I discovered the github repo, so thanks for pointing out all those replies to me! :). I'm finding codeworld (in the browser) ideal for onboarding my mathematically inclined 7th grader to coding; he's using it to code up his extra credit algebra homework currently; but it would certainly be awesome to be able to access the codeworld environment (especially Picture) from codeworld/haskell so as to be able to to gently transition him to pure haskell (and perhaps then purescript) at some point.  Being able to import all of codeworld-base (including extras) would be perfect.

Mike

**Comment by cdsmith** [comment]
Picture is already available in http://code.world/haskell; just import the `CodeWorld` module.

The `Extras.*` modules are not.

**Comment by maspotts** [comment]
Yes I found that: thanks!  Unfortunately he needed a bigger coordinate grid than the default (10,10) so we had to use CustomGraphed() from Extras.Cw, which means we couldn't use code.world.haskell for that because we couldn't import Extras.Cw .

**Comment by cdsmith** [comment]
I've filed a more targeted issue for Extras not being available in codeworld-api.  I think everything else here has been resolved, so I'll close this.  Please reopen if you disagree.

**Comment by maspotts** [comment]
Thanks!
