### ISSUE TITLE
Don't continue building if program is not defined

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1507]
**Program:** https://code.world/#Pm8quyz2oMN7wSfv0mgKFSg

**Message:**

    program.hs:1:1: error:
        The variable program is not defined in your code

**Comment by cdsmith** [comment]
This was a duplicate error message, because the error about not defining program was a warning, so the program was passed on to GHC.  We don't need to do that when we know it will fail.

**Comment by cdsmith** [comment]
Actually, this is fine.
