### ISSUE TITLE
Hash-based sharing should work with funblocks

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#151]
Hash-based sharing (e.g., https://code.world/#PHE23AiqA1dJweMOLJb3e5g) doesn't work with FunBlocks.  We should make it work.

My current thinking is that the hash should identify a JSON value, containing BOTH the generated code, and the Blockly XML for the block layout.

**Comment by stefan-j** [comment]
Added in #158 
Currently the XML is stored separately in the blocklyXML build mode.
