### ISSUE TITLE
Display and selection of Unicode letters

### ISSUE THREAD

**Issue by szabi** [google/codeworld#1525]
* Type: Usability feature request
* Component: Web editor

# Current behaviour

Unicode characters of the category L_ (:= {Ll, Lu, Lt, Lo, Lm}) which are not in the ASCII subset are displayed in red and act as a non-word character when highlighting occurrences of a token/identifier (the green background colour highlight when the cursor is on an identifier). [interestingly, it does not act as a non-word character for double-click selection of identifiers], see example:

<img src="https://user-images.githubusercontent.com/206806/133829875-ffd9a687-a978-43ff-b226-fccad28e4476.png" width=50%/>

# Feature request

Color the characters the same as the rest of the identifier. Do not treat them as non-word characters for token occurrence highlighting, so that all of the identifier (from true non-word character to non-word character) is found and highlighted.

# Use Case / Background

I started teaching my boys programming using `code.world`. They don't speak English but have basic literacy in Hungarian. The nice thing about `code.world` being a Haskell derivative is that one can super easily "translate" the 'builtin' commands, much easier than in any C-family language or python, as you know:

```haskell
kör = circle
téglalap = rectangle
rajza = drawingOf
```
and then they can actually use these terms "natively". As Haskell supports Unicode in identifiers, this works great out-of-the box, as expected, and makes the program very readable and approachable to them:

```haskell
logo = kör(4) & téglalap(8, 8)
program = rajza(logo)
```

However, the in-browser editor that comes with `code.world` treats these Unicode letter characters different from the others: they are displayed red, which looks like signifying an error, and throws off my kids: "why is this red" ... "is there something wrong with the code"? -- even though it is not and it works perfectly.

**Comment by cdsmith** [comment]
See https://github.com/google/codeworld/blob/master/web/js/codeworld-mode.js#L33 for the regular expressions that control this in the educational dialect.  If these regular expressions can be extended to match unicode characters, I'm happy to merge a pull request to do so.  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes looks promising.

**Comment by cdsmith** [comment]
That was easy!

**Comment by szabi** [comment]
Wow, Christ, that was an impressively fast response to a marginal usability feature  request!

Thanks!

A minor nitpick:
This fixed the colouring issue, but not the "token highlighting" (with light-green background)
<img width="232" alt="example-20210920" src="https://user-images.githubusercontent.com/206806/133991294-2691b2f7-b9bb-495f-8467-142a333ee5e7.png">
(With the cursor on `betáp`, the expectation would be to highlight all of it, and to not highlight the `bet` part of `betűkkel`).

I'm only mentioning this because I'm hoping that with what you've learned for 5c73bc6 the fix will be similarly easy, just that it's a different code block that governs that highlighting behaviour.
