### ISSUE TITLE
codeworld-api doesn't compile against reflex reflex-0.9.0.0

### ISSUE THREAD

**Issue by GeorgeCo** [google/codeworld#1597]
codeworld-api doesn't compile against reflex reflex-0.9.0.0 on ghc 9.4.4

It seems like it the version bounds need to be bumped as it compiles with --allow-new

$ cabal install codeworld-api --lib
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: base-4.17.0.0/installed-4.17.0.0 (user goal)
[__1] trying: codeworld-api-0.8.0 (user goal)
[__2] next goal: parsec (user goal)
[__2] rejecting: parsec-3.1.16.1, parsec-3.1.16.0, parsec-3.1.15.1 (constraint
from user target requires ==3.1.15.0)
[__2] trying: parsec-3.1.15.0/installed-3.1.15.0
[__3] next goal: reflex (user goal)
[__3] rejecting: reflex-0.9.0.0 (conflict: codeworld-api => reflex>=0.6.3 &&
<0.9)
[__3] rejecting: reflex-0.8.2.2, reflex-0.8.2.1, reflex-0.8.2.0,
reflex-0.8.1.1, reflex-0.8.1.0, reflex-0.8.0.0, reflex-0.7.1.1,
reflex-0.7.1.0, reflex-0.7.0.0, reflex-0.6.4.1, reflex-0.6.4, reflex-0.6.3,
reflex-0.6.2.4, reflex-0.6.1, reflex-0.6, reflex-0.5.0.1, reflex-0.5,
reflex-0.4.0.1, reflex-0.4.0, reflex-0.3.2, reflex-0.3.1, reflex-0.3,
reflex-0.2, reflex-0.1.1, reflex-0.1.0, reflex-0.0.1, reflex-0.7.2.0,
reflex-0.6.2.3, reflex-0.6.2.1 (constraint from user target requires
==0.9.0.0)
[__3] fail (backjumping, conflict set: codeworld-api, reflex)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, reflex, parsec, codeworld-api
Try running with --minimize-conflict-set to improve the error message.

**Comment by cdsmith** [comment]
Uploaded 0.8.1 with updated version bounds for reflex and mtl.  It builds with GHC 9.4.4 in my tests.

**Comment by GeorgeCo** [comment]
Thanks Chris!
