### ISSUE TITLE
Code duplication between codeworld.js and blockworld.js

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#164]
These should be cleaned up to share the same common code when possible, rather than maintaining two copies.

**Comment by stefan-j** [comment]
I know about this, I was feeling guilty when doing this. 
The common elements should be generalized and moved to a separate file. 

A related problem is that the UI differs for FunBlocks and small differences creep into annoying places.

**Comment by cdsmith** [comment]
It's fine to start out with a copy.  I just wanted to get the bug tracking in place for cleaning it up.
