### ISSUE TITLE
Funblocks error highlight looks identical to selection

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#166]

**Comment by stefan-j** [comment]
I was playing around with red, but couldn't get it looking right.  Any ideas on displaying it a bit differently?

**Comment by cdsmith** [comment]
I don't have any ideas off-hand.  If you'd like to dup this to your own bug (#169), that sounds good, so we just have the one outstanding issue to track the UI investigations.

**Comment by stefan-j** [comment]
Issue is now included as part of #169.
