### ISSUE TITLE
Improved visual indication for disconnected inputs 

### ISSUE THREAD

**Issue by stefan-j** [google/codeworld#169]
Currently when a block has disconnected inputs a whole selection of blocks affected get highlighted yellow.
This can be further improved by:

1. Displaying a visual notification that the block has disconnected inputs
2. Maybe only highlight the affected block with disconnected inputs and not all of them.
3. Changing the highlight, currently the error highlight looks too similar to regular block selection (Previously issue #166)

**Comment by cdsmith** [comment]
I like this change so far!  But I would like it even more if:

1. The warning icon appeared immediately when placing the block (but the popout only appeared when pressing Run.
2. The warning didn't go away on its own after time.
3. This same warning didn't get confusingly re-used for situations where there's no top-level block.

**Comment by cdsmith** [comment]
Will follow up with specific issues for any remaining details.
