### ISSUE TITLE
Need validation for funblocks numbers

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#176]
Numbers in funblocks aren't validated.  If you type something that's not a number, you just get an error in the generated source.  (Or, if you type a valid expression, perhaps even no error!)

**Comment by cdsmith** [comment]
The validation code is acting funny.  It seems to only validate that some prefix of the text is a valid number.  That leads to confusing behavior, where if I type "2/3", I get no error indicator, but the input silently changes to 2.

**Comment by stefan-j** [comment]
This is due to the way Javascript's parseFloat behaves, which is used in the validation. parseFloat truncates the starting number out of the string if the string contains other characters.

 I'll change it to Number for more intuitive behavior.
