### ISSUE TITLE
Comment block resizing doesn't match the text size.

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#179]
It seems like something in the comment resizing logic is underestimating text width.  Space characters seem to play a big part.
![comment_bug](https://cloud.githubusercontent.com/assets/544744/16363266/7846941e-3b7a-11e6-9424-d0761d4dd444.png)

**Comment by stefan-j** [comment]
I'm having trouble reproducing this. What browser are you using?

**Comment by cdsmith** [comment]
I'm look at this in Chrome on Windows at the moment.  I'll try a few more options when I get to the office later.

**Comment by cdsmith** [comment]
Okay, it has something to do with zoom.  I can only reproduce when zooming.  The problem goes away when the zoom level is exactly the default.

**Comment by cdsmith** [comment]
Not reproducible on Linux, in either Chrome or Firefox.  I don't think this is a big deal.
