### ISSUE TITLE
Definition blocks don't update correctly with type changes.

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#186]
Reproduction steps:

1. Start with https://code.world/blocks#PzkcPBeGIhH7FDLlqF8AYcg
2. Disconnect the text block from the `let` block for foo.

The `foo` block in the main expression should go back to a polymorphic block.  Instead, it just disappears!

**Comment by cdsmith** [comment]
This still doesn't quite work.  The block doesn't disappear now, but it is insufficiently polymorphic.

For example, try building this program (leaving the ____ terms disconnected):

    main = drawingOf(if ____ == foo then blank else blank)
    foo = ____

Completing the definition to 'foo == 5' correctly updates types in the `==` block.  But disconnecting the foo block again leaves the type specialized in the `==` block.

**Comment by cdsmith** [comment]
There are still problems here.  I think the ad hoc approach to this one is failing.  We're essentially implementing type unification here, and there are well-known approaches to doing so.  Is it time to consider this from a more formal perspective?

Examples of cases that are still broken:

1. Define "a = a" (using a let block connected to its own variable).
2. Drag out a let block for "foo".
3. Drag the "a" from the first "let" to the second, then back again.  Oops, the blocks are still assigned the same type variable!
4. Connect another "a" to some block with a monomorphic type.  Oops, "foo" is now constrained to the same type!

Another one:

1. Create a let block for "foo", and an `==` block.
2. Place the variable "foo" on one side of the equality.  It's still polymorphic.
3. Define `foo` to a number.  The first block correctly becomes monomorphic.
4. Detach the number.  Oops, the connected `foo` block remains monomorphic!

All of these failures follow the same pattern, which is that there's some missing case where you're trying to partially correct types.  I think perhaps you should first run type unification over the entire program, then rename the type variables to match the old values if you prefer.

**Comment by awmorp** [comment]
The code to restore type variables when a block is disconnected currently only works for the disconnected child block and its former parent/ancestor block. It doesn't look at any other unconnected blocks. The relevant code as a starting point is here: https://github.com/stefan-j/blockly/blob/master/core/connection.js#L623

**Comment by stefan-j** [comment]
@awmorp  Thanks !
I also saw you did some work with the resetting the types upon disconnect with `copyConnectionTypes_`.

**Comment by cdsmith** [comment]
This seems to be obsolete.  The problem is different now, and @stefan-j is already overhauling type inference.
