### ISSUE TITLE
Undo command is available, but broken

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#187]
A right-click on the trash icon gives an "Undo" menu item.  But it seems broken.  I get the messages:

    TODO: Inspect trash.
    blockly_compressed.js:1245 Can't move non-existant block: )qNy1@4u){JD%.]RSR4C
    blockly_compressed.js:1234 Can't uncreate non-existant block: )qNy1@4u){JD%.]RSR4C

**Comment by stefan-j** [comment]
I'm getting the same messages, though the undo and redo seem to be working correctly.

**Comment by cdsmith** [comment]
There are a few weird things about undo... but I'll file them as separate bugs.
