### ISSUE TITLE
Weird refusal to unify blocks

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#200]
This is a bit picky to reproduce, but here are steps that work:

1. Create a let block, and rename it to `a`.
2. Connect the `a` block to the definition (so the block defines `a = a`)
3. Create a new let block, which will be called `foo`.
4. Drag the `a` block from the first let to the `foo` let block.

Expected: it should connect.  Actual behavior: it fails to connect.

**Comment by cdsmith** [comment]
This might be the same as #186?

**Comment by stefan-j** [comment]
Yeah, it is closely related, it will be fixed once 14c77c977125d4d35f2a4d12496ed991d21a9ea6 gets merged.

**Comment by cdsmith** [comment]
Closing as a dup, then.
