### ISSUE TITLE
Renaming Let blocks is broken

### ISSUE THREAD

**Issue by stefan-j** [google/codeworld#201]
This issue comprises of two points:

1. Currently multiple let definition may have the same name.

2. Furthermore, the incorrect caller blocks sometimes get renamed.
For example, in the program [#P3uExjsDV-Z4LbjfLJrpptQ](https://code.world/blocks#P3uExjsDV-Z4LbjfLJrpptQ), remove the number block from the bar definition, then `foo` gets incorrectly renamed to `bar2`

**Comment by stefan-j** [comment]
Also, when adding a new definition with the same name, and then renaming it, the incorrect caller blocks get renamed.

**Comment by stefan-j** [comment]
Renaming of caller blocks for a let definition is temporarily disabled since PR #201

**Comment by cdsmith** [comment]
This issue still seems to occur.  If I add blocks for this program:

    main = drawingOf(bar)
    bar = blank

Then drag a new "let" block from the toolbox, the existing "bar" in main is renamed to "bar2" along with the new block.  It should instead keep the same name as the old block it referred to before.
