### ISSUE TITLE
Context menu lets you create an enabled disconnected block

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#205]
To reproduce:

1. Define a let block.
2. Right-click the block.
3. Choose "Create foo"

This creates a new "foo" block, which is enabled initially, but not connected to a top-level expression.  Dragging it anywhere causes it to become disabled.

This is pretty minor, but it looks broken when you find it.  I'd actually rather remove the context menu option entirely, since creating a new disabled block doesn't look very good.

**Comment by cdsmith** [comment]
Copy and paste (ctrl-c and ctrl-v) do the same thing.

**Comment by cdsmith** [comment]
As does the "Duplicate block" menu option.

Since this is pretty widespread, I take back by earlier comment about disabling the functionality.  Disabling copy and paste is definitely not a possible option.  So it's just a matter of catching the change event and disabling when needed.

**Comment by stefan-j** [comment]
I'm disabling the block in the create event as well in commit dcdbfe58ad3ea3994399b22712f40c5318069cc6.

However I think I'll also remove the create block option from the context menu.
