### ISSUE TITLE
Attempting to use "Save As" command results in JavaScript error

### ISSUE THREAD

**Issue by rcook** [google/codeworld#208]
Repro steps:

1. Navigate to https://code.world/
2. Open JavaScript debugger (Ctrl+Shift+I on Chrome, for example).
2. Sign in using Google account.
3. Type some text into the editor.
4. Click "Save As".
5. Enter a project name and click "Save".

Result:

The following JavaScript error is output to the console:

```
codeworld_shared.js:427 Uncaught ReferenceError: getWorkspaceXMLText is not defined
```

And the project is not saved.

Tested on following browsers:

* Chrome 51.0.2704.103
* Firefox 41.0.1
* Internet Explorer 11.0.9600.18349

All on Windows 7.

**Comment by cdsmith** [comment]
https://github.com/google/codeworld/commit/62a59208ad54a7f1b350632a6b9f51877a413859 is responsible.  I'll send a fix in a moment.

**Comment by cdsmith** [comment]
@stefan-j Let's be more careful with changes to the shared code in the future!  This has broken for a day or so now, and people haven't been able to save work. :(

**Comment by rcook** [comment]
Thanks! I've verified the fix at https://code.world/.
