### ISSUE TITLE
Very large circles don't render correctly

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#209]
https://code.world/#P7I8K0C3_2epHD9kA7hSyHw

**Comment by cdsmith** [comment]
Thanks to @NeilFraser for the report.

**Comment by NeilFraser** [comment]
Interestingly the above link works fine in Firefox.  Though add another digit and Firefox starts to fail too.

**Comment by cdsmith** [comment]
Same thing for Chrome 51.0.2704.81, on Android.  The link above works, but it still fails for larger numbers.  Probably a matter of different generated floating point code?  In any case, the issue remains.

**Comment by cdsmith** [comment]
The JavaScript that's run looks like this:

    var c = document.getElementById("foo");
    var ctx = c.getContext("2d");
    ctx.save();
    ctx.translate(250, 250);
    ctx.scale(1, -1);
    ctx.fillStyle = 'rgba(255,255,255,1)';
    ctx.fillRect(-250, -250, 500, 500);
    ctx.save();
    ctx.beginPath();
    ctx.arc(0, 0, 1074719.875, 0, 360, false);
    ctx.lineWidth = 25.0 * 85977.59;
    ctx.strokeStyle = 'rgba(0,0,0,1)';
    ctx.fillStyle = 'rgba(0,0,0,1)';
    ctx.stroke();
    ctx.restore();

To me, that looks essentially correct, and the fact that it renders incorrectly is a (minor) browser bug.

That said, though, it's weird.  I originally copied my implementation in `gloss` (see http://hackage.haskell.org/package/gloss-1.10.2.2/docs/src/Graphics-Gloss-Data-Picture.html#circleSolid) of drawing a filled circle by drawing a thick circle with line width equal to twice the radius.  If, instead, I do this:

    ctx.arc(0, 0, 25.0 * 85977.59, 0, 360, false);
    ctx.fill();

then the circle renders correctly.

**Comment by cdsmith** [comment]
Partially fixed by commit f27a674 by using fill() for solid circles and sectors instead of the thick circle trick.    This increases the radius after which the function stops working to around 5 billion pixels (aka 200 million CodeWorld units).

We could still do a little better by capping the radius used to a reasonable value; but as long as browser don't implement this, there's no 100% correct solution.  I'm not sure I want to bother with a bunch of arbitrary changing of users' parameters until there's a real problem...
