### ISSUE TITLE
Funblocks should implement tuple types

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#213]
It's unclear how to make this fit with the connector-shapes-as-types philosophy.

This is needed for points, which are needed for paths and polygons.

**Comment by awmorp** [comment]
I believe this is already implemented in Polymorphic Blockly. Check out this video: [https://cseweb.ucsd.edu/~lerner/polymorphic-blocks-long.mp4](https://cseweb.ucsd.edu/~lerner/polymorphic-blocks-long.mp4)
Sample block code: [https://github.com/awmorp/blockly/blob/master/blocks/typed-blocks.js#L292](https://github.com/awmorp/blockly/blob/master/blocks/typed-blocks.js#L292)

**Comment by cdsmith** [comment]
The current vertical pair blocks are nearly useless for creating polygons.  Can we make them inline blocks with standard tuple syntax instead?  Or, if you really feel strongly about the vertical layout, at least offer both?

One potential problem is that the massively complex shape for pairs is too tall for many inline uses...

**Comment by stefan-j** [comment]
The current shape is from Sorin's original polymorphic blocks. 

I can change it to something more compact such as this ?
![2016-07-29-130256_3840x1080_scrot](https://cloud.githubusercontent.com/assets/2664883/17246510/ed1e4968-558c-11e6-92ab-e34cf948ca16.png)

Though, both type connector shapes are still being drawn vertically which still takes up some space. I could change it to have only a single output connector shape, though we lose some expressiveness.

**Comment by cdsmith** [comment]
I don't suppose it's possible to make this look like this?  `( _____ , _____ )`  Where the `_____` are spaces for other blocks.

**Comment by cdsmith** [comment]
This looks great now!

Tuples with more than two elements could be cool... but would be blocked on pattern matching anyway, and technically, you can build anything out of nested pairs now. :)
