### ISSUE TITLE
Better local variables

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#222]
The existing model for local variables has some serious drawbacks.

1. Most importantly, local variables look *completely* different from built-in names.  Pedagogically, this is a disaster.  We need to find a better answer.
2. The existing system is broken anyway.  There are different blocks for references to a local variable bound by a list versus a function parameter, and they look identical but aren't interchangeable.

Ideally, the blocks that define these local variables would have some kind of a local toolbox, from which one could drag blocks for their local variables.  App inventor (which uses blockly) has something kind of like this.

![appinv](https://cloud.githubusercontent.com/assets/544744/16909597/a1aa8a26-4c88-11e6-9ff2-2944e672f99e.png)

(I even wish these labels looked like blocks instead, as in the toolbox.  But if they turned into blocks when dragged, that would be sufficient.)

**Comment by stefan-j** [comment]
That is actually a good idea. The current one was meant to be temporary.

Just to reiterate, in the above app-inventor picture, the user should be able to drag x,y or touchedSprite out from the block, which should instantiate a calling block with that name?

I'll see what I can do.

**Comment by stefan-j** [comment]
Ah ok, I see. It opens up a toolbar upon hover.

**Comment by cdsmith** [comment]
Oh, I actually would prefer if you could just drag it out.  Too bad about the toolbar.

**Comment by cdsmith** [comment]
If blockly already implements the toolbar on hover approach, maybe it would also work to have just one such bock, called "local definitions" or some such thing, and put all the blocks in there.

**Comment by stefan-j** [comment]
App Inventor made their own custom Flyout, so its not officially part of Blockly. 

![localvars](https://cloud.githubusercontent.com/assets/2664883/16977257/9045db7e-4e44-11e6-86ce-be12c07b494e.png)

I'm working on something like this, for the functions as well. Calling blocks can be dragged out from the white block.

**Comment by stefan-j** [comment]
One minor issue would be when the user connects them to another block, where the variable name is outside scope.. 
I should probably add a warning or disable the block if the variable name is not in scope.

**Comment by cdsmith** [comment]
That looks awesome!

Yes, I guess preferably trying to connect such a block outside of its scope would just fail to connect, but an error message would be okay, too.
