### ISSUE TITLE
Continuous code update misses some changes

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#225]
I've noticed at least a couple places where changing the program doesn't auto-update the generated code:

* Editing names in a text box.
* Deleting blocks from the context menu.

In both cases, dragging a block causes the update to happen.  Does this perhaps use the wrong event listener?  Doesn't Blockly fire some kind of event any time the document changes?  This update seems to only happen on specific events, instead.

**Comment by stefan-j** [comment]
Currently it only updates the code on the move event. I'll update it for any change event.
