### ISSUE TITLE
Wrong type in haddocks

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#238]
The haddocks give the wrong types for `interactionOf` etc, as defined here:
https://github.com/google/codeworld/blob/master/codeworld-api/src/CodeWorld/Driver.hs#L682
Note the `[Double] ->` which is actually not in the type of the real, GHCJS-visible `interactionOf`.

BTW, why was the `[Double]` argument dropped?

**Comment by cdsmith** [comment]
Ah, thanks.  I'll fix that.

To answer your question: the `[Double]` argument was a trick for getting random numbers in the basic CodeWorld environment, where we don't export most of the `IO` monad.  CodeWorld simulations and interactions are therefore given an infinite list of random numbers as a parameter.  This is not really related to graphics or user interaction, so it's outside the scope of the `codeworld-api` package.

Of course, you can do the same thing at http://code.world/haskell.  You'd just import `System.Random`, use `getStdGen` and `randoms`, and use the resulting list directly to build the initial state.
