### ISSUE TITLE
Change the default variable name to x instead of bar

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#239]
When defining a variable, the default name should be `x`.  This is the normal default in mathematics, and students won't understand `bar` and will try to associate a meaning with it.

**Comment by stefan-j** [comment]
Should we also then let function variables start with `a` ?

Somewhat related, should we allow function variables to have the same name as that function?

In Haskell
```
x x = x
``` 
is valid.

**Comment by cdsmith** [comment]
I don't have any great desire to allow "x x = x" as a definition.  I agree that anything that writes something like this by default is broken.  Also, after further thought, I'd rather have "x" as the default for parameters.  Perhaps global variables should default to "var", parameters should default to "x", and list comprehension indices should default to "i", or something like that?

I wish functions could default to "f", but the problem is that by the time the definition becomes a function, the name is already set.  So "var" is good enough.
