### ISSUE TITLE
Need a help button for blocks UI

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#245]
The help section for blocks is currently stubbed out.  It should have helpful stuff in it. :)

**Comment by stefan-j** [comment]
It is possible to have blockly in readonly mode. So we can possibly show program snippets. I'mnot sure how this would work with markdown though.

**Comment by cdsmith** [comment]
It definitely seems like a help section would benefit from some kind of visuals, but that's secondary to just having *something* there.

The visuals could be screenshots, but taking and storing that many screenshots sounds painful.  So if it were possible to write something in text form that would load up and display as blocks, that would be great.

As far as making it work with markdown, I imagine we'd just make it a code section, and add some JavaScript that post-processes the page and converts code sections to embedded read-only blockly workspaces.  That's not too different from what already happens on the text UI help page, except there it uses CodeMirror's runmode to add syntax highlighting and such, and adds a hyperlink to load the sample into the main editor.
