### ISSUE TITLE
codeworld-api via blank-canvas doesn't clear the whole screen

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#248]
When using the new `blank-canvas` implementation of codeworld-api, the canvas is resized to the entire screen, but only a square segment in the center is cleared after each frame.  This means that programs that draw off of that square leave leftovers from frame to frame.

The fix is one of:

a) If possible, resize the canvas to the square that CodeWorld usually guarantees, OR
b) If nothing else, at least clear the entire canvas on every frame

@nomeata

**Comment by nomeata** [comment]
Right, I noticed it as well. I’ll most likely go for option b). It should not be a  big problem if the stand-alone user can draw beyond what the web user can draw.
