### ISSUE TITLE
Stop does not for diverging expressions

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#250]
Interestingly, the implementation is lazy enough so that infinite drawing work so some extend, e.g.
https://code.world/haskell#Pw0wix1VHvyhlCiuXUJiBKA

But unfortunately, the Stop button does not really kill the computation, it still runs in the background. This is not nice. And it seems that is is possible to kill the computation, as when I recompile the code, it does get stopped.

However that works, maybe the Stop button could use the same, more reliable, method?

**Comment by cdsmith** [comment]
Looks like this was a side effect of the switch to split-pane layout in f768772774687dbcc422bf2a06c759342f24856c.  Calling hide() on the split pane seems to stop drawing the iframe, but leave it present enough that browsers still run its contents.

Needs at extra call to `runner.contentWindow.location.replace('about:blank');` somewhere in https://github.com/google/codeworld/blob/master/web/js/codeworld.js#L280

I'll fix it as soon as I get the chance.

**Comment by cdsmith** [comment]
Fixed.
