### ISSUE TITLE
Blocks was broken by my deploy-hash change

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#256]
The result format of /compile in the server changed due to my deploy hash changes in commit 4c95b471d1f45b34edf686bed407979784e14de8  I forgot to update the blocks UI.  Need to fix that ASAP

**Comment by cdsmith** [comment]
@stefan-j FYI, hold off before merging current upstream changes, to avoid interrupting your work.

**Comment by stefan-j** [comment]
Yeah I noticed this on code.world/blocks. I haven't yet taken a look at the new hashing system, but I can probably update the blocks UI accordingly this weekend.

**Comment by cdsmith** [comment]
I'll fix it.  Just wanted to bring this up so you didn't merge in changes and then get interrupted to sort out the mess.

**Comment by cdsmith** [comment]
@stefan-j In case you didn't see it, I did fix this.  It's now safe to pull from upstream.
