### ISSUE TITLE
Newly opened blocks projects show as modified

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#263]
If I open a blocks project, it often starts out showing as modified, before I make any changes.

**Comment by stefan-j** [comment]
Might it be due to #258, where there is only a slight change in the XML?

The current approach, IIRC, is to check whether the loaded XML differs from the XML of the current workspace.

**Comment by cdsmith** [comment]
I'm not sure.  I can no longer try this because none of my saved projects will open at all.

It seems believable that some intervening change caused the generated XML to be a little different, even while the old XML still parsed.  In those cases, I think we should find a way to not show the project as being modified.

**Comment by stefan-j** [comment]
It seems that some of this XML weirdness is caused by Blockly saving everything as lowercase, but some of my mutation attributes that are saved/loaded are camelCase, causing it not to load properly.

**Comment by cdsmith** [comment]
Okay, there are still some cases where a saved project opens as modified, but I think it's a one-off thing where the generated XML is different from earlier versions, and this is actually fine.  I'll close this.
