### ISSUE TITLE
block Event constructors are either wrong or very confusing

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#264]
The `MousePress` and `MouseRelease` buttons need both a `MouseButton` and a point.  But the case block for `Event` only assigns them one parameter, `a`.  It's not clear what `a` is supposed to be.  It should be a pair `(MouseButton, Point)`, but it doesn't match fit with pair functions in the blockly UI.

**Comment by stefan-j** [comment]
Yeah I forgot to add point to the type.

Now that I'm busy with this, which one of these would be preferred:

![2016-08-25-154021_3840x1080_scrot](https://cloud.githubusercontent.com/assets/2664883/17971386/efc5b346-6ada-11e6-9a59-4a3ed8e00b31.png)
which is a pair of a MouseButton and a point: `(MouseButton, (Number, Number))`, this can be seen more clearly in:
![2016-08-25-154028_3840x1080_scrot](https://cloud.githubusercontent.com/assets/2664883/17971418/13bdbc6c-6adb-11e6-8c7a-a699cac18bac.png)

or

![2016-08-25-154346_3840x1080_scrot](https://cloud.githubusercontent.com/assets/2664883/17971425/1a5326fc-6adb-11e6-84eb-669113ae9165.png)
which is where they are separated.

I'll also add some different connector shapes for `Event` and `MouseButton`

**Comment by stefan-j** [comment]
Nevermind. It has to be the first for the case block to be correct.

**Comment by cdsmith** [comment]
I very much hope you can implement the second one.  The tuple is there for the same reason as other tuples: because CodeWorld uncurries functions.  To me, having pairs as the types here seems a lot like having pairs as the input blocks to the `rotated` function.

**Comment by stefan-j** [comment]
Yeah I can change it. It involves using tuples for the user types in the code generation, which might make it more consistent with CodeWorld.
