### ISSUE TITLE
Blocks UI renders all pair accessors as `fst`

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#273]
Both firstOfPair and secondOfPair get rendered as `fst`.  This is wrong in both places: the CodeWorld functions are called `firstOfPair` and `secondOfPair`.

I tried to fix this, but it seems that the code generation for these blocks is part of the Blockly fork, which is odd, to say the least.  This seems to me to be squarely within the realm of CodeWorld-specific details that are not useful in any other environment.

**Comment by stefan-j** [comment]
If you haven't changed anything yet I'll quickly fix and move the tuples blocks to CodeWorld

**Comment by cdsmith** [comment]
I did fix it locally, but since I am not really set up to develop in blockly, I'll let you fix it, and just revert my changes for the next pull request.
