### ISSUE TITLE
Blocks still renders negative numbers with unnecessary decimal place

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#275]
Not a big deal, but just to remember this...

A recent change started rendering integers without the ".0" on the end.  That's great!  But for some reason, it doesn't work for negative numbers.  They still get rendered as "-5.0"

**Comment by stefan-j** [comment]
What's interesting is that `-1` works, `-2` works, `-3` doesn't.

**Comment by cdsmith** [comment]
A clue!

https://code.world/haskell#PNtbsmfoyxnnyXbJlaF6EJg

This seems to be a GHCJS bug.

**Comment by cdsmith** [comment]
Filed a bug there.  https://github.com/ghcjs/ghcjs/issues/508

**Comment by cdsmith** [comment]
Fixed by using a GHCJS that fixes `truncate`
