### ISSUE TITLE
Block warnings overwrite each other and are forgotten

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#285]
Create a block defining a function with two parameters having the same name.  Before defining the right-hand side, the warning on the block is "There's a block missing", which is just fine.

Now fill in the right-hand side, and the warning goes away!  But there's still a problem, with the duplicate parameter names.  Running this program gets all the way to the server, which generates an error message.  Opening the configuration popup re-adds the correct warning again.

**Comment by stefan-j** [comment]
I'll look into this. 

Aside from being overwritten, I've also seen warnings sometimes not being set on disconnect. I'm mostly setting them with an event so it almost appears as if events sometimes don't fire (the immediate placement disconnect thingy where the block doesn't get disabled might be related).

**Comment by cdsmith** [comment]
Okay, this seems to be fixed just by making it harder to get two warnings on the same program.  I hesitate to mark this as fixed, because it seems inevitable that there will be two ways to get warnings on a block *somehow*.

Do you know a new way to try to reproduce this?

**Comment by stefan-j** [comment]
Currently there are only two* possible warnings. One for when a block has _disconnected inputs_ and another for when it is _isolated_.

_disconnected inputs_ does not override any other, but _isolated_ may.

To reproduce:

1. Connect an `if` block to a `function` block
2. It now displays a warning for _disconnected inputs_
3. Disconnect the `if` block, it displays _isolated_ and not _disconnected inputs_

However it may not be a problem. I'm not aware of warnings being forgotten anymore.

It may happen that they aren't rendered sometimes. Usually moving them will trigger rendering of the warning.


*There is a third warning that gets displayed when the type inference algorithm fails on a block

**Comment by cdsmith** [comment]
Okay, I'll close this, then.
