### ISSUE TITLE
Weird parameter blocks type inference

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#302]
https://code.world/blocks#Pz3BY421hBEkE9jDUOwjotw

Why does the `ev` parameter get such an odd inferred type?  If I delete the parameter that is already connected, I can't even connect a new `ev` because its type is wrong.

If I try to rebuild the function now, all sorts of weird things happen.  Types aren't unified when they should be.  When types *do* unify, the parameter blocks aren't updated to match...

**Comment by stefan-j** [comment]
Internally, I'm using a const function named `ev : e -> a -> a` in generating the case expression. I'm renaming it to something that can't be entered by the user.

**Comment by cdsmith** [comment]
Oh, interesting!  I'll file a different bug for issues that arise when I rebuild with different parameter names.
