### ISSUE TITLE
Type inference doesn't run on newly loaded programs

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#303]
Load https://code.world/blocks#PfpEFNZWP293aHmHnyFjZsA

There are a bunch of type connections that render overly general types.  You have to disconnect and reconnect a few things before the inference algorithm will run.

**Comment by stefan-j** [comment]
Oops. The inference runs (can be seen by dragging out `x`, I just forgot to redraw the workspace afterwards

**Comment by stefan-j** [comment]
Nevermind, I am redrawing the workspace. 
I think its due to the error:
```
blockly_compressed.js:1205 Uncaught Types do not match, when trying to type Number
```
