### ISSUE TITLE
Parameters with multiple uses do not generalize

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#307]
https://code.world/blocks#PH5wSqyAmC-nOKCpywG2PCg

Here, `x` must be a number, because it's an argument to addition.  However, if you disconnect the `x` from the addition block, the remaining `x`, and the parameter on the left-hand side, remain as numbers.  I think this is because there's some state in the other `x` that remembers it's supposed to be a number, and that causes the left-hand side to fail to generalize.

**Comment by stefan-j** [comment]
I think this behavior is correct. The addition block in `else` is constraining `then` to be a number as well, which forces the `x` to be a number

**Comment by cdsmith** [comment]
Yeah, okay.  I thought I'd simplified a more complicated example where something happened incorrectly, but obviously I did it wrong.  Maybe that one was also correct.

**Comment by cdsmith** [comment]
I think #312 captures the broken behavior that I saw.
