### ISSUE TITLE
Something missing in type unification

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#308]
https://code.world/blocks#PH5wSqyAmC-nOKCpywG2PCg

![md5a9lskkng](https://cloud.githubusercontent.com/assets/544744/18187257/f0897c4a-705c-11e6-919a-47c90bff6caf.png)

The first element of `state` here is required to be a number, but one end of the connection seems to have missed this fact, and is still rendering as polymorphic.

**Comment by stefan-j** [comment]
This is unrelated to #312

**Comment by cdsmith** [comment]
Something seems to have fixed this.  I cannot reproduce any longer.
