### ISSUE TITLE
Errors likely due to overly aggressive caching of generated JavaScript

### ISSUE THREAD

**Issue by joshcough** [google/codeworld#31]
Hi, 

I'm using Chrome and currently getting many errors. My javascript console is telling me that it's simply internal server errors (when I press the run button). Things were working fine with Chrome last night. Was there possibly a redeploy that might have broken things?

Things are working well in Safari though. 

-Josh

**Comment by cdsmith** [comment]
All generated JavaScript is now served with `Cache-control: no-cache`, which should fix this.
