### ISSUE TITLE
Avoid idling for an interaction where the first parameter is const.

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#313]
An `interactionOf` where the second argument is `\_ s -> s` still loops and redraws (at least as long as the tab is open). If it is easy to detect that this is the argument, this looping might be avoided.

You already have this generic equality (in GHCJS) so you can check if the function returns the state unaltered. And in order to check whether it looks at the time argument at all, you can run it with an exception-throwing value as the first argument, evaluate the result, and catch the exception. If none is thrown, the function is guaranteed to always return the same value, and you can simply skip running it.

(Not a big deal, but might be nice, especially for pages which embed multiple interactions using `<iframe>`.)

**Comment by cdsmith** [comment]
Hmm!  I like the idea of using a bottom to probe for a constant step function.  That said, though, I am worried that `==` may diverge on some states.  Maybe there's a way to be clever about this.

**Comment by cdsmith** [comment]
One thing I could definitely do is check `reallyUnsafePtrEquality# state (step(state, undefined))`.  I am confident that if this is true, then I can stop spinning.  This is also possible without relying on GHCJS, which is nice.

**Comment by nomeata** [comment]
Right!

**Comment by cdsmith** [comment]
I actually think we'd want to use StableName for this, instead, to avoid retaining two versions of the state.  Same principle, though.

**Comment by cdsmith** [comment]
Status: I've pushed changes that implement this for idling as well as redrawing pictures.

Next steps are:

1) Fix a corner case where resizing the canvas now fails to redraw the screen.
2) Reimplement `drawingOf` as just a wrapper for `simulationOf`, with constant state.
3) Investigate the issue with "Yo Grandma" spinning on the second (but not first) splash screen.

**Comment by cdsmith** [comment]
The resize case was fixed.  I have merged the last bug into #422.  Filed #425 for the cleanup of `drawingOf`.  So I'm marking this as fixed.
