### ISSUE TITLE
Auto-complete should use symbols defined in the current program

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#33]
Right now, auto-complete works against a fixed list of symbols from the standard library.  In addition to that, it should look in the current file for things that look like definitions, and add them to the auto-complete list.

**Comment by Maaarcocr** [comment]
I would be interested in working on this feature for the Summer of Haskell. I would probably work on different others feature such as issue number 34: Auto-complete should be type-sensitive and issue number 129: Rainbow brackets. Would it be possible to further discuss about this possibility?

**Comment by cdsmith** [comment]
@Maaarcocr Sure, tackling a cluster editor usability features would be a great proposal!  Feel free to get in touch with me at cdsmith@gmail.com to discuss any questions you have.

**Comment by nixorn** [comment]
If it is actual, I can try.

**Comment by cdsmith** [comment]
It looks like a rough version of this was added in https://github.com/google/codeworld/commit/c63fd5ccb6d6c1017e643568216a005312b5fd42 by a Summer of Haskell student two years ago.  I missed it because it was one commit in a long list.

Remaining issues:

1. It only works for symbols with top-level type signatures.  This is probably okay, since implementing type inference in the browser is less than ideal.
2. The newly added symbols are appended to the bottom of the autocomplete list, which makes this feature less discoverable than it could be.
3. User-defined symbols are not included in the newly implemented doc-on-hover feature.  It would be great to add them there as well.

Points 2 and 3 together indicate that there's room for keeping some kind of canonical dictionary of known terms that is updated as editing continues, and is used as a common source for both hover and autocomplete.

**Comment by cdsmith** [comment]
@nixorn I noticed that you indicated you're working on this for [BountySource](https://www.bountysource.com/issues/2940977-auto-complete-should-use-symbols-defined-in-the-current-program).  As I mentioned above, @three implemented this in the summer of 2017.  I made a small improvement to sorting (which may have been broken by the doc-on-hover CL anyway, but I don't think so).  The core feature here already exists.  There are definitely improvements, but this gets messy in terms of the bounty.  I'd have to award the bounty to @three if he wants to claim it; otherwise, if the two of you agree to something else, I'm happy to go along.

**Comment by cdsmith** [comment]
Sounds great!  The plan sounds great to me.  You might want to limit how often you update the extracted list of hints/docs, because it might make typing annoying to scan the whole buffer on every keystroke for sizable projects on low-end Chromebooks that are used in many schools.  That's not too hard to fix, though.  Perhaps you could do something like: every time a change is made, we set a three second timer.  If additional changes are made in that three seconds, the timer gets reset.  When three seconds passes without another change, we scan the source and update the list."  (Or you could do something like the way syntax highlighting works, where you store the state and only incrementally rescan starting from the location of the change.  But that sounds more complicated.)

Thanks for the understanding about the bounty; I'm just trying not to leave anyone feeling they are owed something and didn't get it.  But if Eric doesn't want to claim it, then I'm happy to give you the bounty instead for your extension work.

**Comment by nixorn** [comment]
Is this also should be closed via #799 ?

**Comment by cdsmith** [comment]
Yeah... though I think I need to revert that commit.  It looks like we lost all the formatting in the auto-complete box.  Did you test that at all?

**Comment by nixorn** [comment]
Yes, I tested that code.
![image](https://user-images.githubusercontent.com/5370736/52260637-cb2a5500-2937-11e9-8f80-752035fd49c5.png)
Where is regression?

**Comment by nixorn** [comment]
Yes it is removed. I moved declarations from hint box to hover, because with hover it looks excess for me. But not for students, I missed that.

**Comment by cdsmith** [comment]
Okay, fixed the quirks that I found in autocomplete docs.  If you work on this more, you'll want to be sure to merge my last few commits.
