### ISSUE TITLE
Compiler errors include `forall` when the code does not accept it.

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#353]
Consider this code: https://code.world/haskell#P2Zwlp7PzgdyH16m9o__Dgg

We get the error message

```
Line 1, Column 1: Warning:
    Top-level binding with no type signature: foo :: forall t. t -> t
```
but using this type signature does not work:
```
Line 1, Column 16:
    Illegal symbol '.' in type
    Perhaps you intended to use RankNTypes or a similar language
    extension to enable explicit-forall syntax: forall <tvs>. <type>
```
Clearly, that’s confusing.

Usually, GHC prints error messages so that they are compatible with the language extensions enabled for the given code, so I assume something slightly weird with the CodeWorld setup.

**Comment by cdsmith** [comment]
Hmm... I get this from a fresh install of 

```sh
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
$ lpe Test.hs  # original version
$ ghc -Wall Test.hs 
[1 of 1] Compiling Main             ( Test.hs, Test.o )

Test.hs:1:1: Warning:
    Top-level binding with no type signature: foo :: forall t. t -> t
Linking Test ...
$ lpe Test.hs  # Add suggested type annotation
$ ghc -Wall Test.hs 
[1 of 1] Compiling Main             ( Test.hs, Test.o )

Test.hs:1:16:
    Illegal symbol '.' in type
    Perhaps you intended to use RankNTypes or a similar language
    extension to enable explicit-forall syntax: forall <tvs>. <type>
```

**Comment by nomeata** [comment]
Ok, nevermind then, then this is a bug in ghc and not something we can fix.

**Comment by nomeata** [comment]
Filed as https://ghc.haskell.org/trac/ghc/ticket/12597#ticket. Sorry for not checking it myself, I was overconfident that GHC does this right (maybe it did a long time ago).

**Comment by nomeata** [comment]
Simon fixed it, will likely be included in 8.0.2: https://ghc.haskell.org/trac/ghc/changeset/796f0f2ad7eefd1c9af5a7ef9bf56848067e85b1/ghc

**Comment by cdsmith** [comment]
Great news!  I'll plan to do the GHC 8 update around December, and then an upgrade to 8.0.2 (assuming it's not out yet anyway) is likely to be much easier.

I had intended to mention that, if you really wanted a fix sooner, there's already a mechanism in place to do regex-based post-processing of GHC error messages.  I use it extensively for the CodeWorld mode.  But it looks tricky to really do what you want, so it's likely best to wait on GHC to implement it properly.

**Comment by nomeata** [comment]
Not worth it for me at this time, but thanks for mentioning it.
