### ISSUE TITLE
blocks: "&" gets into bad state with invalid connector

### ISSUE THREAD

**Issue by amatteis** [google/codeworld#370]
To reproduce, create a definition that draws a circle and create a drawingOf containing an "&".
Add the definition to the "&", then click the gear icon on the "&" and add a parameter.
The & block now contains an extra connector that it should not have, with a shape that doesn't seem to fit anything. Trying to run the program with this block in it gives:

procedures.js:786 Uncaught TypeError: Cannot read property 'isFunction' of undefinedgetMode @ procedures.js:786preConnect @ procedures.js:798Blockly.Connection.connect_ @ blockly_compressed.js:924Blockly.RenderedConnection.connect_ @ blockly_compressed.js:1324Blockly.Connection.connect @ blockly_compressed.js:932Blockly.BlockSvg.onMouseUp_ @ blockly_compressed.js:1347e @ blockly_compressed.js:1697

**Comment by cdsmith** [comment]
@stefan-j Can you look at this if you have time?  It's easy to reproduce: all you need is a variable in an & block, and to open the mutator dialog.

This is causing problems with the class I'm teaching, and it's not at all obvious to me how to go about troubleshooting.  I'd be very grateful if you find anything.

**Comment by stefan-j** [comment]
Sure thing. Sounds like something is going wrong with the type inference. I'll take a swing at it sometime today.

**Comment by cdsmith** [comment]
Thank you, @stefan-j !
