### ISSUE TITLE
JavaScript exception: SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#373]
I get the above when trying to run [a game](https://code.world/haskell#PSlSDMPDzzljT7lwAn56YLA) on Codeworld. I guess it needs `wss` if the page itself is on `https`. Which needs to be supported by `codeworld-game-server`.

**Comment by nomeata** [comment]
I guess your setup has an SSL proxy taking care of that, because I don’t see any SSL code in `codeworld-server` either. Can you activate a similar proxying for the separate port?

Or is it easier for now to just let the main server also handle the websocket requests?

**Comment by cdsmith** [comment]
Yes, I need to proxy the websocket connection.  I'm working on that now.

**Comment by cdsmith** [comment]
Fixed.  The solution was ugly, because apparently the same SSL certificate can't be used for different ports, so I had to map https://code.world/gameserver to the websocket server.  When HTTP is used, it still points to :9160, so you can still develop without installing nginx.
