### ISSUE TITLE
Games should not keep very old state even when there are no events

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#377]
Splitting from #372 

Currently, games may keep track of states that are arbitrarily old, because they only update the committed state when handling events.  That has a few disadvantages:
1. It means a delay to replay a lot of time steps on the next event.
2. It means they hay retain a bunch of unnecessary heap in common cases, such as when the step function traverses a lazy list.

We could have the server send regular pings to clients, to inform them of the current server game time.  This allows them to advance the committed state.  or, we could have the clients just make an assumption that the server will never send events more than 15 seconds old, and advance their own committed state on a delay.  Or both.

**Comment by nomeata** [comment]
Pinging should be sufficent. I don’t see the advantage of arbitrary timeouts.
