### ISSUE TITLE
Client timestamps for game events

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#378]
Splitting from #372, idea is from @nomeata

It's unfortunate that games are basically always wrong about their local state after a UI event.  That's because the server gives the event its canonical timestamp.  But we trust the clients not to cheat, so we can have the clients set timestamps instead.

The trick is that the clients need to know a safe committed timestamp, before which no new events will be added.  That is no longer the latest server event, since there's clock skew between clients.  So clients will need to send pings with their current times, so that the server knows the true committed time, which is the oldest timestamp from any client.

**Comment by nomeata** [comment]
It might be sufficient if  the client estimates the time stamp the server will give to the client’s event, (it could ask for the difference by sending a time-stamped event) and then using this difference to almost correctly assign timestamps to unconfirmed local events as they enter the queue. This way, the general server protocol does not need to change.

**Comment by cdsmith** [comment]
First of all, I think it's reasonable to expect that 95% of the time, the after-the-fact change in time won't matter.  Most events will commute with events from other players, except for the occasional critical point (e.g., both players try to move to the same spot, or try to click the same object).  Most events will also commute with time steps, except in a few mechanics such as "click this before it disappears")

So, if the client estimates the server timestamp, what happens then?  Does it wait for a tenth of a second or so before applying the event locally?  I'm afraid that would be even worse!  We'd add visible latency in the 95% of the time that it doesn't matter, in exchange for avoiding a glitch in the remaining 5%.  I think it would generally be better to leave things as is.

**Comment by nomeata** [comment]
There is a middle way. Assume we estinate the round trip to be one second. State is `s`. Then, after the user presses a button (`e`)and half a second passed, then we'd display state `handle e (step 0.5 s)` instead of `step 0.5 (handle e s)`. This way, whenever the events comes back and we want and have to go to `handle e (step 1 s)`, there is no jump, but rather a smooth interpolation between the anticipated local state and the  eventual committed state.

**Comment by cdsmith** [comment]
This vaguely related to #385, which is a big about discrepancy of event times between client and server.  Though in that case, the client was  actually incorrect.

**Comment by cdsmith** [comment]
I think I want to just push ahead with the client-side timestamp plan.  I've made a few steps in that direction recently.  Some outstanding points here:

1. Clients do not yet send pings.  The changes in commit 2dfec1099bfaa6da578fee9bf0c9fa8df22656d6 make it easy to do, though.
2. Once that's finished, we need something (perhaps the game server, or perhaps each client individually) to keep track of the latest timestamp from each client.  The minimum of these is the committed time for the game.
3. The prediction code will need updates to support inserting events at arbitrary times without advancing the committed time.  This should be easy.

**Comment by nomeata** [comment]
But does it make sense to sort events by timestamp when the timestamps come from different sources?

**Comment by cdsmith** [comment]
It's true that clock synchronization is definitely a concern.  It would be possible to add approximate (e.g., SNTP-like) clock sync to the protocol.  I strongly suspect, though, that the artifacts from different clocks will be much less noticeable than one's own events changing timestamps in history.  At least the lag will be attached to things that other players do, which is more understandable.

**Comment by nomeata** [comment]
Hmm, ok. I agree that in the absence of conflicting events, the user experience should be as good as a local interaction, so it unavoidably has to be the local time stamp.

**Comment by nomeata** [comment]
I am about to write the paper section on this, and noticed we still haven’t implemented this scheme. I guess I should so that now.

If now the timestamps ensure order, and no longer the server, there is no point for the server to transmit an event back to the client, right? But we still might need to do that for eventual consistency, so hat the timestamp (if a `Double`) gets mangled by serialization the same way for all clients.

Should the timestamps really be doubles? Or `Integer` with some high precision (picoseconds or so).

What about events from two clients with precisely the same time stamp. I guess we can order by player number (although that gives an unfair advantage).

This scheme does not have much in common with the existing scheme any more, where the server orders events. That is a bid unfortunate for the narrative of the paper, but not much we can do about it.

If all clients count their time stamp from the moment they received the “game start” event, I think that ought to be enough synchronization.

**Comment by cdsmith** [comment]
I would have no complaints at all if you implemented this!

I think our plan for this currently is to drop clients whose pings fall too far behind?  If so, I agree that there is no reason for clients to receive their own events back again.  The only reason for changing this might be if, in the future, we were to try to recover from longer-term network unavailability by a client by telling it to skip some of its own history when it becomes available again.  But this can be done later if and when the change is made.

Timestamps are doubles on the client to start with, because they come thay way from the JavaScript implementation (https://developer.mozilla.org/en-US/docs/Web/API/Performance/now).  If transmitting doubles over the network is lossy, then we have other problems!  I think it's okay though:

    Prelude Test.QuickCheck> quickCheck $ \ (n :: Double) -> read (show n) == n
    +++ OK, passed 100 tests.

I'm not at all concerned about events with identical timestamps.  Client timestamps should have microsecond resolution, so I just don't think it will ever be a noticeable problem.

I am still concerned about clock synchronization, though.  If clients count their start times from the moment they receive the game start event, that's a TCP packet, so it's possible it could be dropped and retransmitted, leading to very big variations (a second?) in time until it's received.  And when that happens, this client's events would be significantly delayed to all other clients for the entire game, because of that one packet arbitrarily far in the future.  That being said, though, I'm all for implementing this in the simplest possible way, then filing a bug to add clock synchronization later.

**Comment by nomeata** [comment]
Good idea with the quickcheck test :-)

> And when that happens, this client's events would be significantly delayed to all other clients for the entire game, because of that one packet arbitrarily far in the future.

True. But remember that this client will – from its local p.o.v. – start the game when it receives the start package, so at least its own events will look just in time. There are two non-local directions to consider:

 * Packages from other clients to the late clients. Assuming the TCP connection gets a bit faster, these might actually carry timestamps that are, from the late client’s p.o.v., in the future. My code does not do that now, but should probably simply not apply these events until the local time has progressed far enough. If they are a bit in the past, then it looks like a normal delay.
 * Packages from the late client to other clients. They will be very much in the past, causing the list of pending packages to grow, and causing the late client to appear to be quite jumpy. But *shrug* – that is just a quantitative difference to the normal delay, not a large one.

Not a big deal so far, I’d say.

**Comment by cdsmith** [comment]
Done.  I'll file bugs for the remaining steps.
