### ISSUE TITLE
In the blocks interface, I can create lists only with 3 elements

### ISSUE THREAD

**Issue by alphalambda** [google/codeworld#393]
When I hover over the List block, it says "Create a list with any number of elements", but I cannot find a way to change the number of elements to either less than or more than 3. Either the message should say "Create a list with 3 elements" or there should be some more obvious way to change the number of elements.

**Comment by cdsmith** [comment]
The block has a gear on it, which you can use to change the number of elements in the list.

I agree this is counter-intuitive, but it's how the Blockly library traditionally works.  #342 is a related proposal for changing some other blocks that need mutators.

**Comment by alphalambda** [comment]
On Mon, Nov 07, 2016 at 09:04:28AM -0800, Chris Smith wrote:
> The block has a gear on it, which you can use to change the number of elements in the list.

Oh. I saw the gear and clicked on it, but it did not occur to me that I could change it.
I thought it was some graphical illustration of what a list is.

Maybe the tooltip should say: "Create a list with any number of items. Click on the gear to change the number."

**Comment by cdsmith** [comment]
I'm going to close this bug.  While I don't agree that there are better UI choices that could be made with blocks, I think the solution is ultimately the same as #342, which is already open.  I'm mostly pausing work on the blocks UI anyway.
