### ISSUE TITLE
Resizing panels separately

### ISSUE THREAD

**Issue by alphalambda** [google/codeworld#414]
There should be a way to resize the graphics output panel and the editor panel separately. To be able to read the code shown with a projector or smart board, students need a large font setting for the editor and a small graphics output panel. Otherwise, the graphics window leaves very little space for the editor, and students cannot see enough of the code at once.

**Comment by cdsmith** [comment]
I can definitely see adding controls for changing the font size in the editor, as long as the option is shown in a subtle enough place to avoid adding too much noise for students who will rarely use it.  Willing to accept a patch for this.

**Comment by cdsmith** [comment]
Fixed by editor font size, and draggable borders for the run area.
