### ISSUE TITLE
Desync bug in collaborations

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#443]
When playing the tank game (https://code.world/haskell#PQ94iinch5mmZ7J9FuhX4zw) with different clients on different networks, we reliably saw major desync problems, bad enough that we consistently saw clients disagree on who had won the game.  One client was Ubuntu on Linux, and the other was Windows 8 - browser unknown.

I cannot reproduce with two windows (even with Chrome vs FireFox) on the same browser.  Still trying.

**Comment by cdsmith** [comment]
Can reproduce a desync with two Chromebooks on the same wifi network now.  The desync is much more subtle.

**Comment by cdsmith** [comment]
Also confirmed that this happens with deterministic replacements for sin/cos, so this is NOT just #440

**Comment by cdsmith** [comment]
Reproduced with Snake, as well.  This is a weird one.

![snake-broken1](https://cloud.githubusercontent.com/assets/544744/23539955/45a1a930-ff93-11e6-8183-570af1661656.png)

See the section on the bottom right, where it appears that the snakes overlapped for a bit, and yet play continued!  So... what?  Perhaps the picture is being drawn from a different history than stored state, or... I have no explanation.

**Comment by cdsmith** [comment]
Okay, so it looks like the weirdness in the last comment is due to a bug/quirk in the snake game itself.  If two players simultaneously try to enter a previously unoccupied square, they can both succeed in doing so!  Then as long as they continue in the same direction, they'll continue to both enter unoccupied squares together, and continue to live, with overlapping paths.

The snake game still reproduced the bug, since the clients diverged.  But both clients actually did see "valid" games, according to the program being run.  So that's a little bit less weird.

**Comment by cdsmith** [comment]
It looks clear that this is triggered by UI events.  Even in environments that easily reproduce the desync in most games, the pendulum simulation (which uses no input) never desyncs.

It's also much easier to reproduce on slow networks.  Hotel wifi was sufficient to make all games unplayable.

**Comment by nomeata** [comment]
If it depends on the network connection, that rules out a problem with serializing the time stamp, right?
Assuming this once worked better, then I suspect c76405f74eea30199f8da21ba19a9dc98a7b2c34. Have you tried with a version before that?

**Comment by cdsmith** [comment]
No, I haven't.  So far this week, I've been stealing spare moments here and there.  Hope to have time to look deeper tomorrow

**Comment by cdsmith** [comment]
After some poking into this, I can confirm that it DOES happen using CodeWorld.Prediction, and does NOT happen using CodeWorld.Prediction.Trivial.  So there is a bug in the CodeWorld.Prediction module.
