### ISSUE TITLE
Error 500 on /compile

### ISSUE THREAD

**Issue by chrisgward** [google/codeworld#448]
HTTP Response Body:

```
A web handler threw an exception. Details:
data/haskell/user/[redact]/[redact].hs: hClose: resource exhausted (No space left on device)
```

**Comment by chrisgward** [comment]
This is on the https://code.world server, not a self-hosted instance.

**Comment by cdsmith** [comment]
Yikes!  We ran out of disk space on the main CodeWorld instance.  I've mitigated the problem by deleting the cache of compiled code, so it should work now.  I'll look into a longer-term solution now.
