### ISSUE TITLE
Risky Installation Process

### ISSUE THREAD

**Issue by wisn** [google/codeworld#459]
I've read https://github.com/google/codeworld/issues/4 and take a look on https://github.com/google/codeworld/blob/master/install.sh file. This automation installation process scares me where I've installed Haskell via The Haskell Tool Stack. Why not use Stack instead of only Cabal?

I saw that CodeWorld dependencies also placed in this repository. I think this would be great if every dependencies has their own repository. Since some developers might be wants to contribute to `codeworld-api` must clone this whole file.

This is just a suggestion since Stack also provides HSpec which let us to creates an unit testing.

**Comment by wisn** [comment]
Recently, I'm trying to install CodeWorld with `install.sh` on my VPS with 2 GB of RAM and 2 CPUs. It's failed with this message.
```
ExitFailure (-9)
This may be due to an out-of-memory condition.
```

After this failure, it's hard for us to continue the last step. So, this mean, we must **reinstall** again. With Stack, we may continue the installation by `stack build` command.

How about this?
CC @cdsmith

**Comment by cdsmith** [comment]
The `install.sh` and `build.sh` scripts just install GHC, GHCJS, ghcjs-dom, and the local libraries and binaries.  If you prefer to do this a different way, everything should still work.  GHCJS needs the student runtime libraries (`codeworld-api` and all those) installed into its package repository as part of this.  We definitely don't want to use stack (or cabal, either) to build student code.  We just invoke GHCJS directly for that.

I don't know how much easier stack would be for the setup.  The longest and most flaky steps are about installing node.js (which needs the be more recent than what Ubuntu distributes), and booting GHCJS (for which I see a consistent stream of bugs about problems with stack).  But if you get it working, please share what you did to set it up.

Incidentally, the out-of-memory error is mentioned in the README.  Booting GHCJS is expensive.  There are commands there to temporarily add swap space to compensate.

**Comment by wisn** [comment]
I've trying to use Stack and build CodeWorld by myself with `install.sh` steps. I found that it's really troublesome since there are so many packages problem. I think I will try again later.

**Comment by cdsmith** [comment]
Since @wisn reports that installation via stack isn't easy either, it doesn't look like there are concrete actions that can be taken here in the short term.  I've been talking to a few people lately about revamping the installation using Nix.  That looks a bit more promising -- both because Nix can handle non-Haskell dependencies consistently, and because Nix is used for the reflex platform, meaning there are people and commercial interests actively working on getting it working well with GHCJS.  I'd guess that will happen eventually.

For now, install.sh works if there's enough RAM to boot GHCJS.  I'm not sure what "risky" means in the title.  So I'm closing this bug.

**Comment by aryzach** [comment]
@wisn did you ever have any luck installing codeworld using stack? I only have stack and not cabal because my computer is old and I had a hard time trying to get cabal installed, and just got haskell working with stack. Now I want codeworld, but that sounds like it'll be a problem

**Comment by cdsmith** [comment]
There is a partial installation via stack in the Travis CI integration.  It doesn't do everything, though.

Just to make sure, the only reason you would need to install CodeWorld on your own machine is if you want to run a new server, or develop on the project.  You can use the public server at http://code.world (or http://code.world/haskell) if all you want to do is use the system.  (You shouldn't develop confidential code on the public server, but I doubt you're doing enterprisey stuff in CodeWorld anyway!)

**Comment by aryzach** [comment]
I basically want to either run locally, or host it on my static website. Is it required to do that?

**Comment by wisn** [comment]
@aryzach I had tried several times and have no luck. I gave up. It is almost three years ago and I actually forgot what am I doing.
