### ISSUE TITLE
Rename main -> program

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#474]
I would love for students to write this:

    program = drawingOf(codeWorldLogo)

instead of

    main = drawingOf(codeWorldLogo)

At first glance, it appears we could accomplish this by passing `-main-is Main.program` to GHC.  Unfortunately, changing the entry point does *not* change the choice of symbols exported from a module by default.  So doing this requires all student programs to begin with a module header, like this:

    module Main (program) where
    program = drawingOf(codeWorldLogo)

This is worse than the original.

Another possibility is to use CPP to replace "program" with "main", and then fix up error messages.

Whatever is done, this obviously breaks 100% of student code, so we'd need to make it backward compatible somehow.  CPP does that automatically, but -main-is would need preprocessing to compile either with or without that option depending on whether main occurs in the program.

**Comment by nomeata** [comment]
> Unfortunately, changing the entry point doesn't not also change the choice of symbols exported from a module by default.

I wonder if that is a bug… The report specifies `module Main(main) where` as the default header – but the report does not take into account that there might be a `-main-is` flag, and that flag could possibly change this default. But a fix in the compiler won’t help you too soon, if you want to continue using released versions, I guess.

**Comment by cdsmith** [comment]
I meant to try the CPP version at some point.  If we end up going that way, it would be good to have a long-term plan to clean up the mess.

I'll try to do this.  I've never contributed to GHC before, and this seems like a good newbie patch.  Might not be soon, though.

**Comment by cdsmith** [comment]
Filed https://ghc.haskell.org/trac/ghc/ticket/13704

**Comment by nomeata** [comment]
https://github.com/ghc-proposals/ghc-proposals/pull/53 might help

**Comment by cdsmith** [comment]
Ugh.  Looks like -XCPP fixes line numbers, but not column numbers.  So this causes error messages on the main program line to be off by 3 characters.  I guess that makes sense now that I link about it (because CPP inserts line pragmas), but it's annoying.

I think being three columns off on one line isn't awful, and it's still better to do this now than wait until we have more users.  Maybe @pranjaltale16 can incorporate a better answer into his Summer of Haskell work on fixing error messages, or maybe we can patch GHCJS to fix `main-is` earlier.

**Comment by ekarayel** [comment]
With Haskell's layout rules this can lead to very hard to debug situations. Consider the following code:
```
program = do let print = putStrLn . show
             print [1,2,3]
```

It runs fine if you set `main = program` but it breaks due to the layout rule when you `#define program main`. 

I've been working on a code base that used macros occasionally. And I hit a situation like the above several times. I was conviced the code should compile, but I got a useless syntax error. It cost me a lot of time to figure out, what was going on.

**Comment by cdsmith** [comment]
Good point!  We don't use `do` in codeworld-base, anyway.  But it's possible that uses of `let` or `where` will be broken by this.  Okay, I'll revert the CPP change, and look into locally patching GHC to fix `-main-is`.

**Comment by cdsmith** [comment]
I've re-enabled this, but with `program` expanding to `(main )` instead of `main`.  The result is that layout and column numbers work as expected, but you cannot write a type annotation for `program`.  That's too bad, but I'll live with it.  This is too transformative of a change.

Much of the motivation comes from work done over the summer testing understanding of basic concepts.  It turns out that understanding `main` as a value is hard.  It works if we adopt strict terminology, and distinguish between "the code" and "the program" (the program is the thing that runs: the actual window where things happen; and the code describes it).  But to do this, it's essential that early programs make sense as descriptions of programs.  This change accomplishes that.  So I'm willing to live with type annotations being broken from now until I can fix GHC's `-main-is` option.

(In ordinary Haskell, I'd describe `main` as being an *action*, but it turns out this is also a relic of traditional programmer thinking.  When we're doing "wholemeal" programming describing the whole drawing or animation at once, students don't naturally think of the whole program as an action.  And since `IO` types can't be decomposed, there's no need to ruin them with this kind of thinking!)

**Comment by cdsmith** [comment]
I have the proper fix in now, and it works great!  Many thanks to @nomeata for helping identify the necessary GHC changes.
