### ISSUE TITLE
KeyPress "Unknown:173" instead of KeyPress "-"

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#482]
With [this program](https://code.world/haskell#PQCGP-DEe2z_I7nYle_nnng)
```
import CodeWorld
import Data.Text (empty, pack)

main = interactionOf  empty (const id) (\e _ -> pack (show e)) text
```
and pressing `-` (the minus key) I see `KeyPress "Unknown:173"` instead of `KeyPress "-"`. But in CodeWorld, or is my browser strange?

**Comment by cdsmith** [comment]
Looks like FireFox sends a different key code for that key (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode).  I'll fix this now, and also verify the remaining keys.

**Comment by cdsmith** [comment]
Thanks for the bug report!  Fixed now.
