### ISSUE TITLE
Factoring the code in codeworld/codeworld-api/src/CodeWorld/Driver.hs

### ISSUE THREAD

**Issue by ekarayel** [google/codeworld#493]
Hi,

I noticed the two code branches in `codeworld/codeworld-api/src/CodeWorld/Driver.hs` where alot of the code is essentially identical upto the fact that in the client-side version runs in the `IO` monad while in the server-side version - the code runs in the `Canvas` monad from `Graphics.Blank`.

I'd propose defining a new Monad class instead, e.g. 

```
class (Monad m) => CanvasMonad m
    moveTo :: Point -> m ()
    lineTo :: Point -> m ()
    -- and so on ...
```
For the server side version, there would be an instance

```
instance CanvasMonad Canvas where
    moveTo = Canvas.moveTo
    lineTo = Canvas.lineTo
    -- and so on ...
```
and on the client side 
```
instance CanvasMonad IO where
    -- definition as above 
```

That would reduce the code duplication considerably.

I can send a Pull Request myself, but wanted to get an opinion first. 

What do you think?

**Comment by cdsmith** [comment]
Yes, I definitely agree with this change.  If you'd like to implement it, please go ahead.  I'll never turn down a good cleanup CL.

**Comment by cdsmith** [comment]
At this point., the core drawing code is unified.  The next step is to pull out a minimal interaction between the main event loops and things like the inspect window and game server interface, so that we can stub those out and share the main event loops, as well.  That connects this issue with #695 and #401, too.

**Comment by cdsmith** [comment]
Work on remaining parts of this is now tracked in #1009.
