### ISSUE TITLE
atan2 arguments are reversed

### ISSUE THREAD

**Issue by gladstein** [google/codeworld#494]
To get the angle for a vector (x, y) you need atan2 (y, x), not atan2 (x, y). 

Please see https://code.world/#Pbt218ETd7Of5lVmOomzHcg for a demonstration.

**Comment by cdsmith** [comment]
Hmm.  It's conventional in most other programming languages to give the arguments with y first.  e.g., see https://en.wikipedia.org/wiki/Atan2  But it's definitely confusing.  Perhaps the answer is to abandon the conventional programming-language naming, and call it something like `angleToward`, and reverse the arguments now that we're not referring to a name with its own conventions.

**Comment by cdsmith** [comment]
Another naming possibility would be to add matching functions `vectorLength` and `vectorDirection`.

**Comment by gladstein** [comment]
That would be great. A vector has a length and a direction, so the names
make good sense.
