### ISSUE TITLE
Firefox tries to run gapi.auth when it isn't set

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#51]
In Firefox, this message sometimes appears in the JavaScript console:

    TypeError: gapi.auth is undefined

This is most likely a result of a timing problem, where some call that relies on sign-in state is being made before the authentication API is completely loaded.

**Comment by mattn** [comment]
I get this on google chrome.

https://github.com/google/codeworld/blob/85007f30e1ab4ed0f08553e711efc5209c6b312d/codeworld-server/web/codeworld.js#L573

Maybe, this `:plusone` should be removed?

**Comment by cdsmith** [comment]
Fixed.  I had some broken code setting up a callback, and it was being called too early.
