### ISSUE TITLE
Recording CodeWorld program produces type error in FireFox

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#514]
FireFox shows the button to record a CodeWorld program, but trying to use it throws an exception:

    TypeError: Argument 1 of Blob.constructor can't be converted to a sequence.

on the line:

    var blob = new Blob(this.chunks);

**Comment by cdsmith** [comment]
@venkat24

**Comment by cdsmith** [comment]
There isn't a type error any more, but the save doesn't happen.  The canvasRecorder object exists, with a Blob in it, but the save doesn't work.

**Comment by nixorn** [comment]
I loaded asteroids example then recorded some gameplay and finally got Firefox save file dialog. The save works for me. Is I missed something?

**Comment by cdsmith** [comment]
Yep, it looks like this used to not work, but it does with newer versions of Firefox.  Since Firefox reliably auto-updates now, I am happy with that.  Thanks for looking!
