### ISSUE TITLE
CodeWorld editor should visually indicate layout

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#54]
The editor ought to recognize keywords that start layout, and do something to indicate the layout, and help the user understand the significance of lining things up.  Not sure what visual effect is best here.

**Comment by nixorn** [comment]
We have red error underline with message "parse error on input" where next line to the left from previous.
![image](https://user-images.githubusercontent.com/5370736/54108034-f0552c00-43eb-11e9-9f7a-58b0f8dfc282.png)
Also we have "An equation does not fit here. Is this line indented incorrectly?" where next line to the right from previous and contains "=". It is replacement from ErrorSanitizer.
![image](https://user-images.githubusercontent.com/5370736/54109203-0c0e0180-43ef-11e9-8c43-559a2c2d46a1.png)

Also compiler does not sense indents inside parentheses/squares. Should we handle this?
![image](https://user-images.githubusercontent.com/5370736/54110853-83459480-43f3-11e9-8559-349375f7de37.png)

There is two questions:
1. How to sure than particular line have incorrect indentation?
2. How to tell user what need to do?

About first. We have keywords `where`, `let in` and `do` keywords, I can show on it. Also indent can be done after `=` like this
```
a = 
  1 + 1

```
I think I should do indent map per line, just list. Fore previous snippet it like
```
[ 0  // a =
, 2  //  1 + 1
, -2 // EOF
]
```
And track where opened indent have no correspond outdent.

About second. First variant I came up - mark indents by vertical lines. It require only calculation of indent value, almost not need to parse any special cases (`where`, `do`, etc)
![image](https://user-images.githubusercontent.com/5370736/54110931-b720ba00-43f3-11e9-9595-a23afb9a27e8.png)
Another one is use to use special indent icon in left gutter.

Could be good to detect to which side user should indent/outdent, and show hint, but now i have no idea how to do this.

**Comment by cdsmith** [comment]
I don't think we should use this feature to highlight indentation inside brackets.  Those aren't significant to the language, and could be confusing for existing code.

I think this can possibly be done very neatly as follows: when syntax highlighting, keep track of layout context, and add an extra class to spans that start a new layout item.  Then use CSS to add a small bullet point to the left of these tokens.  There rest is just tweaking styles.  For instance, this might need an extra gap at the left margin so that left justified elements don't have their bullet point run off the edge of the editor.

**Comment by cdsmith** [comment]
To be more specific, the layout rules themselves are defined at https://www.haskell.org/onlinereport/haskell2010/haskellch10.html#x17-17800010.3

Here's how I'd see an algorithm working.  In codeworld-mode.js, you'd add these fields to the state object:

1. A layout "scan state", which can be any of:
1a. START. This is the starting state.  If the next non-comment non-whitespace token is `module` or `{`, then this acts like NORMAL.  Otherwise, it acts like "triggered".
1b. NORMAL: there's no new layout being added.
1c. TRIGGERED: you've encountered a layout-introducing keyword: `of`, `let`, `where`, `do`, or `\case`.  The next non-comment or non-whitespace character will introduce a new layout level (either its column number, or 0 if the token is `{`).
1d. LAMBDA: you've encoutered a `\`.  If the next non-comment non-whitespace token is a `case`, then you'll go to "triggered".  Otherwise, this acts like NORMAL.
2. The stack of layout contexts, which are integers as described in that section, and are the second parameter to the `L` function defined there.

Any time you encounter a token, you'd partially evaluate the `L` function to see what it does to the layout contexts.  When in a situation where the first section specifies an `{n}` or `<n>` token is inserted, then you'd update for that, as well.

There are some hard cases in those rules.  There's one case (note 3) that specifies a parse error, but I think you should instead just ignore the token if there are no 0s in the layout context stack, or else truncate to the last 0.  The harder one is note 5, which is going to be a pain.  I'd suggest you start by not implementing it at all, and then we'll probably have to work around some cases.

The `L` algorithm inserts new tokens into the stream.  You don't actually want to do that... you just want to keep track of any time that a `{` or `;` is inserted, and instead add a bullet point to the token it was inserted before.

Does that make sense?

**Comment by cdsmith** [comment]
Regarding note 5, I think the most important case is `let x = 5 in x^2`, which can be handled by just adding a rule that we will end the layout context if there are more `in` keywords than `let` keywords in the statement so far.  There may be some more ad-hoc rules that can be thrown in like that.

**Comment by cdsmith** [comment]
@marcianx was nice enough to figure out the CSS to prefix a token with a bullet point.

    span.cm-layout {
      position: relative;
    }
    span.cm-layout:before {
      content: "»";
      position: absolute;
      left: -6px;
      top: 0;
      color: brown;
    }

With that, it's just a matter of adding the "layout" style to the codeworld-mode.  According to https://codemirror.net/doc/manual.html#modeapi:

> Multiple styles can be returned (separated by spaces), for example "string error"

So it should be enough to append " layout" to the return value of the mode tokenizer when a new layout item is present.

**Comment by cdsmith** [comment]
You might also want this:

    .CodeMirror pre.CodeMirror-line {
      padding-left: 1em;
    }

**Comment by marcianx** [comment]
For a fine size agnostic solution, you might want to use `em` instead of `px`.

**Comment by cdsmith** [comment]
Good point.  Edited.

**Comment by cdsmith** [comment]
One more point.  There's already a stack of bracket types in the tokenizer state.  It occurs to me that a layout context with position 0 is really the same thing as a `{` style bracket, and also that it doesn't make any sense to start a new statement/declaration of a layout block without also closing all of the bracket pairs inside of the previous one.

That suggests that instead of one stack of brackets and a separate stack of layout contexts, what we really want is a single stack containing *both* explicit brackets (including `{` style) and implicit layout contexts.

**Comment by cdsmith** [comment]
Sample code with the styles above:

![image](https://user-images.githubusercontent.com/544744/54168931-27a4f680-4447-11e9-8e9a-962c1e12c8d6.png)

**Comment by nixorn** [comment]
I definitely could not correctly implement this without these comments. Thanks a lot!

**Comment by nixorn** [comment]
Test programm for this issue https://gist.github.com/nixorn/5c9d603d54b3729ec829b94f4fd6801e
