### ISSUE TITLE
codeworld-compiler tests fail

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#541]
@pranjaltale16 

Unfortunately, these only run when someone runs the script by hand.  I fixed the test runner script, but the tests are failing.  From a quick glance, some of the problems seem to be due to unicode characters, but there are other failures, too.

**Comment by pranjaltale16** [comment]
The main issue is with unicode only.
For ex, In first case:
```
### Failure in: 0:test_variableName        
test/Main.hs:69
test_variableName
expected: "\nprogram.hs:1:18: error:\n    \8226 Variable not in scope: circl :: Picture\n    \8226 Perhaps you meant one of these:\n        circ (line 2), circle (defined in the standard library)\n"
 but got: "\nprogram.hs:1:18: error:\n    \\8226 Variable not in scope: circl :: Picture\n    \\8226 Perhaps you meant one of these:\n        circ (line 2), circle (defined in the standard library)\n"
```

Also, some of the messages will also change once we integrate haskell-src-exts, I think, it is better to update messages once we integrate it.
