### ISSUE TITLE
Broken formatting in guide

### ISSUE THREAD

**Issue by ekenberg** [google/codeworld#543]
This section under "Top Down Animation" in the guide is presumably supposed to be a table but is displayed as a long string of text:

| Expression | Type | Meaning | | ------------------- | ------------------- | ------------------------------------------------ | | t | Number | An instant in time. | | ball | Number -> Picture | The entire animation. | | ball(t) | Picture | The single frame of ball at some point in time | | thickCircle(t, 1) | Picture | The meaning is identical to ball(t) |

Is there a `<pre></pre>` missing?

**Comment by cdsmith** [comment]
Thanks for the report.  Looks like github's markdown has a table syntax, but pagedown (used on the CodeWorld site) doesn't implement it.  I'll clean that up tonight.
