### ISSUE TITLE
Use `postMessage` to communicate between iframe and IDE

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#552]
In my CIS164 course notes, I am using iframes to embed CodeWorld programs in HTML pages: http://cis.upenn.edu/~cis194/fall16/lectures/01-intro.html

This broke recently, presumably because the iframe tries to send error messages to the outer page, which fails if they are not from the same domain. I now get an error in my browser console, and that seems to abort the CodeWorld program.

The “proper” solution to do this these days seems to be using `Window.postMessage` as documented here https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage. This is the “right” way of doing it, and would fail gracefully (I believe) if the outer window does not support receiving these messages.

**Comment by cdsmith** [comment]
Thanks for the report, and sorry for the delay in fixing.  It's fixed now.

**Comment by nomeata** [comment]
Yay! I don’t consider this a delay :-)
