### ISSUE TITLE
Remove rarely used corners of codeworld-base

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#554]
A lot of symbols in codeworld-base are only there because they are analogues of stuff from Haskell's base library.  Now that code.world/haskell is a first-class thing and Haskell fans can just use it, we should consider removing the lesser-used corners of codeworld-base.  This will make it much easier to browse the available functions in autocomplete, and less likely that something will accidentally match.

Here's the "suspicious" list from my first pass through:

* `(.)` is far less useful given lack of currying and lower use of higher-order programming.  It also has the disadvantage of creating confusing errors when it's used accidentally.
* `Maybe` as a type, along with `Just`, `Nothing`, `definitely` (aka `fromJust` in Haskell), `hasValue`, and `withDefault` are hardly used.  It's telling that nothing else in the standard library uses `Maybe` at all.
* `reciprocal` is always written as `1/x` or `x^(-1)` in math, and `opposite` is always written as `-x`.
* Some advanced math functions, like `acos`, `asin`, `asin`.  (`atan2` will stick around as `vectorDirection`) might not be needed, but this is a low priority since they are legitimate math syntax.
* `combined`, uses of which can be rewritten using explicit recursion.  Having only this one fold doesn't make much sense.
* `id` doesn't seem to be useful given the rarity of higher-order programming.

Obviously, this is a breaking change, so it involves deprecating, hiding from autocomplete, and removing in a year or so.

**Comment by thSoft** [comment]
IMHO it would be great to keep some kind of fold/reduce.

**Comment by cdsmith** [comment]
@thSoft Are you using `combined` in codeworld-base today?
