### ISSUE TITLE
Internal server error trying to run a program with run.html

### ISSUE THREAD

**Issue by pvdbrand** [google/codeworld#567]
One of my students wanted to put his program on his website. I showed him that he could construct a link as follows: https://code.world/run.html?mode=codeworld&dhash=hash you get when you use the Share button.

I tried it for several programs, and it always seemed to work. However, for this student's particular program it did not work. This is the link: https://code.world/run.html?mode=codeworld&dhash=Pz45bfGDRsgOY3WodG0hRVQ

In the browser developer tools I see that runJS returns an internal server error. However, the program compiles and runs just fine in the CodeWorld environment.

On a related note, is there an easier way to create a link to a game that does not involve manually constructing the URL?

Thanks!

**Comment by cdsmith** [comment]
The URL you gave is incorrect.  A dhash should always begin with D, not P.  Only source hashes start with P.  I don't see how this could have happened, so I suspect that the student tried to do surgery on the URL manually, and inserted a dhash where a source hash belongs.

That is a valid source hash, you can see the program at http://code.world#Pz45bfGDRsgOY3WodG0hRVQ -- but the correct dhash link is https://code.world/run.html?mode=codeworld&dhash=DTUdJUgaUQMWK__mXTzzGkw

If you have evidence that the URL you have came from the CodeWorld server, please reopen.  I just don't see how that's possible at the moment.
