### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by alphalambda** [google/codeworld#576]
A fresh install failed at this point:
<pre>
src/HIndent/Pretty.hs:876:19: error:
    • The constructor ‘Deriving’ should have 3 arguments, but has been given 2
    • In the pattern: Deriving _ heads
      In an equation for ‘prettyInternal’:
          prettyInternal (Deriving _ heads)
            = depend (write "deriving" >> space)
              $ do { let heads' = ...;
                     maybeDerives <- fitsOnOneLine
                                     $ parens (commas (map pretty heads'));
                     case maybeDerives of {
                       Nothing -> formatMultiLine heads'
                       Just derives -> put derives } }
            where
                stripParens (IParen _ iRule) = stripParens iRule
                stripParens x = x
                formatMultiLine derives
                  = do { depend (write "( ")
                         $ prefixedLined ", " (map pretty derives);
                         .... }
      In the instance declaration for ‘Pretty Deriving’

src/HIndent/Pretty.hs:1599:46: error:
    • Couldn't match expected type ‘QName NodeInfo’
                  with actual type ‘MaybePromotedName NodeInfo’
    • In the first argument of ‘prettyInfixOp’, namely ‘op’
      In a stmt of a 'do' block: prettyInfixOp op
      In the first argument of ‘depend’, namely
        ‘(do { prettyInfixOp op;
               space })’

src/HIndent/Pretty.hs:1714:10: error:
    • Couldn't match expected type ‘[Deriving NodeInfo]’
                  with actual type ‘Maybe t1’
    • In the pattern: Nothing
      In a case alternative: Nothing -> return ()
      In a stmt of a 'do' block:
        case mderivs of {
          Nothing -> return ()
          Just derivs -> space >> pretty derivs }

src/HIndent/Pretty.hs:1715:10: error:
    • Couldn't match expected type ‘[Deriving NodeInfo]’
                  with actual type ‘Maybe (ast1 NodeInfo)’
    • In the pattern: Just derivs
      In a case alternative: Just derivs -> space >> pretty derivs
      In a stmt of a 'do' block:
        case mderivs of {
          Nothing -> return ()
          Just derivs -> space >> pretty derivs }
cabal: Leaving directory '/tmp/cabal-tmp-18720/hindent-5.2.2'
Installed Cabal-2.0.1.1
cabal: Error: some packages failed to install:
codeworld-compiler-0.1.0.0-1ERDBePgTpqG87HXOkUJsw depends on
codeworld-compiler-0.1.0.0 which failed to install.
codeworld-server-0.1-HSHnfhSCzxUGaQc4CCcwA5 depends on codeworld-server-0.1
which failed to install.
hindent-5.2.2-57yMcJoxD67AAtJqSanDI failed during the building phase. The
exception was:
ExitFailure 1
============================
= Aborting: Command failed =
============================
</pre>

**Comment by cdsmith** [comment]
Okay, it looks like hindent is broken.  hindent doesn't declare an upper bound on its dependency for haskell-src-exts, and on Dec 11, a new haskell-src-exts was uploaded that added this constructor param.  So hindent won't build against the latest haskell-src-exts.
