### ISSUE TITLE
Company firewall blocking multipart/form-data requests

### ISSUE THREAD

**Issue by glaukon-ariston** [google/codeworld#586]
When I try running an example I get this. Any chance of not using "multipart/form-data" to POST data? I had a quick look at the source and "multipart/form-data" comes from the use of XMLHttpRequest/FormData combination. Would it be technically possible to use "application/x-www-form-urlencoded" media type instead? 

Ta,
Glaukon

```
POST https://code.world/compile 403 (MediaTypeBlocked)
codeworld_shared.js:39
  | sendHttp | @ | codeworld_shared.js:39
  | compile | @ | codeworld.js:750
  | onclick | @ | (index):102
 
File Blocked
McAfee Web Gateway has blocked the file, because the detected media type (see below) is not allowed.
URL: 
Filename: 
Media Type (detected): multipart/form-data
Media Type (from file name): 

Company Acceptable Use Policy
For assistance, please contact Helpdesk.

generated 2018-01-23 10:43:01 by McAfee Web Gateway 
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
```

**Comment by cdsmith** [comment]
Thanks for the report!  Unfortunately, application/x-www-form-urlencoded encodes the form data into the URL, and URLs have a maximum length (around 2K) that is already exceeded by lots of code that people build with CodeWorld.

One could imagine insane workarounds, like making multiple requests to accumulate the file.  However, I believe it's the wrong thing to do.  Not only is it technically complex, but it also appears CodeWorld would be circumventing a policy set on your firewall.  In the end, you *are* uploading the source file, and if your network administrator doesn't want you uploading files, then they are objecting to that behavior.  Of course that's dumb; but it's also a decision they made.  I don't want to take lightly the possibility that CodeWorld would be circumventing your network policy.

**Comment by cdsmith** [comment]
I'm going to close this.  It's unfortunate, but it seems to be an overly restrictive corporate network policy, and working around it on the CodeWorld side is probably the wrong answer.
