### ISSUE TITLE
What are the integer arguments in "collaborationOf"

### ISSUE THREAD

**Issue by ChristopherKing42** [google/codeworld#591]
The function [`collaborationOf`](https://hackage.haskell.org/package/codeworld-api-0.2.1.0/docs/CodeWorld.html#v:collaborationOf) takes arguments of the form

- StaticPtr (Int -> Event -> world -> world)
- StaticPtr (Int -> world -> Picture)

The meaning of the `Int` arguments in those arguments is undocumented. What do they mean?

**Comment by cdsmith** [comment]
They are player numbers.  In `codeworld-api`, the first player is player 0, then player 1, and so on.
