### ISSUE TITLE
translated not working properly for circles - blank-canvas

### ISSUE THREAD

**Issue by schteeben95** [google/codeworld#594]
Just found another issue:
`drawingOf $ translated 3 5 $ rectangle 0.2 0.2 & circle 0.2`
Doesn't work properly when running locally. 

c2934c2 is also the culprit.

**Comment by cdsmith** [comment]
Thanks again.  Transformations were being applied twice to arcs and circles!  This time I tried a few examples to satisfy myself that there are no more obvious bugs, at least.  Will release a new version to hackage now.

**Comment by cdsmith** [comment]
Done

**Comment by schteeben95** [comment]
Thank you kindly sir.
