### ISSUE TITLE
It would be nice to have a favicon.ico!

### ISSUE THREAD

**Issue by rcook** [google/codeworld#613]
It's a little thing, but it would be nice. I have no artistic talents unfortunately, but I know where the file should go!

**Comment by kammitama5** [comment]
that is a really great idea! Not sure what Chris would agree on, but even the logo would be really cool!

**Comment by cdsmith** [comment]
I put something there, based on a redesign that's already in progress.  It's better than the blank-page icon, but I'll do better soon.

**Comment by cdsmith** [comment]
I've now got a decent image in each of three sizes.  The black isn't terribly colorful, but lighter shades don't turn out well at all.  I think I'll stop here.
