### ISSUE TITLE
change Polygon to solidPolygon in CallStack

### ISSUE THREAD

**Issue by kammitama5** [google/codeworld#614]
Is this a good place to start? This is from Driver.hs Line 569.
Should I start changing this to solidPolygon? Just checking before I get started. Thank you!
https://github.com/google/codeworld/blob/master/codeworld-api/src/CodeWorld/Driver.hs

![poly](https://user-images.githubusercontent.com/8516378/39602475-1f94edbe-4eda-11e8-8f8f-ea9b1fd22843.png)

(also have to remember to turn on non-exhaustive pattern warning)

**Comment by Gabriel439** [comment]
Yeah, that's a good place to start.  The goal of this exercise is mainly to get the hang of making a disruptive change and fixing all the compile errors that arise

**Comment by kammitama5** [comment]
so I set -Wall in ghc options, and changed the line to solidPolygon but all it does is say ```Parse error in pattern:solidPolygon``` and then leave the directory. I made a separate branch called testbranch to commit my code for this. How do I best troubleshoot how to go from there to implement it throughout the code base?

**Comment by cdsmith** [comment]
I'm glad to hear that -Wall doesn't add warnings!

The idea behind making the type change was to first add a new constructor to the type, and then update the code to follow.  In codeworld-api/src/CodeWorld/Picture.hs, you'll find the definition of `Picture`.  What we talked about doing was adding a `SolidPolygon` constructor there.  (Note the capitalization: constructors have to be capitalized.)  If things are set up right, you'll get a bunch of warnings about incomplete pattern matches, mostly in Driver.hs, and you'll want to find and update them all.  To test, you can change the existing `solidPolygon` function (in Picture.hs) to use your new constructor, and check that you can still draw a solid polygon.

In the end state, here, the constructors for `Picture` will resemble the functions that build pictures.  So there will be constructors called `Circle`, `SolidCircle`, `ThickCircle`, etc., which match up with the (already existing) functions called `circle`, `solidCircle`, `thickCircle`, etc.  Only functions are exported, which keeps the `Picture` type suitably abstract and hides stuff like the CallStack fields; but the constructors mirror the functions.

**Comment by kammitama5** [comment]
Oh. A new one. Okey doke. Thanks. This is helpful.

**Comment by kammitama5** [comment]
I modified ```Picture.hs```,
adding the Data constructor SolidPolygon
![screenshot_2018-05-07_13-55-42](https://user-images.githubusercontent.com/8516378/39719600-92ef2efc-51ee-11e8-9951-3538fc108eb6.png)
and changing the function to include SolidPolygon
![screenshot_2018-05-07_13-55-20](https://user-images.githubusercontent.com/8516378/39719617-9b78da1e-51ee-11e8-8224-e82e2d0ec4db.png)
However, when I used ```./build.sh``` I get no errors in ```Driver.hs```
![screenshot_2018-05-07_13-53-50](https://user-images.githubusercontent.com/8516378/39719657-b5ed68e2-51ee-11e8-86df-551f87a7af1d.png)

**Comment by cdsmith** [comment]
Okay, that's a start!  The hope was that you'd now see warnings about incomplete patterns, when you build with this change.  If there are already lots of warnings, they may be getting lost in the noise.

By the way, if you JUST want to rebuild codeworld-api, you can run:

    (. base.sh && cabal_install --ghcjs ./codeworld-api)

That should be faster and less noisy than running the entire build script.

**Comment by cdsmith** [comment]
Actually, you want something more like this:

    bash
    . base.sh
    cd codeworld-api
    cabal clean
    cabal build --ghcjs

**Comment by kammitama5** [comment]
I ran the above command and after cd-ing into ```codeworld-api``` and running ```cabal clean``` and ```cabal build --ghcjs```, cabal tells me that the command is ambiguous.

![screenshot_2018-05-09_01-55-50](https://user-images.githubusercontent.com/8516378/39800447-9705b40a-531c-11e8-8dd2-a5e153ae7f99.png)

I also added ```-fwarn-incomplete-patterns``` and ```-Werror``` and expected a list of errors related
to Driver.hs.

![screenshot_2018-05-09_02-00-38](https://user-images.githubusercontent.com/8516378/39800485-c7c0bf72-531c-11e8-84fc-b2fdabefbe8c.png)

Instead, I got a list of warnings relating to Event.hs and a lack of documentation
for certain modules, and ```codeworld-api``` was aborted.

![screenshot_2018-05-09_02-00-02](https://user-images.githubusercontent.com/8516378/39800530-f47ff686-531c-11e8-821e-10db7f7acba4.png)

**Comment by Gabriel439** [comment]
@kammitama5: There are some warnings that are on by default even if you don't explicitly enable them, so `-Werror` is failing on those warnings

Probably the most straightforward way to go about this is to first turn on `-Werror` and fix all the warnings that you see (creating a pull request for each logical set of fixes) and then once the project is "`-Werror`-clean" then you can turn on `-fwarn-incomplete-patterns` and start fixing those warnings

**Comment by kammitama5** [comment]
thanks! Okey doke. Will do.

**Comment by kammitama5** [comment]
I disabled the ```f-warn...``` and just ran ```-Werror``` and got this, so will poke around and see if I can solve this over the next couple days.
![screenshot_2018-05-11_20-57-59](https://user-images.githubusercontent.com/8516378/39952539-c552d88c-554d-11e8-9a01-3cf17ccf183d.png)

**Comment by kammitama5** [comment]
I added SolidPolygon and just have some non-exhaustive pattern matching errors. I'll work on these and make a pull request. 

![screenshot_2018-05-15_11-10-40](https://user-images.githubusercontent.com/8516378/40069503-686ace10-5820-11e8-8606-0a541404fea0.png)

**Comment by kammitama5** [comment]
I got it to type-check but I could be wrong ¯\_(ツ)_/¯

**Comment by Gabriel439** [comment]
Yeah, this is exactly what should be happening!

If everything type checks and doesn't emit warnings then you should open a pull request :)

The goal is to keep making larger and larger changes, confident in the knowledge that if the compiler doesn't find any issues that your code works

**Comment by kammitama5** [comment]
okey doke. I submitted the pull request :D

**Comment by kammitama5** [comment]
I deleted Polygon and made sure SolidPolygon type-checked. I also changed the ```init solidpolygon``` to camelcase. I've submitted a pull request.

**Comment by cdsmith** [comment]
Nice!  Merged.  Do you have a direction to go next?  I left a comment on the last pull request with a suggested goal that's a little further out.  Let me know if you need to chat in more detail, and I'll make time for it.

Closing this issue, since it's done.

**Comment by kammitama5** [comment]
Thank you! :D I don't really, and am open to suggestions!

**Comment by cdsmith** [comment]
Currently, this `SolidPolygon` constructor is used for two different shapes: `solidPolygon` and `solidClosedCurve`, depending on the boolean parameter.  How about splitting out a new `SolidClosedCurve` as a separate constructor?

**Comment by kammitama5** [comment]
sounds good. I'll work on that! Thank you.
