### ISSUE TITLE
Split Path Constuctor Into variants 

### ISSUE THREAD

**Issue by kammitama5** [google/codeworld#629]
```
 Split the Path constructor into its eight variants 
(which will yield Polygon, ThickPolygon, ClosedCurve, 
ThickClosedCurve, Polyline, ThickPolyline,
 Curve, and ThickCurve).

```

**Comment by cdsmith** [comment]
Looks like this is done.  If you're familiar enough, it might be okay to just take on the rest all at once.  Otherwise, we can look them over and plan a few more specific constructors to try.

**Comment by kammitama5** [comment]
Up to the task with either approach.
