### ISSUE TITLE
Split Circle Constructor into Circle, SolidCircle, ThickCircle

### ISSUE THREAD

**Issue by kammitama5** [google/codeworld#634]

**Comment by cdsmith** [comment]
There's actually no `Circle` constructor.  Currently, `solidCircle` turns into `Sector`, and `thickCircle` and `circle` turn into `thickArc` and `arc`

**Comment by kammitama5** [comment]
Ah. I'm probably going to tackle the text stylized and other text next. Circle sounds "involved"

**Comment by kammitama5** [comment]
Yeah...this is the one I'm working on at the moment

**Comment by cdsmith** [comment]
Yeah, I thought the plan was to make `Picture` mirror the public API.  So the arguments to each constructor are one CallStack, plus the arguments to the public API function.  Is that your plan?

**Comment by kammitama5** [comment]
I believe so...I'm juuuust understanding what you're telling me...but flailing.
