### ISSUE TITLE
A correct long program fails to compile

### ISSUE THREAD

**Issue by fernando-alegre** [google/codeworld#645]
A student submitted this program:
https://code.world/#PFbdxW4T-gqKLbuYoIlX7Nw

The compiler times out with this message:
Sorry!  Your program couldn't be run right now.  Please try again.

There are two problems with this:

1) The message encourages the student to keep trying, which will increase the load in the server and fail every time.
2) If we increase the timeout to 95 seconds, the program can actually run, as this link (in a server modified with a 95-second timeout) shows:
http://dirtyrice.phys.lsu.edu:8080/#PTokN6HJw4KUy6F82nWu3iQ

Maybe after a compile times out, a second compile could be tried without -O2.
For example, in this case, compilation time goes down from 50 seconds to 16 seconds:

codeworld8@dirtyrice:~/test$ time ghcjs -DGHCJS_BROWSER -dedupe -hide-package base -package codeworld-base -XOverloadedStrings -XPackageImports -XRebindableSyntax -XImplicitPrelude PTokN6HJw4KUy6F82nWu3iQ.hs 
[1 of 1] Compiling Main             ( PTokN6HJw4KUy6F82nWu3iQ.hs, PTokN6HJw4KUy6F82nWu3iQ.js_o )

Linking PTokN6HJw4KUy6F82nWu3iQ.jsexe (Main)

real    0m15.557s
user    0m15.146s
sys     0m0.400s

**Comment by cdsmith** [comment]
I like your suggestion to retry compiles that time out without -O2.  I've run into this before, where GHC has terrible performance optimizing occasional programs with a lot of pattern matching.

**Comment by cdsmith** [comment]
See #413 for a previous incarnation of this.  Would be nice if someone has cycles to poke at the underlying GHC behavior.
