### ISSUE TITLE
Switch to GHCJS 8.6

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#655]
It looks like we're at the inflection point where 8.2 (or even 8.4?) is more reliable than 8.0.  It would be a good idea to switch over later on this summer, before the new school term starts.

This means verifying that we don't get regressions in error messages.

**Comment by cdsmith** [comment]
It looks like we'll want to wait on ghcjs/ghcjs#654 and ghcjs/ghcjs#666 to be fixed before updating.

**Comment by cdsmith** [comment]
Worked on this a couple weekends ago at the Atlanta haskathon.  The tricky part at the moment is that GHCJS 8.6 installation instructions seem to be written with cabal new-build.  I'm not knowledgable enough about cabal to know to make that work.

My general requirements are:

1. I need to install the base libraries into a common package db that I can refer to when invoking ghcjs manually.
2. I'd prefer to install everything into a CodeWorld-specific directory rather than putting stuff in the user's home directory.  But I'm willing to let this one go if it makes things too much easier.

Unfortunately, cabal new-build seems to have inherited a lot of stack's opinions about how it should set things up to make it work for other use cases, and I can no longer figure out how to install ghcjs with a package db in a specific location.  (I used to just set a `PREFIX=foo` env variable when installing GHC and GHCJS, and then install stuff with `cabal install --global --prefix=ff`.  This no longer seems to work since GHCJS install assumes the new way.)

**Comment by cdsmith** [comment]
@luite I'm a bit lost with everything here.  Any advice?  I'll try again this weekend, because this needs to get done before GSoC students can make much progress.

**Comment by peterbecich** [comment]
@cdsmith , I've had some success in building CodeWorld with Stack and GHCJS 8.0: https://github.com/peterbecich/codeworld/tree/stack-yaml  There is not yet a release for 8.2 or higher: https://github.com/matchwood/ghcjs-stack-dist/issues/10#issuecomment-492663413

If there were a release on `matchwood/ghcjs-stack-dist` for 8.6, it is possible that using this would be easier than installing GHCJS 8.6 otherwise?

**Comment by cdsmith** [comment]
I don't think a pre-build GHCJS would do any good.  Ever since 8.2, GHCJS builds its own version of the GHC API.  That means that where CodeWorld used to need a patched GHC, it now needs a patched GHCJS instead.

I have the patch ported over now, and GHCJS is building just fine.  I'm just running into an installation issue.  Running `cabal new-install` with GHCJS 8.6 seems to put broken symlinks into the path.  As soon as I get this fixed, I hope to be able to boot GHCJS.  Then it's just a matter of fixing a few known issues, such as regex patterns changing to match new error messages, etc.

**Comment by cdsmith** [comment]
Fixed by #958
