### ISSUE TITLE
failed to build / Build error

### ISSUE THREAD

**Issue by kammitama5** [google/codeworld#659]
I tried to build tonight and got this error. I was in root and ran ```./build.sh```. This was from my most recent pull from upstream master. Retried and got same error.

```
cabal: Error: some packages failed to install:
HsOpenSSL-0.11.4.14-2XIC8DvyHUZ5Zbuvkze1rn failed during the configure step.
The exception was:
ExitFailure 1
codeworld-auth-0.1-6c6jruZpP75BPJGdSk9T7n depends on codeworld-auth-0.1 which
failed to install.
codeworld-server-0.1-HSHnfhSCzxUGaQc4CCcwA5 depends on codeworld-server-0.1
which failed to install.
jwt-0.8.0-61C4i68iVKmK8XsgQkW0dY depends on jwt-0.8.0 which failed to install.
============================
= Aborting: Command failed =
============================
```

**Comment by cdsmith** [comment]
Yep, this was a pull request I merged from @rcook.  You will need to install the OpenSSL development libraries.  The pull request already added this to the `install.sh` script, but since you ran that before it was merged, you missed the install for this library.

**Comment by rcook** [comment]
@kammitama5 : Yes, you'll need to run one of the following:

Centos etc.:
```
sudo yum install -y openssl-devel
```

Ubuntu etc.:
```
sudo apt-get install -y libssl-dev
```

Zypper:
```
sudo zypper -n install libopenssl-devel
```

Homebrew
```
brew install openssl
```

Hope that helps!

**Comment by kammitama5** [comment]
awesome. Thank you!
