### ISSUE TITLE
Testing, optimization, better organization for JavaScript code

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#66]
The JavaScript code is a mess!  We need to:
1. Break it up into better-organized pieces with documentation and clean APIs.
2. Add unit testing (using node.js?) whenever possible.
3. Compile and minify with closure to serve nicely optimized code on the live site.  Preferably, keep an out to run in dev mode with unoptimized JavaScript for debugging.

**Comment by cdsmith** [comment]
I'm becoming convinced that what I want to do here is actually generate the client-side JavaScript using GHCJS.  This has advantages in that: (a) most potential contributors are coming from the Haskell world anyway, and (b) some desired changes would be much easier with libraries like haskell-src-exts.

So step 1 here would be to take the existing `web/codeworld.js`, and turn it into a GHCJS-based package, `codeworld-client`, and modify the build script to run GHCJS and generate it at build time.  A first pass could just copy the existing JavaScript into a `jsbits` directory with a thin wrapper, and then I could migrate parts to real Haskell code.

**Comment by cdsmith** [comment]
Relevant to this:  CodeMirror has discontinued their minimizer as-a-service.  That means that in order to continue updating CodeMirror to the latest version, we're going to need to rebuild it at build/install time, most likely using something like uglify (which is what the previous minimizer was doing).  As long as we're doing that, it's not hard to imagine also applying the same infrastructure to CodeWorld's internal JavaScript.  For debugging purposes, we'd still want the source files to be accessible in web/js, so uglify can build source maps.

**Comment by denim2x** [comment]
Hi - may I lend a hand?

**Comment by cdsmith** [comment]
That would be great!

You can see how we use uglify for CodeMirror at the end of the install script.  https://github.com/google/codeworld/blob/master/install.sh#L170  My random thoughts are that we could definitely move that into the build script instead, then refactor the existing monolithic JavaScript bits (in web/js) into more modular form, and incorporate them into the same JavaScript bundle.

If it's easy, it would be great to also preserve a debug mode that loads the source JavaScript (even if its distributed around 50 different files, or whatever!), so that it's still possible to debug with browser developer tools.

Please feel free to ask questions, and I'll keep up as well as I can.  I'm a bit overwhelmed at the moment, but I will do everything I can to help.

**Comment by denim2x** [comment]
What's your opinion about [Ace](https://ace.c9.io)?

**Comment by cdsmith** [comment]
I don't have a strong opinion, nor enough knowledge to have an opinion, about Ace vs. CodeMirror as editors.  If we switch, there will be a bit of work matching the features of the current CodeMirror based editor.  CodeWorld currently has custom code for syntax highlighting, rainbow brackets, autocomplete, bracket-matching, and integration with debugging and error messages, and a lot of careful tuning of the styles, and all of that would need to be repeated for the new editor.  But if the advantages outweigh the need to repeat that work, then I can see swapping.

**Comment by cdsmith** [comment]
As long as I'm listing integrations, I should mention undo history.  This is a tricky one: all currently saved projects contain an undo history in CodeMirror's format.  Swapping to a different editor would mean either throwing away everyone's undo history for saved projects, or writing a one-off converter.

**Comment by cdsmith** [comment]
Closing this in favor of the three more specific cleanup issues I just filed.
