### ISSUE TITLE
New Inspect dialog sometimes prints extremely long numbers

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#668]
![image](https://user-images.githubusercontent.com/544744/41661647-2e2a16e8-746d-11e8-9e8a-fe1cfa6e1ef9.png)

The intent was to limit these numbers to some reasonable length.

@kammitama5

**Comment by kammitama5** [comment]
Would you prefer to two 2dp or 4dp? I had set the radians/ angles to 2dp but wasn't sure if you'd prefer 2dp or 4dp for the other arguments.

**Comment by kammitama5** [comment]
Okey doke. I might need some help with this.

**Comment by Gabriel439** [comment]
@kammitama5: I think the first step is factoring out the logic from the `Show` instance for `Number` into a reusable top-level function, like this:

```haskell
instance Show Number where
    show = showNumber

showNumber :: Number -> String
showNumber ...
```
