### ISSUE TITLE
Animation tool : Slow motion speed slider

### ISSUE THREAD

**Issue by kammitama5** [google/codeworld#676]
@kammitama is working on this

**Comment by kammitama5** [comment]
note: in step function, throw something that checks to see if time is negative and if so, set to 0 and set playback speed to zero. (6/25)

**Comment by kammitama5** [comment]
Should I close this? I opened a new issue for making the slider draggable, and one for text on the slider.

**Comment by cdsmith** [comment]
I don't think there was a need to open two new issues.  Let's close those and keep working in this one.  It's okay for a single issue to track more than one commit or pull request.

**Comment by cdsmith** [comment]
I put together this example with everything we talked about last time.  It might be helpful to you to look over and understand.

https://code.world/haskell#PB9L3b5zEcIW2XNefV8mchA

**Comment by kammitama5** [comment]
It makes sense, but I'm having a bit of an issue trying to see how to relate it to the existing codebase (or should I be thinking of it as an extension of the existing codebase ie making new functions for the slider?). My thought was that the label for the slider was something that could be added given existing code in the ```drawControl``` function that needs to be added to the ```SpeedSlider drawControl function``` but that something in ```TimeLabel``` could help me to draw the label for ```SpeedSlider```.

**Comment by kammitama5** [comment]
The functions you created in your example above (particularly in the final ```picture``` function seem to correspond to the ```TimeLabel``` line ```(scaled 0.5 0.5 $ text (pack (showFFloatAlt (Just 4) (state w) "s"))) <>``` (line 2347). Where state is ```w``` and ```lettering``` in your example is ```scaled text``` (I do have the dimensions written down for what was spoken about during the meeting). Is this along the line of thought I should be using? Thanks.

**Comment by cdsmith** [comment]
Yes, I believe the change function in my code corresponds to a function called handleControl, and the picture function corresponds to drawControl.  But that's from memory.  If it doesn't make sense, I'll look again tonight

**Comment by kammitama5** [comment]
Thanks. I'm also trying to use a bit of what I have with the example you gave me, and I keep running into an error asking for ```RealFloat a``` instance rather than ```ShowFFloatAlt```. Is there also a difference between ```text``` and ```lettering```? I played around with your example a bit (which is clear and makes sense), which has helped me understand a lot better what I need to do, but I also have a bit of uncertainty (okay, a lot) about how to put it all together. That's what I'm struggling with.

**Comment by cdsmith** [comment]
There is no difference between `text` and `lettering`.  You can verify at https://github.com/google/codeworld/blob/master/codeworld-api/src/CodeWorld/Picture.hs#L277 that their definitions are exactly the same.  I am in the process of changing the function from `text` to `lettering`, because the name `text` was confusing to a lot of students.

I'll try to answer other questions in the pull request.

**Comment by cdsmith** [comment]
@kammitama5 finished this one some time ago.  Closing the issue to reflect that.
