### ISSUE TITLE
Codeworld screen size should be resizable

### ISSUE THREAD

**Issue by kammitama5** [google/codeworld#689]
The current screen size is 500x500 pixels, and on smaller screens this renders the window too large and the debug controls unreachable for the user.

![small_screen](https://user-images.githubusercontent.com/8516378/42643578-5334aa5a-85ae-11e8-9f85-e75f83472ffd.png)

**Comment by cdsmith** [comment]
The easiest way to do this would be to make the divider draggable.  It's set as non-resizable at https://github.com/google/codeworld/blob/master/web/env.html#L125

Then we'd need to add an event handler for the resize, which would change the iframe height to keep it square.  The run.html, inside the iframe, already resizes the canvas to the largest square that fits within the parent window, so resizing the iframe would be good enough.

**Comment by cdsmith** [comment]
(I'm not 100% sure there isn't a clever way to make the iframe square using CSS.  That would be even better!)
