### ISSUE TITLE
The code.world site became unusable in at least some browsers

### ISSUE THREAD

**Issue by fernando-alegre** [google/codeworld#693]
The code.world site cannot be used anymore in browsers in which it worked perfectly before. In particular, I am using Firefox 52.7.2 (64-bit) in Linux, and I receive a message saying "A script is slowing down the browser. Wait or Stop?" If I choose Wait, I just get the same message a few seconds later. When I choose Stop, I get basically a blank screeen (no editing window) with just the buttons on the bottom.

**Comment by cdsmith** [comment]
I'm looking now, and it appears that cdn.polyfill.io is hanging at load time.  Continuing to look.

**Comment by cdsmith** [comment]
Previous comment was wrong.  Firefox is hanging spending most of its time in JIT.  I'm not sure why.

**Comment by cdsmith** [comment]
https://github.com/google/codeworld/commit/5929eea8c3bb222262da38b8fcd0c91daff6ff5f is the culprit.  Commenting out the MutationObserver fixes the hang.  Now to figure out how to get the right resize behavior again.

**Comment by cdsmith** [comment]
This should be fixed now.  Thanks!
