### ISSUE TITLE
"at" function is mistyped in blocks editor

### ISSUE THREAD

**Issue by conklech** [google/codeworld#731]
Minimal case:

https://code.world/blocks#P4usidS8OicidBSZvAoHP1Q
![image](https://user-images.githubusercontent.com/573035/45839545-7c9e5600-bcc9-11e8-9447-81f0aa75d88d.png)

```
program = drawingOf(circle(at([1,2,3],1)))
```

This program is accepted by the blocks editor and looks correct, but produces a compilation error; apparently `at` takes three arguments, not two.

```
program = drawingOf(circle(at([1,2,3],1)))
1
program = drawingOf(circle(at([1,2,3],1)))
Line 1, Column 28: error:
    • Couldn't match expected type Number with actual type [a0]
    • In the argument(s) of circle, namely (at ([1, 2, 3], 1))
      In the argument(s) of drawingOf, namely
        (circle (at ([1, 2, 3], 1)))
      In the expression: drawingOf (circle (at ([1, 2, 3], 1)))

Line 1, Column 30: error:
    • Couldn't match expected type ([a0], a0, Number)
                  with actual type ([Number], Number)
    • In the argument(s) of at, namely ([1, 2, 3], 1)
      In the argument(s) of circle, namely (at ([1, 2, 3], 1))
      In the argument(s) of drawingOf, namely
        (circle (at ([1, 2, 3], 1)))
```

**Comment by cdsmith** [comment]
Oh, yep that's a bug.  Way back in the past, `at` was a synonym for `(#)`.  I'll change the code gen for the `#` block to use the operator.

**Comment by cdsmith** [comment]
@conklech 

Thanks for the report! This should be fixed now.

Please be aware that there are lots of known bugs in the CodeWorld Blocks UI.  This was the work of @stefan-j a couple years ago, and it was a phenomenal job for a summer, but it's never been productionized or completed.  The "funblocks" tag marks known issues, and some of them have drastic consequences, like corrupting a project to where it cannot be fixed.  User beware!

That doesn't mean I don't believe in the project.  I'd love to see it work out.  But I'd hate for you to invest a bunch of time and then realize it's not usable.

**Comment by conklech** [comment]
Thanks for the heads up! I didn't have any particular plans other than
thinking it was a cool advocacy/education opportunity. I only thought to
report the bug because the rest of the system seems so polished.

Maybe your warning would be appropriate to include in the project readme?

**Comment by cdsmith** [comment]
Yep, I'll do that.  The text-mode interfaces: http://code.world and http://code.world/haskell, are completely fine and very widely used.  It's just blocks that still has some major bugs.
