### ISSUE TITLE
Alignment is wrong on the bottom of the output box

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#734]
This is definitely a nit, but...

![image](https://user-images.githubusercontent.com/544744/45936523-42f57580-bf7d-11e8-8cca-72d340f12797.png)

The drop shadow is cut off at the bottom. It looks kind of bad, and will bug me until I fix it.  It's probably a matter of adding a few pixels of padding to the right container somewhere.

(@marcianx )

**Comment by marcianx** [comment]
That's because it's cropped off and there's a scrollbar on the right. Simply scroll down -- the message window is also there below it. Alternatively, one can change the default width of the right-most pane. What's your preference?

**Comment by cdsmith** [comment]
Well, I fixed the missing shadow.  It wasn't actually scrollable.  There was a CSS attribute setting the bottom margin to 0px, and that cut off the shadow.  The remaining issue is that the alignment is off:

![image](https://user-images.githubusercontent.com/544744/45954216-0a33bb80-bfd2-11e8-91d9-45bf3fc63c89.png)

I can live with that, but if you know an easy fix, let me know.

**Comment by cdsmith** [comment]
Yeah, I don't think this will be fixable, sadly.  I can only fix it in Chrome developer tools by changing the `height` property on `#result`.  But that property is set by the JavaScript code implementing the split pane.  I'll close this and just live with it. :)
