### ISSUE TITLE
Hotkey for running the program

### ISSUE THREAD

**Issue by marcianx** [google/codeworld#740]
It would be nice if we had a hotkey to immediately trigger compilation + running of a program so that we don't have to keep moving over to the mouse to run what we've typed. Probably less of a need for students and more for me. ;)

**Comment by cdsmith** [comment]
Ctrl-Enter?  Works for me.

**Comment by cdsmith** [comment]
Oh, it's missing from the help button

**Comment by cdsmith** [comment]
Will push to production in a bit.

**Comment by cdsmith** [comment]
Pushed.  It may require a cache refresh to see if you've used CodeWorld lately.
