### ISSUE TITLE
Clicking Share when a program is running shares the old code

### ISSUE THREAD

**Issue by fernando-alegre** [google/codeworld#750]
The following workflow makes students share old code without them noticing:
1. Click Run
2. While the program is running, modify the code
3. Click Share

There should be some indication to the student that the link they get in this case does not correspond to the code they have at that time, but to the code they had the last time they clicked Run. Alternatively, maybe clicking Share should automatically recompile the code before showing the link to the student.

**Comment by cdsmith** [comment]
Okay, I pushed the fix that checks for this case and warns explicitly.
