### ISSUE TITLE
Reflections

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#757]
Reflections can currently be done using `scaled` with -1 as one of the scale factors.  But to better match the 8th grade math education standards, it would be nice if it were *called* reflection.  This is similar to how we added a `dilated` function which matches the word used in the common core, and also always preserves similarity (which we don't care much about, but *is* important in the common core standards when talking about geometric transformations).  There are two possibilities for an API:

Choice 1:

    reflectedX :: Picture -> Picture
    reflectedY :: Picture -> Picture

Choice 2:

    -- Second argument is the angle of the line across which to reflect the image.
    reflected :: (Picture, Number) -> Picture

I prefer choice 1, on the basis that it's simpler, and that more complex transformations can be done by composing with rotation.  This is analogous to how we always rotate around the center, but rotations around other points can be accomplished by composing with translations.

**Comment by cdsmith** [comment]
I'm not sure if this is worth increasing the API surface area.  Just wanted to get the idea written down.

**Comment by alphalambda** [comment]
FWIW, here's my two cents.

Not to be contrarian, but I actually like the second choice much better.

First, reflectedX is a really ugly name, and it is not much shorter than reflected(_,0),
and similarly for reflectedY vs. reflected(_,90)

Second, the fact that students can change just the number to see reflections along other axes opens a lot
of possibilites for easy exploration. I'd really like having such a function, and the exercise
showing that the effect of an arbitrary reflected is equivalent to composing a single fixed reflection with a variable
rotation would be really useful for high school students.

**Comment by cdsmith** [comment]
Thanks for the feedback.  Don't worry about being contrarian!  One of the reasons I speculate out loud about these things is to get more thoughts about what is most useful.  There's also the perspective that having reflection about an arbitrary angle justifies the existence of the function a bit, because it's more than just a `scaled` with fixed arguments.

**Comment by cdsmith** [comment]
@alphalambda 

I started trying to implement this last night, but realized I don't know what the argument should mean.  What you expect to get from, say, `reflected( (1, 1), 0 )`?  I could see two answers:

* (-1, 1), because the point is reflected in the direction of the x axis.
* (1, -1), because the point is reflected across the x axis.

**Comment by blackgnezdo** [comment]
May I suggest we at least document the fact that `scaled` can be used for reflection? I imagine the use case of a student who knows to search for "mirror" and "reflect" in [the doc](https://code.world/doc.html?shelf=help/codeworld.shelf) but not necessarily aware of the issue tracker.

**Comment by cdsmith** [comment]
Yes, that's a great idea.  If you send a pull request, I'll merge it, or I can try to get to it in the next couple days.

**Comment by cdsmith** [comment]
Surveying existing online tools, I see:

* Specifying a reflection line using a pair of points.
* Offering a choice of specific reflections across the X axis, Y axis, "the origin" (which means both), or the y=x line.

The former is common for interactive activities where students can drag the points and see the effects in real time.  It seems inappropriate here to ask a student who knows the direction they want to reflect in to invent points to represent it.  The latter is common for more symbolic exercises, but it seems too limiting for us as discussed above.

I had hoped to find some kind of standard for specifying reflections at an angle, but it doesn't look like anyone else does it that way.

**Comment by cdsmith** [comment]
Okay, [wikipedia](https://en.wikipedia.org/wiki/Rotations_and_reflections_in_two_dimensions) says: "Let a reflection about a line L through the origin which makes an angle θ with the x-axis be denoted as Ref(θ)."  So I'll go with that as enough authority here.  That means that `reflectedPoint((1, 1), 0) = (1, -1)`.
