### ISSUE TITLE
Proposed backward-incompatible changes to color functions

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#768]
After teaching colors, there are a few changes that I desperately wish for.  They are not backward-compatible, but they would fix enough issues for new programmers that I'm seriously considering looking for a way to make these changes anyway.

They are:

1. `gray` (and the alternate spelling `grey`) should be a color, not a function.  Students wanting a different shade of gray may use `light(gray)`or `dark(gray)` just as they can with other colors, or `lighter(gray, 0.352)` to be more precise.  Or `RGB(k, k, k)` or `HSL(0, 0, k)`.  There are so many ways to fine-tune luminosity that it's silly to make gray alone into a function instead of a plain color.
2. `mixed` should take a list of colors as its argument, and mix them all in equal proportions.  Students often rely on `mixed` to fine-tune their complex colors, and they often want to mix, say, two parts brown to one part red, or something like that.  Currently, the best answer I have is `mixed(brown, mixed(brown, red))`, which is actually 3-to-1, and leads them down the path of deeply nesting parentheses.  I'd prefer to let them say just `mixed([red, brown, brown])`, and then further tune by adding yet more colors to the list.

I do not know any way to make these changes gradually, and the current names are just too valuable real estate to abandon.  So I propose this somewhat more aggressive than that.  Just make the change, and at the same time, add error message replacements that try to detect when students are relying on the old versions, and tell them what happened.

**Comment by alphalambda** [comment]
My students always wondered why "grey" had to be a function instead of just another color, and I did not have a good answer for that. It won't be missed, and I don't feel the need for a "grayscale" function to replace it.

**Comment by cdsmith** [comment]
Just to answer the "why" question, it originally came from [gloss](http://hackage.haskell.org/package/gloss-1.13.0.1/docs/Graphics-Gloss-Data-Color.html#g:3), which defined `greyN` but not a single gray.  Still, it's definitely confusing.

**Comment by cdsmith** [comment]
I've added a warning to these functions.  I don't want to change them in the middle of a school term, so I haven't actually changed anything yet.

**Comment by cdsmith** [comment]
I've removed the warning on `gray` and `grey`, because I expect them to be replaced by `Gray` and `Grey`, rather than changing the existing function.

**Comment by cdsmith** [comment]
The change to `gray` will happen as part of #780
