### ISSUE TITLE
Automatic requirement checker for exercises

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#769]
Idea from class today, that @marcianx and I plan to work on this evening.

When students are completing an exercise in class, there are usually some requirements for success.  For example, in class today, we wanted students to redefine three variables to be applications of the same function.  Enforcing this by hand is work-intensive, and students are likely to ignore specific requirements if they are not checked.  So, we have the following idea.

First, define a language for requirements that can be embedded into comments in a program.  When such a comment is found, the server will parse it, check each of these requirements against the syntax tree for the code, and emit an extra diagnostic that summarizes the status of each item on the checklist.  The client will look for that diagnostic, and if it's found, will display a summary of the requirements in a popup window when the program runs, with checkmarks for those that are satisfied, and an X for anything that's not satisfied.

We're starting with the ideas we need for a specific exercise.  The specific requirements:

1. "This top-level definition is not modified."  Requires a name for the top-level definition, and a hash of the definition.  Verifies that the parsed definition in the submitted code (ignoring `SrcLoc`s) matches the one provided.
2. "This variable is defined by applying that function."  Requires a variable name, and a function name.  The definition must be `var = func(...)`
3. "This function has no incomplete pattern matches."  This is a built-in warning in GHC, but I believe it's disabled by default.  We can give a conservative approximation by just requiring that all function arguments are variables.

The language is to-be-decided, but some nice features are: (1) groups of specific requirements can be given a human-readable name, to make the diagnostic more readable, and (2) there can be multiple named groups, to be shown as a checklist.

**Comment by alphalambda** [comment]
I can think of a few more requirements, like:

- The source uses only functions from a given "approved" list for the exercise
- A variable/function definition with a given name and a given type must be present

However, I think "requiring that all function arguments are variables", and similar built-in, hard-coded enforcement
of rules may make it easier to use for your style of programming or your debugging priorities,
but it may make it more difficult for others to adopt CodeWorld, because not everyone has the same priorities and stylistic preferences.

I went away from Elm because of the strong enforcement of the author's vision of what is "good code",
which no matter how it is defined, it will be impossible for others to agree 100%.

Maybe having {-# CODEWORLD #-} pragmas that restrict available language features would help everyone decide according to their differing criteria.

For example, the current extra rule "everything must always have parentheses" gets in the way when you have functions of lists or higher order functions, and while it may be important
for the first couple of months, it is not so useful in the other five/six months of a course. I wish it were a pragma.

That reminds me of what I read about Racket, which I think has also "beginner", "intermediate" and "advanced student" pragmas. The needs of students are different the first two
months and the last two months of a full year course.

**Comment by cdsmith** [comment]
Yeah, I get the broader concerns.  I want to keep this focused, though, on enforcing specific requirements that are communicated to students for a single assignment.  Maybe this mechanism can be generalized to something like Racket's language levels, but I don't know if this would be the right mechanism for that particular use case.

This feature would definitely only apply to source files that had these requirements embedded into their comments.  If there's no special comment, this would have no effect.

**Comment by cdsmith** [comment]
For example:

    program = drawingOf(train)

    train = car1 & car2 & car3

    car1 = car(-5, blue)
    car2 = car(0, red)
    car3 = translated(colored(solidRectangle(5, 2), green), 5, 0)

    car(x, c) = translated(colored(solidRectangle(5, 2), c), x, 0)

    -- ASSIGNMENT RULE: "The definitions of `program` and `train` are not modified."
    -- check_sha1(program, kasgdlas77878apsdpdahsyd778)
    -- check_sha1(train, 23ljn23jnbre23jnbl2k3bo23bdo)
    -- ASSIGNMENT RULE: "All cars are defined using a common function named `car`."
    --  check_definedBy(car1, car)
    --  check_definedBy(car2, car)
    --  check_definedBy(car3, car)
    -- ASSIGNMENT_RULE: "The `car` function is defined for any arguments."
    --  check_onlyVarPatterns(car)

And compiling this would generate something like this in compiler output:

    :: REQUIREMENTS ::
    [✓] The definitions of `program` and `train` are not modified.
    [X] All cars are defined using a common function named `car`.
         (The definition of `car3` does not use the `car` function.)
    [✓] The `car` function is defined for any arguments.

**Comment by cdsmith** [comment]
It would be great to implement this eventually using plugins like @nomeata's inspection-testing tool.  But we're a long way from getting there: prerequisites would include supporting Template Haskell, and using GHC 8.6 (which currently has no GHCJS implementation).  So for now, we will parse comments in a preprocessing step.

**Comment by alphalambda** [comment]
It seems that check_sha1, check_definedBy and check_onlyVarPatterns are just instances of a generic match_definition.

Would not something like the following make more sense?

-- ASSIGNMENT RULE: "The definitions of `program` and `train` are not modified."

-- match_definition("program", "drawingOf(train)")
-- match_definition("train", "car1 & car2 & car3")

-- ASSIGNMENT RULE: "All cars are defined using a common function named `car`."

-- match_definition("car1", "car(%expression%, %expression%)")
-- match_definition("car2", "car(%expression%, %expression%)")
-- match_definition("car3", "car(%expression%, %expression%)")

-- ASSIGNMENT RULE: "The `car` function is defined for any arguments."

-- match_definition("car(%parameter%, %parameter%)", "%expression%")

Where the wildcards %expression% and %parameter% stand for an arbitrary expression or parameter.

I think this is more "teacher-friendly" than requiring teachers to calculate sha1 hashes.

**Comment by cdsmith** [comment]
That sounds like a great idea.  Unfortunately, I don't know how to parse arbitrary Haskell code with %-interpolations like that.  I'll think about ways to make this work.  Are you aware of a library or something?

**Comment by marcianx** [comment]
One hackaround to parse %-interpolations would be to replace each of them with a unique identifier of a form that you may not allow CodeWorld users to use -- e.g. `__foo` -- and then allow these identifiers to match arbitrary expressions when comparing parse trees.

**Comment by alphalambda** [comment]
Yes. That's basically what I had in mind, except that %expression should match an expression, but %parameter should match an argument name, and maybe other %-interpolations could match other parts of the parse tree.

Alternatively, the match could be regular-expression based, so that %expression matches /.*/ and %parameter matches /[a-z][a-zA-Z0-9]?/

If the program compiles, we are guaranteed to have a proper program anyway, so we can assume that %expression will actually be an expression.

**Comment by cdsmith** [comment]
I do have a draft implementation now.  You can try it at https://code.world/#PRL_MKSqQUdr_AA9zX-JRiQ  It may require clearing cache to reload to new client-side JavaScript.

I am not ignoring the advice from this bug.  I appreciate the ideas.  We just also wanted to get something implemented quickly to try out in class, and the teacher-facing API was not particularly important for the purposes of this test.  It's entirely possible that we could completely change the requirement language in a future implementation.

**Comment by cdsmith** [comment]
Student feedback from our test today was overwhelmingly positive.  Feedback from myself was very positive, as well.  There were many occasions on which students who yesterday were happy to take shortcuts and ignore requirements were instead very motivated to figure out how to give a correct solution, because it was being checked.

One point of confusion arose when the program did not compile due to parse errors.  Then the current implementation skips requirements checking entirely, since the requirements checker works on the parsed syntax tree.

Another weird case is when the program doesn't compile due to type or scope errors, the requirements checker runs, but may report all green checkmarks even though the code doesn't run at all!  There was a request to add an implicit "the program must compile" to the requirements list.  That requires making the final decision on the requirements list much later in the process.  It's also tricky because a program may still compile, but fail immediately at runtime.  Or it can show the wrong picture!  Now we're possibly into territory where we'd like to add testing, as well as static validation.  I suppose that's inevitably part of the broader feature.

I also had minor problems with the use of comments for the requirement specification.  A few students deleted the comments during copy-and-paste usage, or just by accident.  In some cases, too, particularly with the syntax-directed checks that @alphalambda proposed above where there's a template for the correct answer embedded in the rules, having the specification in the file itself can give away the answers.  Students won't hesitate to just copy the solution from the comment that reproduces it.  We could add some kind of obfuscation, but this seems like solving only part of the problem.

Better would be some kind of UX for a teacher to define a requirement set, possibly even using an embedded DSL inside of Haskell, and then get a code that can be embedded into a sharing URL to enable that spec.

**Comment by cdsmith** [comment]
I've now added an obfuscated mode (see above commit), which I'm quite happy with.  It also works in plain Haskell mode, as well.

Next step is to think more seriously about the constraint language.  Ideas:

* "The code must compile" has been requested.  But maybe it's better if we just don't even bother to check requirements until the code compiles.
* I'm a fan of @alphalambda 's idea to offer a general means of matching patterns.  (I'm more a fan of doing it at the AST level than as regular expressions, and I think doing that via `__var__` style names looks fine.)
* Formatting requirements, like "No lines longer than 80 characters", might fit here.  Possibly other style rules.
* A common kind of requirement might be "you define at least 10 variables in your project", so count-based constraints would be good.
* Then there are the runtime testing ideas... anything from "your code must not fail at runtime" to even testing for specific pictures... or even playing event logs and checking results.  Definitely a stretch goal, though.

Then, finally, there's the matter of whether comments are the right UI, or if there should be "sticky" requirements embeded in a URL that stay around when CodeWorld is loaded in that mode, even if the source is completely erased.  I think we can postpone that, though, and develop with comments for a while.  (One sort-of hack suggested by @marcianx is to support sticky requirements by putting them in comments, but in another program referenced by hash from the URL.  That's reasonable.)

**Comment by alphalambda** [comment]
If possible, I would like the requirements to allow specifying the following too:

- A list of functions that are not allowed to be used in an exercise
- A list of functions that must be used in an exercise
- Exceptions to the above rules for specific definitions

For example, I would like to be able to have exercises like these: (I simplified the settings for clarity)

- Build a rectangle using "polygon" instead of "rectangle" (using "rectangle" not allowed)

- Use the included definition of "ellipse" (which uses "circle") but do not use "circle" anywhere else in your code, and then draw
  a bunch of ellipses

- Build a tangram using just the provided polygonal pieces (polygon and rectangle are not allowed
  except in the definition of the provided tangram pieces)

**Comment by cdsmith** [comment]
Wrote up a current state of the design at https://github.com/google/codeworld/blob/master/RequirementChecker.md

We can still discuss here, since it's easier to talk in an issue than in a submitted file.  But I'll try to keep the latest up-to-date info together in that location.  Eventually, it can serve as documentation for the completed feature.

**Comment by cdsmith** [comment]
Status: this really feels like it's starting to come together.  I've switched over to a YAML-based syntax, which I think paves the way for including richer and more structured requirements, such as those parsed Haskell source fragments used as patterns.  I further modularized the compiler wrapper, and used the new structure to avoid running the requirements checker unless the compiler succeeds.  I'm now ready to start working more on specific rule types, and I think the decl matching proposal is a good one to start with.

It's probably time to close this issue as fixed, since the infrastructure is in place, and open new issues for specific improvements we want, like individual rule types.  I'll probably do that tomorrow.

**Comment by cdsmith** [comment]
The feature exists.  I'm now closing this general but I'm favor of specific issues I filed to implement future features.  Those are #772, #773, #774, #775, #776, #777, #778, and #779.
