### ISSUE TITLE
Define colors as pattern synonyms?

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#780]
One problem that I run into when teaching early functions is that equations cannot be written for specific colors without using RGB or HSL form.  That is, one can't write:

    f(red) = colored(ball, red)
    f(blue) = colored(ball, blue)

and so on.  This is inconvenient, because:

1. Colors are the strongest early examples of user-defined function arguments.  ("What if you wanted to draw people with many different hair colors?")
2. It seems to work well to introduce functions by writing specific equations first, then generalizing the pattern after a few equations have already been written.  I'd like students to be able to *actually* do that in code... but it doesn't work, because `f(red) = colored(ball, red)` is *already* the generalized pattern, entirely by accident.

One could easily redefine the built-in colors as pattern synonyms (as `Red` instead of `red`).  The advantage would be that the introduction of functions would go more smoothly.  If we did this, we would probably also change `pi` to `Pi`, as well, and maybe other analogous cases.  Note that `Bool`, `Text`, and `Number` literal expressions already have pattern forms, so `Color` and `Picture` are the only exceptions here.

The disadvantage is that the introduction of *colors* would break rules, leading to questions about why these are capitalized.  That's a conversation we're definitely not ready to have so early in the class.  I'd have to hide behind vague language about "Red is more like a literal value than a variable" or something like that.  And we can't entirely hide the issue, since expressions like `sqrt(2)` or `1/2` are also not usable as function arguments.

**Comment by cdsmith** [comment]
To be clear, pattern synonyms are capitalized.  So this change would involve changed `red` to `Red`, and the rules about capitalized names remain true.  In fact, `RGB` and `HSL` are already pattern synonyms; the only true `Color` constructor is `RGBA`.

I definitely don't want to remove colors entirely.  I try to introduce colors as early as possible (say, within the first few days of instruction.  I definitely couldn't do that if I got distracted talking about specifying colors in terms of red, green, and blue components.

That said, I definitely see a case for reducing the number of predefined colors to those that are truly household names (so maybe: red, green, blue, yellow, orange, brown, purple, pink, white, black, and gray; but not cyan, magenta, rose, aquamarine, violet, chartreuse, or azure... but maybe there's a case for keeping cyan and magenta because of their role as primary pigment colors).  With fewer built-in choices, there's more incentive for students to start customizing their colors earlier, whether it's done by using `RGB` or `HSL`, or by using functions like `light`, `dark`, `bright`, `dull`, and `mixed`.  Would you look favorably on this change?  I'm not convinced, but I'm willing to consider it.

**Comment by alphalambda** [comment]
What I think would be confusing is if both `red` and `Red` were available. So, I think either of these two options could work:

1) Leave it as it is now. Colors can be accessed either via pre-defined variables (red,blue,etc.) or via RGB and friends (HSL,RGBA), but partial function definitions work only with RGB and friends.

2) Not have pre-defined variables. Instead use only Red, Blue, etc. (and also RGB,HSL,RGBA). In this case, partial function definitions will work with all colors

**Comment by cdsmith** [comment]
Yes, #2 is what I was proposing.  I mean, for a transition period, we'd still have the old variables, but they would be marked as deprecated and hidden from the autocomplete window.  After a suitable delay, I would remove them.

I think I'm also leaning in favor of paring down the built-in colors to just `Red`, `Green`, `Blue`, `Yellow`, `Orange`, `Brown`, `Purple`, `Pink`, `White`, `Black`, and `Gray`.  That way the really obvious colors are there, but students looking to fine tune their color choices would be encouraged to turn to composing expressions earlier (using `RGB`, `HSL`, `light`, `dark`, `bright`, `dull`, or `mixed`), rather than hunting down more memorized color names.

I'm still not really decided.  The disadvantage is that this exposes the constructor/variable distinction earlier; and to be honest, I'm not in a hurry to explain that.  The weird meaning for capital letters is definitely not standard math notation, and I'm not interested in teaching Haskell for its own sake.  But the ability to write examples of function patterns with colors is a compelling argument in favor.

**Comment by cdsmith** [comment]
I'm going to open a new issue for reducing the number of colors.  I think it's promising, but it's actually entirely orthogonal to whether colors become pattern synonyms.

**Comment by cdsmith** [comment]
I've been exploring and field-testing explanations on students, and I'm convinced that capitalizing color names is not a problem when it comes to understanding.  So I'm committing to this change.
