### ISSUE TITLE
install.sh hangs during ghcjs-boot with some node.js versions

### ISSUE THREAD

**Issue by nixorn** [google/codeworld#794]
**Description**

I run install.sh and waiting around 2 hours on my laptop. Last lines of output is

```
...
Data/Aeson/Types/FromJSON.hs:471:3: warning: [-Winline-rule-shadowing]
    Rule "FromJSONKeyCoerce: fmap id" may never fire
      because ‘id’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma for ‘id’
[13 of 23] Compiling Data.Aeson.Internal ( Data/Aeson/Internal.hs, dist/build/Data/Aeson/Internal.js_o )
[14 of 23] Compiling Data.Aeson.Encoding.Builder ( Data/Aeson/Encoding/Builder.hs, dist/build/Data/Aeson/Encoding/Builder.js_o )
[15 of 23] Compiling Data.Aeson.Encoding.Internal ( Data/Aeson/Encoding/Internal.hs, dist/build/Data/Aeson/Encoding/Internal.js_o )
[16 of 23] Compiling Data.Aeson.Encoding ( Data/Aeson/Encoding.hs, dist/build/Data/Aeson/Encoding.js_o )
[17 of 23] Compiling Data.Aeson.Types.ToJSON ( Data/Aeson/Types/ToJSON.hs, dist/build/Data/Aeson/Types/ToJSON.js_o )
Linking Template Haskell ()
runNodeInteractive
Linking Template Haskell (Data.Aeson.Encoding,Data.Aeson.Encoding.Builder,Data.Aeson.Encoding.Internal,Data.Aeson.Internal,Data.Aeson.Internal.Functions,Data.Aeson.Internal.Time,Data.Aeson.Parser,Data.Aeson.Parser.Internal,Data.Aeson.Parser.Time,Data.Aeson.Parser.Unescape,Data.Aeson.Parser.UnescapePure,Data.Aeson.Types.FromJSON,Data.Aeson.Types.Generic,Data.Aeson.Types.Internal,Data.Attoparsec.Time,Data.Attoparsec.Time.Internal,ThRunner1)
```

Now trying to downgrade nodejs version as described here https://github.com/ghcjs/ghcjs/issues/668 . If it will success, possibly need to freeze nodejs version.

**Comment by nixorn** [comment]
Yes, it works with downgraded node.

**Comment by nixorn** [comment]
@cdsmith I had new version of nodejs (v11.1.0) installed in home. I used [nvm](https://github.com/creationix/nvm) before for other projects, so node from apt-get was overlapped by fresh node from nvm. After I switch node to old (`nvm install 7.10.1 && nvm use 7.10.1 && nvm alias default 7.10.1`) install.sh finished successfully.

**Comment by cdsmith** [comment]
Interesting that 11.x still fails, when hvr's note implies it should work.  That might depend on the GHCJS version as well, though.  For the time being, CodeWorld is still based on GHCJS 8.0.  I plan to upgrade to 8.6 this summer, but Luite has until very recently still been working out the bugs with that version.

**Comment by cdsmith** [comment]
@nixorn, if you could still reproduce this, can you try it again on a fresh install?  We're now building GHCJS 8.6, which should have more bug fixes.

**Comment by nixorn** [comment]
@cdsmith I can not reproduce this now.

**Comment by cdsmith** [comment]
Thanks.  I'll close this, then.
