### ISSUE TITLE
Algorithmic pictures

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#80]
Consider:

```
dynamicPicture :: (Point -> Color, Number, Number) -> Picture
```

then `dynamicPicture(f, w, h)` is a rectangle of width `w` and height `h`, the color of each pixel being taken by sampling the function `f` with the appropriate coordinates.  For examples of some of the pretty amazing things that can be done in this model, see https://www.shadertoy.com.

The major open question is whether this would ever be efficient enough to work.  It appears that shadertoy.com works by compiling user programs to the GPU, which probably isn't an option with simple Haskell code.

**Comment by cdsmith** [comment]
This is almost surely not feasible; you need a GCU to get reasonable performance from this model.  So I'll just close it.

(@nomeata did something at https://www.joachim-breitner.de/blog/742-WebGL%2C_Fragment_Shader%2C_GHCJS_and_reflex-dom, but it's just using GHCJS to build the machinery for injecting imperative code.)

**Comment by nomeata** [comment]
You could have
```
dynamicPicture :: (Point -> Color, Number, Number) -> Picture
```
if you use a compiler plugin a la  Conal’s compiling to categories to compile the function passed to `dynamicPicture` to Shader :-)
