### ISSUE TITLE
build_codemirror fails when building with docker

### ISSUE THREAD

**Issue by josephcsible** [google/codeworld#808]
I'm trying to get CodeWorld to build and run inside of Docker. Here's the Dockerfile I'm using:
```dockerfile
FROM debian:stable
RUN apt-get update && apt-get install -y sudo gnupg
WORKDIR /codeworld
COPY . .
RUN ./install.sh
CMD ./run.sh
```
It works fine until the build_codemirror step, then fails with this error:
```
===== IN /codeworld/build/CodeMirror, RUNNING: build_codemirror
Some specified files were not found: codemirror

========== Aborting: Command failed. ==========
DIRECTORY: /codeworld/build/CodeMirror
COMMAND  : build_codemirror
EXIT CODE: 1
===============================================
The command '/bin/sh -c ./install.sh' returned a non-zero code: 1
```

**Comment by josephcsible** [comment]
So far, I've only tried it with Docker, as I don't want to install it and all of its dependencies directly on my host. I guess I'll try it in a full-fledged VM, though.

While I'm trying that, would you happen to know which step in the build is supposed to make the file that it's looking for there, and what the exact path to it is supposed to be?

**Comment by cdsmith** [comment]
To be honest, I don't understand npm all that well, but it looks like it might be this line in install.sh:

    run $BUILD/CodeMirror npm install

**Comment by josephcsible** [comment]
After doing some more testing both with Docker and in a normal VM, this looks like it's related to the user and/or directory used to build, rather than related to Docker itself. I plan to update this with details tomorrow, and hopefully submit a PR to get it closed.

**Comment by cdsmith** [comment]
I have rewritten this in the process of upgrading CodeMirror.  Perhaps you might try again?  See https://github.com/google/codeworld/commit/d89ad16703ad643b1aba74ff4dff15f4889b3d28  This removes a lot of directory scanning that used to happen inside CodeMirror/bin/compress.

**Comment by josephcsible** [comment]
Between what I've discovered and that commit, it seems to work now. New Dockerfile:
```
FROM debian:stable
RUN useradd -ms /bin/bash codeworld \
 && apt-get update \
 && apt-get install -y sudo \
 && echo "codeworld ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
WORKDIR /home/codeworld/codeworld
RUN chown codeworld:codeworld .
USER codeworld
COPY --chown=codeworld . .
RUN ./install.sh
CMD ./run.sh
```

In the future, I plan to make incremental builds less painful and get the Dockerfile in the repo, but those are both out of scope of this ticket.
