### ISSUE TITLE
Autocomplete doesn't work with a blank document

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#822]
When starting with a blank document, autocomplete doesn't do anything.  You have to modify the document, wait the 3 second timer for the reparse to occur, and then trigger it again.  Oops!  We must just be forgetting to initialize codeWorldSymbols before the reparse.  

@nixorn fyi

**Comment by nixorn** [comment]
Ok, will fix.

**Comment by cdsmith** [comment]
I ended up fixing this.  It was a one-line fix, and I wanted this working for a class I'm teaching tomorrow.  I'm telling them about autocomplete, and I would have lost a lot of class time if it didn't work when I asked everyone to try it.
