### ISSUE TITLE
Weird line-wrapping behavior

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#838]
I've noticed lately that CodeMirror does some weird things when a closing bracket is at the end of a line.

![image](https://user-images.githubusercontent.com/544744/52914257-44a93800-3294-11e9-972f-6d3af994fa47.png)

It seems that just the last the bracket can be wrapped to the next line, and then CodeMirror considers the whole wrapped line to be a single line, drawing an extremely tall text cursor.  To reproduce:

1. Type a line that ends in a close parenthesis.
2. Move the text cursor back BEFORE the end of the line.
3. Start adding spaces until the end of the line reaches the right margin.  Now the weird wrapping behavior occurs.

I suspect it's something to do with the new CSS transforms in https://github.com/google/codeworld/pull/820 -- @josephcsible , any ideas here?

**Comment by cdsmith** [comment]
Since this is likely to be browser-specific, I see this on Chrome 71.0.3578.127  Haven't tried other browsers.

**Comment by josephcsible** [comment]
Yep, it's caused by `display: inline-block` that #820 added. It is indeed also specific to Chrome, as it works fine in Firefox 65. I'll try to investigate this more later today.

**Comment by cdsmith** [comment]
This is a much bigger problem than the slight misalignment that #820 was intended to solve (and my understanding is that the bulk of that was font problems anyway).  If there's not an easy solution, then I'll probably revert the css-transform change and go back to changing the font size.

**Comment by josephcsible** [comment]
I've been busier than expected this week and haven't had time to track this down yet. Go ahead and revert it for now, and if/when I find a solution, I'll just send a new PR to reinstate this that includes it.
