### ISSUE TITLE
Unit tests for the compiler aren't well-documented and do not test the correct behaviors

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#844]
A few years ago, a Summer of Haskell student set up a test infrastructure to test compile errors from CodeWorld.  That's great... but the tests are awful.  They are not interesting examples, and don't test specific features.  They are instead just random selections of code, and the expected output is just whatever was captured from some previous run.

With the tests in this state, I don't really gain much confidence by seeing the tests pass.  It would be nice to actually isolate intentional behaviors, and design the tests to target and validate them.

Would be nice to get this done before the coming GHCJS 8.6 upgrade.

**Comment by nixorn** [comment]
On my instance compile tests are fall with messages like
```
expected: "program.hs:1:1: error:\n    Parse error: naked expression at top level"
 but got: "<command line>: cannot satisfy -package the standard library \n    the standard library is unusable due to missing or recursive dependencies:\n      codeworl$-api-0.3.1-6XSpkzNfqXw6rK8JNTQ4IF\n    (use -v for more information) (no loc)"
```
Is it my local problem?

**Comment by cdsmith** [comment]
If you do a fresh run of `./build.sh`, does that fix the problem?

**Comment by nixorn** [comment]
No, running `buld.sh` and then `test.sh` leads to same result.

**Comment by cdsmith** [comment]
Does building and running code work at all in your local server?  I'm quite surprised if those tests are failing but the server is still working...

**Comment by nixorn** [comment]
It is. Building and running works as usual.

**Comment by cdsmith** [comment]
One more question: is this true at HEAD, or is the problem created by local changes?  I noticed your unit-testing pull request branch includes changes to rebuild codeworld-api with flags, and I wonder if the problem comes from that.

**Comment by nixorn** [comment]
making build -> test -> run on upstream head, several minutes

**Comment by nixorn** [comment]
yes, in HEAD it does work. So reason in my changes.

**Comment by cdsmith** [comment]
I suspect what's going on is that when you test codeworld-api, you're overwriting codeworld-api in the GHCJS package database with a new version built against different flags; but you aren't reinstalling codeworld-base, so you end up with a broken codeworld-base install.  Running `./build.sh` fixes the GHCJS package database, so building and running works fine.  But the next run of `./test.sh` breaks it again.

**Comment by cdsmith** [comment]
Let's reclaim this bug for its original purpose, and discuss this in your pull request.

**Comment by cdsmith** [comment]
I cleaned these up a little.  They are not comprehensive, but at least they now make sense.
