### ISSUE TITLE
Block-based programming UI

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#85]
Block-based programming UIs with types-as-shapes seem to be all the rage these days.  It's an open question whether such a thing could be built for CodeWorld.  Certainly yes, for built-in monomorphic types and functions.  Open questions include:

1. What would this look like for user-defined algebraic data types?
2. How would this work for recursion?
3. How would this look with polymorphism? (Maybe the sockets are sparkly magic-looking swirls of various colors, and once you fill one in, the others change to match it...)

Another big issue is how to map GHC error messages back to the block-based input.

**Comment by cdsmith** [comment]
There are some very deep thoughts on this by John Reekie at http://ptolemy.eecs.berkeley.edu/~johnr/papers/pdf/thesis.pdf

The notation there is certainly not right for younger students, but that level of detail and analysis is a great start to planning this project.  Someone would just need to evaluate which decisions can be simplified, and how usable this can be for children.

**Comment by cdsmith** [comment]
Also: http://asg.unige.ch/site/papers/Dami96a.pdf

**Comment by clord** [comment]
I've thought of making something like this for my son to learn the ideas of functional programming. I'll share some of them here:

Blocks are created by using the equivalent of operators. Blocks are connected with wires to ports on other blocks. The only thing that goes through a connection are entire blocks (with or without all arguments specified). I imagine each missing argument is a 'bump' in the shape that prevents the thing from fitting in a place that expects all arguments. One curries by passing incomplete blocks to another block which expects its arguments to have multiple inputs.

I'd pick a small subset of typeclasses and types, and map color to represent types, and pick an overall block shape to represent typeclasses (circles for num, squares for string, etc). Inputs are indicated on a block by a port of the appropriate shape (and color) on one side of the block. that fit the right shape/color. Some holes demand a certain exact type and so have a colored tint or outline, whereas others only want the typeclass and so have a transparent tint but still the demanded shape. 

Main is indicated by an incoming IO-shaped pin that is to be connected to your main function. IO is a special shape that allows entries to be added for sequencing. Toy examples might have a more restricted incoming pin like Either. 

Pattern recognition would be a shape that accepts the combined shape on one side (say, Either) and on the other side has two possible 'output' shapes. More thought needed here.

**Comment by cdsmith** [comment]
@clord, thanks for the thoughts.

Stefan Jacholke is working on this as a Summer of Haskell project this summer, and has set up a blog for the project at http://stefanj.me/funblocks/ if you're interested in following along and sharing more ideas.
