### ISSUE TITLE
Tool tip with argument help when typing a function

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#850]
When typing a built-in function, it would be neat if a tooltip popped up above the line, with names for the parameters, and a bold font to show which one you're currently on.

![bcpcv0s34pw](https://user-images.githubusercontent.com/544744/53220717-fa2d1000-3633-11e9-8f7d-7323e9374975.png)

**Comment by devanshbatra04** [comment]
I would like to take this up. 
Some help would be appreciated. Some pointers on how can I get a metadata of available functions on the frontend?

**Comment by cdsmith** [comment]
This is perhaps related to the hover, but it actually something different.  The idea is for this to appear above the current line, whenever the text cursor is inside a function application, and not on mouse hover.  This is actually a bit tricky; it requires parsing the source code, and knowing the parameter names for the built-in functions.

Artem started working on parsing in #863, but that's stalled at the moment until we have a chance to look at options again and find a way forward.  For the purpose of this feature, you could probably get by with some kind of partial parser that gives up when the current cursor position has anything except a function application around it.  Even so, there's no automatic way to find parameter names for builtins, so that's information that needs to be fed in.

**Comment by devanshbatra04** [comment]
Understood, thanks.

**Comment by cdsmith** [comment]
A few issues that I found when testing:

1. At least on my browser, the popups are always aligned on the left side of the screen.  It would be nice to line them up with something near the function call.

2. `activityOf` doesn't get highlighted, and I believe it's because there are parentheses inside the arguments.  Its type is `([Number] -> state, (state, Event) -> state, state -> Picture) -> Program`.  This makes me think that we might need something more powerful than regular expressions to parse the parts from the type signature.

**Comment by cdsmith** [comment]
`rest` also doesn't work, because of the brackets in the parentheses.

Also, functions that don't work are spamming the JavaScript console with exceptions.

![850errors](https://user-images.githubusercontent.com/544744/55497762-0b444600-5610-11e9-81e6-e2335d06bbf0.png)

**Comment by devanshbatra04** [comment]
@cdsmith 
1. the left alignment was somewhat intended, as it was a quick fix by using CodeMirror's addwidget thing. I will work that out. 
2. activityOf seems an interesting case. Would it be a good idea to get argument names only, I believe that would require a cumbersome edit to ```codeworld-base.txt```? 

Also, should I send in a quick PR that handles the slice exception?

**Comment by cdsmith** [comment]
Further pull requests are definitely welcome.  I suspect catching that exception (and doing nothing if it doesn't match) is a minimum.  Fixing the alignment would also be great; it can be a bit jolting right now.

Handling more complex types is probably more of a project.  What we really need is a first-class parser for the subset of Haskell. needed to populate autocomplete.  @nixorn started some work on this, but it stalled because we need to choose a parsing framework, and I haven't had time to review options.  There are some tough requirements for the parser: we need aggressive error recovery, for example, and support for indentation-sensitive parsing.  I think it's okay to leave this in its current state for now.

Function arguments is also a bigger task.  As you mentioned, we're going to need some auxiliary source of information on function argument names for builtin functions, because they don't exist in the haddock-format output. There are some design choices to make there.  We can definitely get them from the source code for the current module, when functions are defined locally, but once again that's blocked on better parsing.

**Comment by cdsmith** [comment]
I think this is in a good state for now, so I'll close it.
