### ISSUE TITLE
[codeworld-api] Relax bounds: containers

### ISSUE THREAD

**Issue by endgame** [google/codeworld#851]
GHC 8.6 ships with `containers-0.6`, which is excluded by the current bounds in `codeworld-api`. It seems to build OK with an upper bound of `containers < 0.7`, so I suggest relaxing the bounds and publishing a metadata revision.

**Comment by cdsmith** [comment]
Yes, I'll do that within the next 24 hours.  I want to deal with #842 first, so I don't release a new hackage version only to revert one of the breaking changes a few days later.

**Comment by cdsmith** [comment]
Pushed changes.  Will reupload to hackage soon

**Comment by cdsmith** [comment]
Bounds are relaxed in codeworld-api 0.3, published now.
