### ISSUE TITLE
Embeded CodeWorld programs not working in CIS194 course

### ISSUE THREAD

**Issue by abiduzz420** [google/codeworld#853]
**Description**
Codeworld embeds are been rendered as blank white boxes in the CIS194 course which uses lot of codeworld demos for educational purposes. For example, [higher order functions](https://www.seas.upenn.edu/~cis194/fall16/lectures/02-ho-datatypes.html) chapter contains couple of codeworld embeds. I have tested it both on Google Chrome and Firefox Quantum browser.

Console logs form Chrome:
```
Mixed Content: The page at 'https://www.seas.upenn.edu/~cis194/fall16/lectures/02-ho-datatypes.html' was loaded over HTTPS, but requested an insecure script 'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'. This request has been blocked; the content must be served over HTTPS.
Failed to load resource: the server responded with a status of 400 (Bad Request)
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

Console logs from Firefox:
```
Blocked loading mixed active content “http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML”[Learn More]
04-typeclasses.html
Loading failed for the <script> with source “http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML”. 04-typeclasses.html:8:1
Loading failed for the <script> with source “https://code.world/runJS?mode=haskell&hash=PI8Rd7guupXOJc-76-bF32A”. run.html:1:1
```
What could be the underlying cause for this behavior?
Other necessary details: using Win10 OS

I am happy to help out in fixing the issue :)

**Comment by abiduzz420** [comment]
The issue may be due to the [latest commit](https://github.com/google/codeworld/commit/d152511eebd98f961cd7902464085993284a0777#diff-f24d7f125ebcfc91a41ecef0b15789a9R213) to the master branch. Perhaps, this is not a bug but a breaking change?

The commit changed old-style colors signature from `Double -> Color` to `Color`
Diving into the codeworld demo examples, the editor highlights error on a line which says:
```
wall =    colored (red 0.4) (solidRectangle 1 1)
``` 
The function red is applied to one argument but its type `Color` has none. Fixing the code to:

```
wall = colored red (solidRectangle 1 1)
```
solves the issue.
Due to this breaking change, there seem to be blank demos as this line of code is almost in all examples.

**Comment by cdsmith** [comment]
Oh, okay.  It's actually just gray that took a parameter.  Have been trying to change this for ages.  I wonder if there's anyone who could update the CIS194 pages...

**Comment by cdsmith** [comment]
I think I can fix these manually by just editing the saved code at those hashes.

**Comment by cdsmith** [comment]
Okay, I've manually replaced the code at those hashes to change `grey` to `HSL 0 0` everywhere.  That's not ideal, but it keeps the course working and is the best we can do without hamstringing ourselves with a poor API forever.

**Comment by abiduzz420** [comment]
Yeah that probably should be okay for now! Thank you for fixing it 👍
