### ISSUE TITLE
Blocks UI stopped working due to missing addToMessage function

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#854]
The CodeWorld blocks UI currently doesn't work at all.  It looks like it was broken by https://github.com/google/codeworld/commit/8598cf8e5a6738fcfd317b97d52786f13471f83f by @nixorn, which removed the `addToMessage` function in codeworld_shared.js.

Exception is:

    Uncaught ReferenceError: addToMessage is not defined
        at run (funblocks.js:186)
        at compile (funblocks.js:227)
        at h$$QR (blocks_out.js:35510)
        at h$runThreadSlice (blocks_rts.js:8284)
        at h$runSyncAction (blocks_rts.js:8446)
        at HTMLAnchorElement.h$runSync (blocks_rts.js:8417)
        at HTMLAnchorElement.c (blocks_rts.js:4924)

**Comment by cdsmith** [comment]
@nixorn Can you please look at this?

**Comment by nixorn** [comment]
@cdsmith  Oops, sorry. I replaced addToMessage in #855, but funblocks still not works, because of another error.

**Comment by cdsmith** [comment]
Thanks.

I suspect the other error you see is a race condition that happens when funblocks.js loads faster than blockly.  It is almost certainly a pre-existing problem, not caused by recent changes. In fact, it's most likely the same problem as #402, though I don't see the error message you posted when it happens in Chrome.
