### ISSUE TITLE
codeworld-api-0.3:  printf: bad formatting char 'f'

### ISSUE THREAD

**Issue by endgame** [google/codeworld#857]
**Description**

When running `drawingOf coordinatePlane` either through GHCi or as a compiled program, I get the following error when opening the browser link:

```
"Exception in blank-canvas application:"
printf: bad formatting char 'f'
```

This behaviour is not present in codeworld-0.2.5.

**Comment by cdsmith** [comment]
Sorry about this.  I know what's wrong, and I'll push a fix in a couple hours.

**Comment by cdsmith** [comment]
Okay fixed.  Thanks for the bug report.
