### ISSUE TITLE
[Guide] Error message typo: "Miriam" in explanation, "Victor" in codes

### ISSUE THREAD

**Issue by duianto** [google/codeworld#858]
#### Typo:
The name "Miriam" is used in the explanation, but the error and solution codes (before and after) uses the name "Victor".

#### Understanding mistakes
https://github.com/google/codeworld/blob/277d0517b25dce60e748ded5782b9cd9bc8d05a8/web/help/GuideUnit1.md#understanding-mistakes

The third error:
`Multiple declarations of nametag`

Below the error code:
```haskell
program = drawingOf(nametag)

nametag = lettering("Victor")
nametag = circle(10)
```

The first sentence in the explanation:
>One line says `nametag` means the text "Miriam", but the second line
says that `nametag` instead means a circle with a radius of 10.

### Issue

The explanation states that:
>nametag means the text "Miriam"`

but both the error and solution codes (above and below the explanation) uses the name "Victor".

### A Possible Solution

The first sentence of the explanation with the name changed to match the code, looks like this:
```
One line says `nametag` means the text "Victor", but the second line
says that `nametag` instead means a circle with a radius of 10.
```

### Additional Notes

The name "Miriam" is used in the error and solution codes for the next error 
(`Couldn't match type Program with Picture`), that's probably where the name came from.

Possibly if both error sections where written/edited at the same time.

**Comment by cdsmith** [comment]
Fixed.  Thanks!
