### ISSUE TITLE
Error highlights don't replace source locations in hover text

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#873]
I can't figure out an example at the moment, but I've seen this.  Errors in hover text sometimes don't replace source locations, so you see something like `program.hs:5:3`, where our convention is to replace that with "Line 5, Column 3"

**Comment by cdsmith** [comment]
@nixorn Another likely quick fix, if you have time to look.

**Comment by nixorn** [comment]
Ok, when I'll encounter this I'll pay attention to it.

**Comment by cdsmith** [comment]
https://code.world/#PqIBNGrbqNnwDz3ZFc8zTQw is an example.
