### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by 3noch** [google/codeworld#877]
Would be nice to have a dark theme.

**Comment by cdsmith** [comment]
This should be pretty straightforward to implement: it just requires revising all of the CSS styles to add a parent selector like `body.dark` or `body:not(.dark)`, and then adding some kind of button or menu to switch them out by changing the class on the document body.

It's worth mentioning that I've seen a lot of students approach this using a feature of Chromebooks that inverts colors.  (It's called "high contrast mode" in accessibility settings.)  But that gets really confusing with building graphics using builtin color names, so an editor setting would be better.

**Comment by cdsmith** [comment]
In general, I'm not great at UI design, so I probably won't get to this.  But it's definitely in the "patches are welcome" category.

**Comment by nixorn** [comment]
I'm on it.

**Comment by nixorn** [comment]
As I see best way to do this is use CSS variables. But this technology is not supported under IE. Is it ok for us?
More information about where CSS variables supported https://caniuse.com/#feat=css-variables

**Comment by cdsmith** [comment]
I think it would be okay to use CSS variables, if that makes the implementation substantially easier.
