### ISSUE TITLE
Vertical line spacing changes between light and dark modes

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#919]
@nixorn: any ideas here?

Switching to dark mode causes line spacing to be different in CodeMirror.  Lines that are spread apart in light mode get packed tighter in dark mode.  It's not even that I mind... but the fact that there's a difference is disorienting when swapping between the two.  It should be consistent one way or the other.

For instance, try swapping between light and dark mode here: https://code.world/#P8Lvn0-QKxAd5G5WECj_x6A  The code is much more compact in dark mode.

**Comment by nixorn** [comment]
More likely it is because I used different theme for codemirror. Will fix it.
