### ISSUE TITLE
In dark mode, some things are still light

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#920]
Dark mode isn't quite complete.  These things still have a light color:

1. Doc-on-hover and error message tooltips
2. Autocomplete, and its accompanying doc tooltips
3. Alert boxes from SweetAlert2.
4. Some shadows (e.g., on tooltips) are now lighter than their background, and it looks weird.

The third is less important than the first two.

@nixorn: Something for your backlog?

**Comment by nixorn** [comment]
Yes, ok. Can you add this to https://github.com/google/codeworld/projects/10?

**Comment by cdsmith** [comment]
Fixed the 4th point.  Remaining:

1. Doc-on-hover and error message tooltips
2. Autocomplete, and its accompanying doc tooltips
3. Alert boxes from SweetAlert2.
