### ISSUE TITLE
Argument helper tooltip triggers outside the appropriate layout context

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#927]
**Shared Program**: https://code.world/#P_TpB3b2qR9Z_U5JCDjzQtA

**Description**

In this example, the arg-helper tooltip for `colored` appears for the entire remainder of the file after the syntax error on line 5. It's probably hard to avoid detecting the error before line 10 (where GHC find it, too). But after line 10, syntax highlighting has already identified the new layout context, and the argument helper should take that cue and give up, as well.

**Comment by devanshbatra04** [comment]
Working on it.
