### ISSUE TITLE
When using dark mode, the examples in the Extras section of the guide cannot be read.

### ISSUE THREAD

**Issue by alphalambda** [google/codeworld#936]
The examples in the Extras section of the guide, which are generated by haddock, cannot be read when in dark mode, because both the font color and the background are white.

**Comment by cdsmith** [comment]
@nixorn Is this something you can fix?  I think you're a lot more familiar with the dark theme than I am.

**Comment by nixorn** [comment]
@cdsmith yes, will fix tomorrow morning.
