### ISSUE TITLE
clipped: clipping an existing image

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#941]
As I was considering what it would mean to have a conceptually infinite `coordinatePlane`, it occurred to me that `clipped :: (Picture, Number, Number) -> Picture` would be useful, where `clipped(pic, w, h)` is `pic` inside a central w-by-h rectangle, and transparent elsewhere. 
 Implementation is easy, using https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clip.

This fills some of the more trivial use cases of #28 but without the semantic complexity or implementation difficulties.

**Comment by alphalambda** [comment]
The `clipped` function was in my wish list, but I would like to be able to clip along an arbitrary path, so that I can *punch* holes in pictures and create textures that do not *bleed*. Maybe we could have a  simple rectangular `clipped` and an advanced `clippedAlongPath` version.

**Comment by cdsmith** [comment]
Hmm.  If this gets too complex, then I think I'd prefer a more general-purpose API like #28 instead of a bunch of special cases, at least in the default API.  Constructive geometry is a much better approach to things like cutting holes out of pictures, etc.

**Comment by alphalambda** [comment]
I have not thought about it enough to grasp whether implementing clipping along a path would be as complex as implementing constructive geometry or not. The rest of my comment here applies only in case implementing `clipped` is worth it.

If that is the case, then `clipped` would probably be implemented in `codeworld-api` in terms of an internal `clippedAlongPath` function anyway. My only request is that `clippedAlongPath` is exported from `codeworld-api` even if it is not included in `codeworld-base.Prelude`.

**Comment by cdsmith** [comment]
The implementation for clipping along a path is definitely easier.  I'm concerned that as use cases are added, the interface will explode in complexity.  The key question is this: what is a clipping region, really? Is it good enough to clip to a straight-line path?  Probably not.  The natural next thing to ask for is clipping along bezier curves, or circles.  CodeWorld doesn't have a "path" or "region" type to represent these options.

Up until now, CodeWorld has been able to simplify a lot by insisting that there's only one Picture type representing figures on the screen.  This contrasts with other libraries, which often have different types for paths, shapes, figures, collages, etc.  In that spirit, it would be great if we could somehow reuse Picture as the type to represent a clipping region.  But then clipping is really just `&` with different alpha compositing rules, and that gets right back to the constructive geometry angle.

**Comment by cdsmith** [comment]
Similar to other cases, we'd probably want to special-case certain "easy" cases in the implementation to just use clipping in the canvas API.

**Comment by alphalambda** [comment]
I think clipping along a polygonal line would be good enough for most purposes. That is the only primitive that needs system support. The rest can be done in user space. For example, it is easy to convert a polygonal line to a bezier curve in user space:

https://code.world/#PyHY0FN1daLiqKAVICuVAlA

**Comment by cdsmith** [comment]
I've implemented rectangular clipping, but not exported it.  I'm most interested in using it for `parametricDrawingOf` for now.  More general APIs can come later.
