### ISSUE TITLE
Migration script fails when haskell/projects or blocklyXML/projects do not exist

### ISSUE THREAD

**Issue by alphalambda** [google/codeworld#954]
The migration script halts with an error if the directories haskell/projects or blocklyXML/projects do not exist. It should either assume nothing needs to be migrated there or create those directories if they are needed.

**Comment by starsandspirals** [comment]
This is also the case for the directory data/codeworld/projects, if it does not yet exist.

**Comment by cdsmith** [comment]
Okay, this shouldn't be hard to fix, at least.

**Comment by cdsmith** [comment]
FYI @nixorn
