### ISSUE TITLE
After updating the code with the new migration, I can no longer run CodeWorld programs.

### ISSUE THREAD

**Issue by alphalambda** [google/codeworld#955]
In the JavaScript console, it shows: 
POST https://blackeyepeas.phys.lsu.edu/cwn/compile 500 (Internal Server Error)
codeworld.js:1303 Can not parse error header: Sorry!  Your program couldn't be run right now.

I'm not sure what the problem is.

**Comment by alphalambda** [comment]
Some more info: In the Network/Preview tag for the `compile` message I see:
A web handler threw an exception. Details:
data/codeworld/user/PQ3/PQ3lejF08xjTPO9g5Urh70A.hs: openBinaryFile: does not exist (No such file or dir

When I inspect the filesystem, I see the directory data/codeworld/user/PQ3lejF08xjTPO9g5Urh70A/ exits but it is empty. (Note no /PQ3/)

Not sure if that helps...

**Comment by alphalambda** [comment]
The problem is definitely with the migration code, because after I reverted that commit in my local branch, the codeworld server works again.

**Comment by cdsmith** [comment]
Okay, that's strange.  I tested this pretty thoroughly before merging.  It wasn't supposed to change anything  except data/*/projects.  I'm looking into it.  Is there anything unusual about your setup?  Are you perhaps sharing a data folder between the old and new server versions?

**Comment by cdsmith** [comment]
FYI @nixorn

**Comment by cdsmith** [comment]
Okay, yes, it looks like the new code accidentally dropped the prefix in data/$MODE/user as well.  I'm sorry for the breakage.  I should have been more careful in testing.  Fix is coming soon.  Fortunately, it's been around short enough that I can probably fix data in prod by hand, and your test server probably doesn't need share URLs to keep working.

**Comment by cdsmith** [comment]
Okay, I know what happened, and it's easier than I thought to fix.  There was an accidental change to `ensureSourceDir`, which is what makes sure that `data/codeworld/user/PQ3` exists before writing to it.  On the production server, all 4096 of these possible directories already exist, so `ensureSourceDir` isn't actually needed any more!  On your system, it was creating the wrong directory, which caused the next steps to fail.

**Comment by cdsmith** [comment]
If it helps anyone, this was the command that I used to clean up the (empty) incorrect directories created by the bug:

    find data/*/user -maxdepth 1 | grep -E 'data/.*/user/P....' | xargs rmdir
