### ISSUE TITLE
Folders in new tree UI don't show as expandable until after clicking

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#977]
![image](https://user-images.githubusercontent.com/544744/59567470-31d52300-903c-11e9-9a55-661483e5d400.png)

The folders that I haven't clicked yet show just a folder icon, and no expansion indicator.  After clicking, they get the expansion indicator, and it doesn't go away.  This is confusing to me.  I'd rather they just display with the expansion indicator no matter what.

**Comment by cdsmith** [comment]
It seems that empty folders don't get a chevron.  Most likely, when a folder hasn't been opened, the system thinks it's empty.  If there's an option to show expansion controls even for empty nodes, that would fix it.

**Comment by nixorn** [comment]
jqTree by default no matters what node is - directory, file, etc. Node is just node and only way to make node expansible is add children to it.  
Node.type = project | directory is custom property I used to  set icons and logic, it is not jqTree option.

Default jqTree behavior - only expansible nodes(nodes with children) get chevrons.

Another point is expand/collapse node and select/deselect node are not related events, node can be deeply inside collapsed tree but still selected, or some node can be selected while other nodes are expanded.

I see two ways to make this work as you want
1. make node collapsible/expansible logic dependent not from children, but from node type. I'm not sure it is easy.
2. Disable jqTree chevrons and make our own via custom node html and call open/close events from code.

**Comment by cdsmith** [comment]
I don't think showing the expansion UI for an empty node is necessary.  But I do think that it needs to be shown for a node that's not loaded yet.  Is there some way to hack around that?  For instance, maybe you can add a placeholder child node in every folder until it's actually loaded?

**Comment by nixorn** [comment]
Ok, I hope I'll have time to do something with styles tomorrow.

**Comment by Powell-v2** [comment]
I believe this one is resolved now since the whole tree is loaded at once?

**Comment by cdsmith** [comment]
Yes.
