### ISSUE TITLE
Missing asterisk for modified projects in tree view

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#982]
Before the new tree view, a project showed up with an asterisk to indicate it had unsaved changes.  This is no longer happening.  The window title is changed, but there's no asterisk in the project sidebar.

**Comment by nixorn** [comment]
I fixing this.
Btw, we could do tree view more similar to modern editor. We can have more than one modified project in same time with several asterisks in tree.

**Comment by cdsmith** [comment]
I definitely like the idea of updating the tree view.  I'm not a fan of having multiple dirty projects, though.  I think it makes it much more complicated to see what's going on, or what to expect when you click on Save (save all?  Just one?)

**Comment by nixorn** [comment]
Most of editors have different buttons for saving current/saving all.
![image](https://user-images.githubusercontent.com/5370736/59662653-0c6c2480-91b6-11e9-9d89-fc70766bde06.png)

`warnIfUnsaved` on switching between projects looks not very well (my opinion). Popup which breaks current user mind context and force to click several buttons before jump to desired code.

**Comment by nixorn** [comment]
Also most of editors have tabs, which is also convenient.
![image](https://user-images.githubusercontent.com/5370736/59663119-00cd2d80-91b7-11e9-9050-7152e36be7f1.png)
