### ISSUE TITLE
Issues with DrawState

### ISSUE THREAD

**Issue by sjakobi** [google/codeworld#994]
https://github.com/google/codeworld/blob/657bf8d3f9a98002cef11fc3e7bbb2f3e8386efd/codeworld-api/src/CodeWorld/Driver.hs#L291-L293

Issues:

1. It's not obvious how the affine transformation matrix is represented.
1. The fields are all lazy, increasing chances of a space leak.
1. The comment is outdated: We have a `Maybe Color` instead of a `Bool`.

So my understanding is that `(a, b, c, d, e, f, _mcolor)` represents the following matrix: (Linear algebra is not my strongest point though)

```
a b e
c d f
0 0 1
```

Can we simply replace the tuple with a more descriptive record with strict fields?

**Comment by cdsmith** [comment]
Sounds good to me.

**Comment by cdsmith** [comment]
More details about the trasnformation nmatrix are at https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/transform
